### ISSUE TITLE
how to add spaces as pairs when inside a pair?

### ISSUE THREAD

**Issue by hunleyd** [echasnovski/mini.nvim#10]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

Thanks for the excellent plugin! One small question though, how do I configure mini.pairs to make a pair of spaces but only when inside another pair? For example, if I enter:
```
{{ |
```
(where `|` is the cursor), I want it to output:
```
{{ | }}
```

Obviously, I do not want a pair of spaces when inserting something like:
```
text |
```

Obviously, I would like this for any char that is recognized as a pair, not just `{`.

Is this doable as is w/ a clever mapping? Or would you have to implement this in plugin code? I feel like the sample mapping for `<` in the wiki comes close but I can't figure out how to alter that to this need.

Thanks!

As an aside, while looking at the wiki example for `<` I realized I don't know how to add additional chars to the recognized pairs. The wiki says:
```
The following pairs are respected: `()`, `[]`, `{}`, `""`, `''`, `\`\``. 
```
But how would I add `<>` or '%%' (or some other arbitrary pairing)  to that list? Is there a config var for it that I missed?

**Comment by echasnovski** [comment]
Thank you for your kind words!

Originally, informal general idea of 'mini.pairs' is this: "here are a bunch of autopairs-related actions; use them to make mappings for keys that you want; common ones are already done by default". I might rethink this in future, because coming back to it, this might be a little bit heavy on user-friendliness.

So about spaces. There are three actions supported: `open()`, `close()`, `closeopen()`. All of them work if cursor neighborhood (characters to left and right of cursor) is matched with supplied `twochars_pattern` (which is a [Lua pattern](https://www.lua.org/manual/5.1/manual.html#5.4.1)). Unfortunately, Lua patterns don't seem to support alteration. So user can't say "match if neighborhood is this, or this, or this". The closest behavior to this might be "match if left character is one of these and right character is one of these". To add this behavior to space which checks for `([{` to the right and `)]}` to the left, make a standard Neovim mapping:
- In Lua:
    ```lua
    vim.api.nvim_set_keymap('i', ' ', [[v:lua.MiniPairs.open('  ', '[%(%[{][%)%]}]')]], { expr = true, noremap = true })
    ```
- In Vimscript:
    ```vim
    inoremap <expr> <space> v:lua.MiniPairs.open('  ', '[%(%[{][%)%]}]')
    ```

With `<>` everything is the same: make mappings. You, probably, would want something like this:
- In Lua:
    ```lua
    vim.api.nvim_set_keymap('i', '<', [[v:lua.MiniPairs.open('<>', '[^\\].')]], { expr = true, noremap = true })
    vim.api.nvim_set_keymap('i', '>', [[v:lua.MiniPairs.close('<>', '[^\\].')]], { expr = true, noremap = true })
    ```
- In Vimscript:
    ```vim
    inoremap <expr> < v:lua.MiniPairs.open('<>', '[^\\].')
    inoremap <expr> > v:lua.MiniPairs.close('<>', '[^\\].')
    ```

A big **NOTE** though. Currently all this does is mapping a key to an action. To make `<BS>` and `<CR>` respect new pairs, you need to remap them accordingly (supply full table of cursor neighborhoods in which those should act).

**Comment by hunleyd** [comment]
excellent, thank you! i have this working as desired now.

**Comment by echasnovski** [comment]
@hunleyd, wanted to mention that thanks to this issue I decided to slightly redesign mapping process in 'mini.pairs' to make it (hopefully) more user-friendly. Now you can make global mappings in `config` and they will be automatically registered for `<BS>` and `<CR>` (if not changed explicitly). Also work with pair mappings now should be done with `MiniPairs.map()`, `MiniPairs.map_buf()`, `MiniPairs.unmap()`, `MiniPairs.unmap_buf()`.

For example, global mappings for ` `, `<`, and `>` can look something like this:
```lua
  require('mini.pairs').setup({
    mappings = {
      [' '] = { action = 'open', pair = '  ', neigh_pattern = '[%(%[{][%)%]}]' },
      ['<'] = { action = 'open', pair = '<>' },
      ['>'] = { action = 'close', pair = '<>' },
    },
  })
```

Also, all previous mappings (except ones with `MiniPairs.bs()` and `MiniPairs.cr()` which use custom pair list) still work as before.

**Comment by aik2mlj** [comment]
Hi, I am trying to achieve auto-spacing inside a pair of `$`. This is essential for typst setup.
However, this setup does not work. I tried to substitute the `neigh_pattern` as `%(%)` and it just works for `()` pairs. Could you help me on that?
```lua
require("mini.pairs").setup({
  mappings = {
    [" "] = { action = "open", pair = "  ", neigh_pattern = "%$%$" },
    ["$"] = { action = "closeopen", pair = "$$" },
  },
})
```

**Comment by echasnovski** [comment]
> ```lua
> require("mini.pairs").setup({
>   mappings = {
>     [" "] = { action = "open", pair = "  ", neigh_pattern = "%$%$" },
>     ["$"] = { action = "closeopen", pair = "$$" },
>   },
> })
> ```

With this exact setup everything seems to work as expected. Here is the demo:

https://github.com/user-attachments/assets/f4273a16-4d14-4835-8915-8d2312cc719b

Does `:imap <Space>` show the mapping from 'mini.pairs'?

**Comment by aik2mlj** [comment]
> Does :imap <Space> show the mapping from 'mini.pairs'?
Yes, it shows:
```
i  <Space>     * v:lua.MiniPairs.open("  ", "%$%$")
                 Open action for "  " pair
```
But I can't get the auto spacing work.

**Comment by echasnovski** [comment]
> > Does :imap  show the mapping from 'mini.pairs'?
> 
> Yes, it shows:
> 
> ```
> i  <Space>     * v:lua.MiniPairs.open("  ", "%$%$")
>                  Open action for "  " pair
> ```
> 
> But I can't get the auto spacing work. I'm on neovim 0.10.1

I am not sure what to tell here. With this mapping for `<Space>` in Insert mode it should turn `$$` into `$  $` when pressing `<Space>` in between `$$`. Just like in demo.

I guess the best suggestion is to try reproducing with only 'mini.pairs' enabled. It should not reproduce. And after that try bisecting the config until you find the relevant part that makes it work as you see.

**Comment by stefanboca** [comment]
@aik2mlj I also ran into this issue with spaces. For me it was because of [this](https://github.com/LazyVim/LazyVim/blob/ecfaed3cc1cbe3013f1201594adde2ea0022c455/lua/lazyvim/util/mini.lua#L149-L150) and [this](https://github.com/LazyVim/LazyVim/blob/ecfaed3cc1cbe3013f1201594adde2ea0022c455/lua/lazyvim/plugins/coding.lua#L121) in LazyVim. I managed to fix this by removing `$` from the `skip_next` pattern:

```lua
{
  "echasnovski/mini.pairs",
  opts = {
    skip_next = [=[[%w%%%'%[%"%.%`]]=],
  },
}
```

and this was my config:
```lua
local pairs = require("mini.pairs")
pairs.map_buf(bufnr, "i", " ", { action = "open", pair = "  ", neigh_pattern = "%$%$" })
pairs.map_buf(bufnr, "i", "$", { action = "closeopen", pair = "$$" })
```
