### ISSUE TITLE
Closed buffers always shows up in tabline

### ISSUE THREAD

**Issue by prashanth-hegde** [echasnovski/mini.nvim#102]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini-tabline

### Description

I love mini plugin. It has greatly simplified my nvim workflow!

In the mini tabline, there is no option to disable hidden buffers. Reading the tabline when buffers are closed causes confusion in navigation. Could you please add an option to not show hidden buffers in tabline? A screenshot is attached for reference. 
In the screenshot, there are only two active tabs, the others are hidden buffers. 
One more thing to note is that toggling `set_vim_settings` to true or false doesn't seem to have any effect on this behavior. I've tried both.

![image](https://user-images.githubusercontent.com/11544150/181918338-c6efa57c-0d8d-496a-b715-d41d6e10996b.png)

### Neovim version

0.7.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Open multiple tabs with different files
3. Close a subset of the tabs by quitting those files/buffers
4. Observe that the closed tabs still show up in tabline even after closing

My tabline config: 
```lua
require('mini.tabline').setup({
  tabpage_section = 'right',
  set_vim_settings = true,
})

```

### Expected behavior

buffers that are closed shouldn't show up in the tabline

### Actual behavior

closed buffers never goes away from tabline causing confusion in navigation

**Comment by echasnovski** [comment]
Thanks for kind words! And for using 'minischeme' (at least temporarily :) ).

'mini.tabline' shows all **listed** buffers (i.e. buffers that [show in the buffer list](https://vimhelp.org/options.txt.html#%27buflisted%27)). Hidden buffers are [the ones "on the list" but you just can't see them](https://vimhelp.org/windows.txt.html#hidden-buffer).

How did you "close the buffer"? If you execute `:bdelete` (which delete buffer from the buffer list), does it go away?

**Comment by prashanth-hegde** [comment]
glad to be using mini plugin :) 

yeah, nothing fancy in my setup, here are some commands to reproduce: 

```
nvim     # open a new nvim process
:e test1.txt     # open a random file
:tabnew test2.txt   # another random file 
:tabnew test3.txt.  # another one 
:q!        # quit test3.txt
```

At this point, the tabline shows three files `test1.txt, test2.txt, test3.txt` 
But there are only two files I am working with

**Comment by echasnovski** [comment]
> But there are only two files I am working with

Not really. In (Neo)Vim buffer, window, and tab page are different. As [windows-intro](https://vimhelp.org/windows.txt.html#windows-intro) has it:
```
A buffer is the in-memory text of a file.
A window is a viewport on a buffer.
A tab page is a collection of windows.
```

In your example:
- `:e test1.txt` creates a buffer for file `test1.txt` and shows it in current window.
- `:tabnew test2.txt` creates a buffer for file `test2.txt`, creates new tab page, and shows this buffer in new window.
- `:tabnew test3.txt` does the same, but for `test3.txt`.
- `:q!` closes window from tag page 3 (which leads to closing of a tab page itself). However, buffer is still there. It is hidden (because it is not shown anywhere), but you can still use it (try `:bnext` after last command). 'mini.tabline' is intended to show buffer, not tab pages or windows.

You can get more information about this by searching something like "buffer vs tabs in vim".

**Comment by fooness** [comment]
@echasnovski Is there any way to make mini.tabline only show tabs/windows instead of buffers?

Unfortunately it’s rather counter-intuitive and rather weird that mini.tabline shows _closed_ (`:q`) buffers, but these visual tabs in the tabline are skipped when next-tabbing (`gt`) through the shown tabs/buffers.

**Comment by echasnovski** [comment]
> As [windows-intro](https://vimhelp.org/windows.txt.html#windows-intro) has it:
> 
> ```
> A buffer is the in-memory text of a file.
> A window is a viewport on a buffer.
> A tab page is a collection of windows.
> ```

You don't *close* buffer with `:q`, you *close* window which displayed that buffer. The 'mini.tabline' module is designed as "tabline showing listed buffers", so it is reasonable that it still shows buffer which is still there. To actually "close buffer" there are [`:bdelete`](https://neovim.io/doc/user/windows.html#%3Abdelete) and [`:bwipeout`](https://neovim.io/doc/user/windows.html#%3Abwipeout).

To show only tabpages with some of their extra information in tabline, use default tabline: set `showtabline` option to 2 and don't set up 'mini.tabline'.
