### ISSUE TITLE
Auto integrations 'mini.base16' with  LSP and Treesitter

### ISSUE THREAD

**Issue by mohamad-supangat** [echasnovski/mini.nvim#106]
i would love if mini.nvim could integrate easily with some lsp for neovim,

Neovim LSP and DAP
coc.nvim
and Treesitter

some references :
https://github.com/catppuccin/nvim/blob/cb80c9125e3d17a83549e0179a30d1f72b9e6315/lua/catppuccin/groups/integrations/treesitter.lua
https://github.com/catppuccin/nvim/blob/cb80c9125e3d17a83549e0179a30d1f72b9e6315/lua/catppuccin/groups/integrations/native_lsp.lua
https://github.com/catppuccin/nvim/blob/cb80c9125e3d17a83549e0179a30d1f72b9e6315/lua/catppuccin/groups/integrations/coc_nvim.lua

_Originally posted by @mohamad-supangat in https://github.com/echasnovski/mini.nvim/discussions/36#discussioncomment-3345454_

**Comment by echasnovski** [comment]
Thanks for this!

Per source:
- Treesitter *is* supported implicitly because all `TS*` highlight groups by default come linked to builtin ones. Which seem to work fine. At least I haven't noticed anything that catches my eye. If you think about some specific highlight group, let my know.
- 'mini.base16' [has support](https://github.com/echasnovski/mini.nvim/blob/a60055a492296aa1fa5838ff5fdd2b85df96acdd/lua/mini/base16.lua#L490-L531) for built-in diagnostics, which is almost all highlight groups in that link. I'll at the rest.
- 'coc.nvim' is a good candidate for being supported. Thanks!

**Comment by echasnovski** [comment]
I pushed update to 'mini.base16' with many new integrations. Please, check it out.

**Comment by mohamad-supangat** [comment]
> I pushed update to 'mini.base16' with many new integrations. Please, check it out.

thank you very much, I am very happy with this good news
