### ISSUE TITLE
Mini.files spaces after and before Title

### ISSUE THREAD

**Issue by 6H075T2** [echasnovski/mini.nvim#1062]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Really liked this plugin a lot and configuring this plugin to my liking but I couldn't figure out on how I can configure this plugin to add spaces with its Title to make it look like the Footer below.

![image](https://github.com/user-attachments/assets/d8a580c0-2bcf-4926-a47e-42f91ef3b478)

I'm currently learning how to code in Lua and please have patience with me.

**Comment by echasnovski** [comment]
If possible, it would be something along the lines of [customizing window](https://github.com/echasnovski/mini.nvim/blob/f20d8cd3a116ef65f022797de064a044b217ff53/doc/mini-files.txt#L372-L388) example, but with `MiniFilesWindowUpdate` event (because title can change after window is opened).

However, quick tests showed that title is somewhat special, as it indeed updates when navigating horizontally. I am afraid, declaring title "special" and not designed to be customized is a reasonable approach here.

**Comment by echasnovski** [comment]
Icons are the result of applying [`default_prefix()`](https://github.com/echasnovski/mini.nvim/blob/691c5f38f575b572d0c857bd22c35be9a1512925/doc/mini-files.txt#L820) which is used by default as `config.content.prefix`.

Here is an example of how to override it so that there is an extra space before an icon:

```lua
local prefix = function(fs_entry)
  local icon, hl = MiniFiles.default_prefix(fs_entry)
  return ' ' .. icon, hl
end
require('mini.files').setup({ content = { prefix = prefix } })
```

**Comment by 6H075T2** [comment]
@echasnovski, Thanks for very fast response now it works as I intended and looks nice. But my current concern is about the link you've provided in customizing window example why is it that the "Title" property when assigned by a function that returns the current working directory as a title doesn't automatically add spaces like the a normal title would do.

**Comment by echasnovski** [comment]
> But my current concern is about the link you've provided in customizing window example why is it that the "Title" property when assigned by a function that returns the current working directory as a title doesn't automatically add spaces like the a normal title would do.

I don't really understand the question. By default titles in floating windows are not padded with spaces.

The reason customization doesn't apply for titles is because they are a bit special as described in the original response:

> However, quick tests showed that title is somewhat special, as it indeed updates when navigating horizontally. I am afraid, declaring title "special" and not designed to be customized is a reasonable approach here.

**Comment by echasnovski** [comment]
@6H075T2, after some recent changes, I *think* adding space padding to title now should be possible. You can follow the [newly added example](https://github.com/echasnovski/mini.nvim/blob/974ebc04dff3b59899a5eee29157a9bbfd85dce3/doc/mini-files.txt#L393-L411) (without the `config.height` part) and it should work.

This use case even has a [dedicated test](https://github.com/echasnovski/mini.nvim/blob/974ebc04dff3b59899a5eee29157a9bbfd85dce3/tests/test_files.lua#L3870-L3877) in the hope that it will keep working.

I changed my mind about this issue because height also could not be customized (see #1140). As the root cause has revealed to be the same (intentional blocking of too frequent `MiniFilesWindowUpdate` event triggering), it seems to be more reasonable to change the balance here (from preferring performance to preferring actual customization with [heavy warning that it is triggered frequently](https://github.com/echasnovski/mini.nvim/blob/974ebc04dff3b59899a5eee29157a9bbfd85dce3/doc/mini-files.txt#L330).

**Comment by 6H075T2** [comment]
@echasnovski, I never thought you'll give my request some attention since it's I've considered it silly because I don't think anyone even want this feature and possibly even go againts your project principle, I really appreciate your effort to make this possible. <3

Here's what it looks now.
![image](https://github.com/user-attachments/assets/05bd18e2-3fbd-42b4-bab5-7e4071f72c82)

I'm looking forward to your mini.statuscolumn plugin 😊

**Comment by 6H075T2** [comment]
Hi, @echasnovski I've noticed this visual bug ↓
![Untitled](https://github.com/user-attachments/assets/1b80de25-ec78-4901-9f16-55599b1b51f9)
This only happens when a floating window has a long directory title, becomes contracted and unfocused makes the padding on the right gone and not consistent with the left padding as it doesn't appends an empty space in the end.

Thank you for this wonderful update with bookmarks, its nice to have :>

**Comment by echasnovski** [comment]
> This only happens when a floating window has a long directory title, becomes contracted and unfocused makes the padding on the right gone and not consistent with the left padding as it doesn't appends an empty space in the end.

That's expected because width of windows are fixed and can be configured [inside `config.windows`](https://github.com/echasnovski/mini.nvim/blob/3eb07050b25520a4ca011473a3f5dbf56273cb9d/doc/mini-files.txt#L602-L607). So it looks like just a coincidence of the title length being strictly on character less than window width.

**Comment by 6H075T2** [comment]
I forgot to include that the Neovim's window is minimize and not in Fullscreen that's why it happens. 🤦
Thanks for the response :3
