### ISSUE TITLE
[surround] Add insert mode surround mappings

### ISSUE THREAD

**Issue by kmoschcau** [echasnovski/mini.nvim#1085]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

I recently migrated to mini.surround from nvim-surround. First of all, good job with the plugin, the dot-repeat works great!

The only thing I'm currently missing, is an insert mode mapping for surrounding things. nvim-surround had `<C-g>s` for inline-surround and `<C-g>S` for line-surround. Could this functionality please be added to mini.surround?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I hoped that something making a mapping to `<C-o>sa` would work, but it does not due to complications of how mapping are implemented.

Unfortunately, properly adding Insert mode mappings would require a lot of user configuration to be useful (like keys for Insert mode mapping for every action). Reading more about what [`<C-g>s`](https://github.com/kylechui/nvim-surround/blob/ec2dc7671067e0086cdf29c2f5df2dd909d5f71f/doc/nvim-surround.txt#L60) and [`<C-g>S`](https://github.com/kylechui/nvim-surround/blob/ec2dc7671067e0086cdf29c2f5df2dd909d5f71f/doc/nvim-surround.txt#L106) do in 'kylechui/nvim-surround', they can be replicated with the following user mappings (because thankfully surrounding visual selection after `<C-o>` works):

```lua
vim.keymap.set('i', '<C-g>s', '<C-o>vsa', { remap = true })
vim.keymap.set('i', '<C-g>S', '<C-o>Vsa', { remap = true })
```

Closing as not planned.

**Comment by kmoschcau** [comment]
Understandable that you don't want to add it. The mappings work nicely, thank you.
