### ISSUE TITLE
(mini.icons) Extension is not resolved when contains multiple dots

### ISSUE THREAD

**Issue by haus20xx** [echasnovski/mini.nvim#1086]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.icons

### Description

Since pulling in the latest breaking commits my expected behavior around extension matching is broken. From reading the commit descriptions it doesn't seem like this is an expected change.

I use an extension config to match `spec.ts` files in order to visually distinguish them from the raw `ts` files, in particular when using mini.files. 

![image](https://github.com/user-attachments/assets/64c69ba7-9782-4a08-bfcd-586e2e2b51cd)

If I revert to `d990e3d` then my expected and actual behavior match.

### Neovim version

NVIM v0.11.0-dev-487+gc025c049a

### Steps to reproduce

1. `nvim -nu minimal.lua` (setup `mini.icons` with some `extension` override, e.g. `["spec.ts"] = { hl = "MiniIconsYellow}` ) 
2. `:=MiniIcons.get('file', '~/path/file.spec.ts')`
3. `:=MiniIcons.get('file', '~/path/file.name.spec.ts')`

### Expected behavior

`MiniIcons.get('file', '~/somepath/file.spec.ts')` == `MiniIcons.get('file', '~/somepath/file.name.spec.ts')`

### Actual behavior

`MiniIcons.get('file', '~/somepath/file.spec.ts')` uses the configured hl from `extension` configuration.
`MiniIcons.get('file', '~/somepath/file.name.spec.ts')` does NOT use the configured hl from `extension configuration. I believe it ends up using the filetype instead.

The two outputs on `d990e3d`
![image](https://github.com/user-attachments/assets/6b7691b2-4f09-44ed-8c65-a4e8a84f6aa1)

The two outputs on `842e51b` (latest)
![image](https://github.com/user-attachments/assets/8f426402-dd5d-4dc9-b65b-e31d3457660d)

**Comment by echasnovski** [comment]
Thanks for the issue!

The icon data gets resolved as expected which unfortunately doesn't work out of the box for these (rather niche) cases. The reason is that 'name.spec.ts' extension gets itself resolved as 'ts'. This can be worked around with proper `config.use_file_extension`:

```lua
require('mini.icons').setup({
  extension = {
    ['spec.ts'] = { hl = 'MiniIconsYellow' },
  },
  use_file_extension = function(ext, _) return not vim.endswith(ext, '.spec.ts') end,
})
```

I'll take a look if there is something to be done for better out of the box experience, but at the moment I think the suggested approach is a reasonable tradeoff (considering what should be a rather infrequent occurrence).

**Comment by haus20xx** [comment]
Ah, I think I may have misunderstood how/what `use_file_extension` was doing. Your suggestion does indeed restore my intended use case and is more than acceptable for me. Appreciate the expedient response(and all the work you've done with these libraries)!

**Comment by echasnovski** [comment]
This proved to be a bigger problem which resurfaced after recent changes. The issue here is that "extension" category itself doesn't resolve such cases:
- `MiniIcons.get('extension', 'spec.ts')` with default config *will* return typescript icon because `vim.filetype.match()` will recognize it.
- `MiniIcons.get('extension', 'name.spec.ts')` with config from this issue will also return typescript icon for the same reason.

Let's keep this open for now. I'll see if this is reasonable to adjust.

**Comment by echasnovski** [comment]
This now should be resolved on latest `main` with "extension" category having own explicit resolution of compound extensions.

@haus20xx, your previous config should now work without having to configure `use_file_extension`.
