### ISSUE TITLE
Mini.operators: if you have a custom mapping on _ (underscore), the line (grr, gxx, gmm) operators break

### ISSUE THREAD

**Issue by tuurep** [echasnovski/mini.nvim#1088]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.operators

### Description

I have this mapping in my configs:

```lua
vim.keymap.set({"n", "x", "o"}, "_", "H")
```

And narrowed that down to why my mini.operators `grr`, `gmm`, `gxx` and possibly `g==` aren't working as intended. (Note, `gss` works)

Whatever I've mapped to `_` acts as the motion, so in my case, would operate til the top of the visible window.

I'm wondering, is there like some `!` (bang) missing somewhere in the code where re-mappings should be ignored? Or some similar small thing like this.

### Neovim version

v0.10.1

#### Minimal config

`minimal.lua`:

```lua
vim.keymap.set("o", "_", "<cmd>echo('Hi!!!')<cr>")

vim.fn.system({
    "git", "clone", "--depth=1",
    "https://github.com/echasnovski/mini.operators",
    "plugins/mini.operators"
})

vim.opt.runtimepath:append("plugins/mini.operators")
require("mini.operators").setup()
```

#### Repro

```
$ echo "test foo bar" > test.xt
$ nvim -nu minimal.lua test.txt
```

Press `gmm`

Notice how only the character under cursor gets duplicated, and the custom keymapping `<cmd>echo('Hi!!!')<cr>` is used.

Similar thing happens with `gxx`, `grr` and `g==`, but **not** `gss`

### Expected behavior

I expect that I can have an operator-pending mapping on `_` without affecting the behavior of this plugin.

**Comment by echasnovski** [comment]
Thanks for the issue!

This is an expected and [documented](https://github.com/echasnovski/mini.nvim/blob/e24ec1fcf885990fec1a993fe8304a033fd1806d/doc/mini-operators.txt#L396) behavior. Line variants are usually a direct mapping which relies on `_` built-in textobject. You can see it by `:nmap grr`, for example. This is not the case for `gss` which maps to `^gsg_`, which is [also documented](https://github.com/echasnovski/mini.nvim/blob/e24ec1fcf885990fec1a993fe8304a033fd1806d/doc/mini-operators.txt#L397-L398).

> I'm wondering, is there like some `!` (bang) missing somewhere in the code where re-mappings should be ignored? Or some similar small thing like this.

Using `normal!` won't work here as mapping relies on remapped meaning of operator prefixes (so that it will be as if user pressed `gr_`, etc.).

I don't think rewriting the whole mapping logic is worth in this case. So my suggestion would be:
- Don't remap `_` which is a built-in textobject for line.
- Make custom mappings for `grr`, `gmm`, `gxx`, `g==` which eventually uses textobject for current line.

Closing as not planned.

**Comment by tuurep** [comment]
> Don't remap `_` which is a built-in textobject for line.

Ah, that's it. I didn't know it's a text object. Thank you!

**Comment by tuurep** [comment]
Referenced above I have a fix using `feedkeys` with the `"n"` flag ("do not remap keys") that allows me to create prefixes cleanly without workarounds :)

Let me know if that's of interest,
or if the stance is still "not planned", please ignore

**Comment by tuurep** [comment]
Yes, I disagree with you on what's acceptable to remap but also am ready to bear the consequences by doing that 😄 Thanks!
