### ISSUE TITLE
Can't disable local session in mini.sessions

### ISSUE THREAD

**Issue by carnage-mode** [echasnovski/mini.nvim#1099]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

I've tried setting `file = ""` but it doesn't seem to work

### Neovim version

0.10.0

### Steps to reproduce

1. Set `file = ""` in mini.sessions config
2. create a session using mksession
3. Check current directory

### Actual behavior

A `Session.vim` file still gets created

**Comment by echasnovski** [comment]
Creating sessions with 'mini.sessions' should be done via [`MiniSessions.write()`](https://github.com/echasnovski/mini.nvim/blob/691c5f38f575b572d0c857bd22c35be9a1512925/doc/mini-sessions.txt#L146), not the built-in `:mksession`. `MiniSessions.write()` explicitly requires session name: if it is equal to the `config.file`, then file will be created locally, otherwise - in `config.directory` for global sessions. You can also take a look at [this comment](https://github.com/echasnovski/mini.nvim/discussions/33#discussioncomment-4894341) with a bit more details about workflow.
