### ISSUE TITLE
[mini.ai] Incorrect yank for inner tag

### ISSUE THREAD

**Issue by gbcreation** [echasnovski/mini.nvim#110]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Hi,

Maybe it is related to this second issue listed in the help file:

> Known issues which won't be resolved:
> - ...
> - During search for builtin textobjects there is no distinction if it is
  inside string or comment. For example, in the following case there will
  be wrong match for a function call: `f(a = ")", b = 1)`.

but the inner tag yank is not correct when a tag has an attribute whose value contains a `>` character.

### Neovim version

0.7.2

### Steps to reproduce

For example with this tag (`^` is cursor position):

```
<a onclick={() => { /* ... */ }}>link</a>
                                   ^
```

### Expected behavior

`vit` should select this:

```
<a onclick={() => { /* ... */ }}>link</a>
                                 ----
```

### Actual behavior

Actually, it selects this:

```
<a onclick={() => { /* ... */ }}>link</a>
                 --------------------
```

**Comment by echasnovski** [comment]
Thanks for creating an issue!

Yes, unfortunately, this is a limitation of a Lua pattern based approach: I don't see a way of how to distinct which of the `>` is actually a closing an opening tag. Did you look into using treesitter here? Maybe it might help.

**Comment by echasnovski** [comment]
> It works using TreeSitter.

That is great!

It sure should work when mapping is defined in 'nvim-treesitter.textobjects', but with following caveats:
- If you type `a`, then wait for some time (`timeoutlen` milliseconds), and then type `t`, it will use 'mini.ai' textobject. This is due to how 'mini.ai' creates mappings and Neovim resolves them.
- You won't benefit from 'mini.ai' search method, consecutive application, and 'next'/'last' textobjects.

I would suggest creating 'after/ftplugin/html.lua' file and define `vim.b.miniai_config` buffer local variable there like so:
```lua
local spec_treesitter = require('mini.ai').gen_spec.treesitter
vim.b.miniai_config = {
  custom_textobjects = {
    t = spec_treesitter({ a = 'function.outer', i = 'function.inner' }),
  },
}
```
