### ISSUE TITLE
mini.animate scroll to respect scrolloff settings

### ISSUE THREAD

**Issue by 9th8** [echasnovski/mini.nvim#1118]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.animate

### Description

With vim.opt.scrolloff = 9999 and some remapping like 'k' to 'kzz' cursor stays in the middle of the screen even if there is no text below it. However, with mini.animate scroll enabled cursor is bound to bottom of the screen if there is no teхt below it.

Would it be possible to have an option for mini.animate to allow the cursor to stay centered?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Scrolling animation (and resize, for that matter) are suboptimal because they are done with side-effects. See [this section](https://github.com/echasnovski/mini.nvim/blob/af673d8523c5c2c5ff0a53b1e42a296ca358dcc7/doc/mini-animate.txt#L279-L295), which also has a note about special overrides of `nnoremap n nzvzz` and why they don't really work.

Having special option for cursor always being centered seems both too specific and not trivial to implement. At the same time, the current implementation is as best as I can do to support non-default 'scrolloff' value.

Closing as "not planned because it is already as best as it can be under current design".
