### ISSUE TITLE
MiniSession.read() not triggering Treesitter

### ISSUE THREAD

**Issue by 22ispencer** [echasnovski/mini.nvim#1133]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.Sessions

### Description

I'm trying to setup an autocmd to load a local session if it exists, and if not to open mini.starter. I have everything working except when the session does exist and is entered syntax highlighting doesn't work until i reload the buffer via `:e`. I'm new to autocmds, but I couldn't seem to find an answer to this problem. below is a chunk from my config file.

```lua
now(function()
	require("mini.sessions").setup()
	local starter = require("mini.starter")
	starter.setup({
		autoopen = false,
		items = {
			starter.sections.sessions(),
			starter.sections.recent_files(5, true),
			starter.sections.recent_files(5, false),
			starter.sections.builtin_actions(),
		},
	})
	require("mini.icons").setup()
	require("mini.statusline").setup()
	require("mini.tabline").setup()

	add({
		source = "nvim-treesitter/nvim-treesitter",
		-- Use 'master' while monitoring updates in 'main'
		checkout = "master",
		monitor = "main",
		-- Perform action after every checkout
		hooks = {
			post_checkout = function()
				vim.cmd("TSUpdate")
			end,
		},
	})
	-- Possible to immediately execute code which depends on the added plugin
	require("nvim-treesitter.configs").setup({
		ensure_installed = { "lua", "vimdoc", "typescript", "css", "html", "astro" },
		highlight = { enable = true },
	})

	vim.api.nvim_create_autocmd({ "VimEnter" }, {
		callback = function()
			local cwd = vim.fn.getcwd()
			if vim.fn.filereadable(cwd .. "/Session.vim") == 1 then
				MiniSessions.read(nil, {
					force = true,
					hooks = {
						post = function()
							vim.cmd("edit")
						end,
					},
				})
			else
				MiniStarter.open()
			end
		end,
	})
end)
```

### Neovim version

v0.10.0

### Steps to reproduce

1. nvim (in a directory with Session.vim)

### Expected behavior

![image](https://github.com/user-attachments/assets/4432ce87-5551-4865-a04c-910cb59b4591)

### Actual behavior

![image](https://github.com/user-attachments/assets/2eb72987-448b-48fd-8c33-7aea587ef85a)

**Comment by echasnovski** [comment]
> I'm trying to setup an autocmd to load a local session if it exists, and if not to open mini.starter. I have everything working except when the session does exist and is entered syntax highlighting doesn't work until i reload the buffer via `:e`. I'm new to autocmds, but I couldn't seem to find an answer to this problem.

This is indeed not an issue with 'mini.sessions', but an autocommand approach itself. The core issue comes from the fact that 'nvim-treesitter/nvim-treesitter' enables highlighting in the autocommand for `FileType` event. When `MiniSessions.read()` is executed inside a `VimEnter` autocommand, it means that all other events are not triggered because "By default, autocommands do not nest." (see `:h autocmd-nested`). This includes a `FileType` events, which means that 'nvim-treesitter' does not start its highlighting.

The solution is very simple: add `nested = true` above `callback = function()` line for your `VImEnter` autocommand. And there is not need for `post` hook anymore.

The way this could have been deduced (how I ended up doing it) is by first checking that `autoread` in 'mini.sessions' works as expected here. Then take a look at [its implementation](https://github.com/echasnovski/mini.nvim/blob/608e15779f3d672d30c8ee01ad8ff9cac9f7d723/lua/mini/sessions.lua#L453) and notice the `nested = true` flag.

**Comment by 22ispencer** [comment]
Thanks man, I figured it had to be something like that, I just didn't know how to go about debugging it.
