### ISSUE TITLE
Can't change filetype (htmldjango) icon

### ISSUE THREAD

**Issue by Muizzyranking** [echasnovski/mini.nvim#1137]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.icons

### Description

I am trying to change htmldjango filetype icon, but it is still showing the default html icon or htmldjango files.

### Neovim version

NVIM v0.10.1 Build type: RelWithDebInfo LuaJIT 2.1.1720049189

### Steps to reproduce

Using lazy.nvim plugin manager
```lua
return {
    "echasnovski/mini.icons",
    lazy = true,
    opts = {
      file = {
        [".eslintrc.js"] = { glyph = "󰱺", hl = "MiniIconsYellow" },
        [".node-version"] = { glyph = "", hl = "MiniIconsGreen" },
        [".prettierrc"] = { glyph = "", hl = "MiniIconsPurple" },
        [".yarnrc.yml"] = { glyph = "", hl = "MiniIconsBlue" },
        ["eslint.config.js"] = { glyph = "󰱺", hl = "MiniIconsYellow" },
        ["package.json"] = { glyph = "", hl = "MiniIconsGreen" },
        ["tsconfig.json"] = { glyph = "", hl = "MiniIconsAzure" },
        ["tsconfig.build.json"] = { glyph = "", hl = "MiniIconsAzure" },
        ["yarn.lock"] = { glyph = "", hl = "MiniIconsBlue" },
      },
      filetype = {
        htmldjango = { glyph = "==", hl = "MiniIconsBlue" },
      },
    },
    init = function()
      ---@diagnostic disable-next-line: duplicate-set-field
      package.preload["nvim-web-devicons"] = function()
        require("mini.icons").mock_nvim_web_devicons()
        return package.loaded["nvim-web-devicons"]
      end
    end,
    config = function(_, opts)
      require("mini.icons").setup(opts)
    end,
  }
```

### Expected behavior

I expect the icon for htmldjango should be different from the actual html icon.

### Actual behavior

The default html icon is what is being shown.

![image](https://github.com/user-attachments/assets/8143f4fc-d501-4606-b21a-3f693d804f37)

**Comment by echasnovski** [comment]
Customization works as expected here. You can verify it via `:=MiniIcons.get('filetype', 'htmldjango')`.

The problem is that detection of 'htmldjango' filetype [relies on the file content](https://github.com/neovim/neovim/blob/65a703e06063c85c3dd5fdb3ad4e1207a622ef30/runtime/lua/vim/filetype/detect.lua#L732-L737), while 'file' and 'extension' categories in 'mini.icons' can use only supplied file name (or preferably full file path).

As both 'neo-tree.nvim' and (what looks like) 'lualine.nvim' compute icon data based on the file name or path, they display the icon for 'html' filetype. If 'lualine.nvim' used the filetype (as does 'mini.statusline', for example), it would have shown the '==' as icon.
