### ISSUE TITLE
suggestion: use `vim.g.terminal_color_*` to highlight mini.icons by default if they're set

### ISSUE THREAD

**Issue by goolord** [echasnovski/mini.nvim#1138]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.icons

### Description

if you set the highlights in `mini.icons` using the `vim.g.terminal_color_*` variables, it will probably look good enough for most colorschemes and would drastically reduce the work required to support mini.icons everywhere

these are the colors i'm using at the moment
```lua
vim.api.nvim_set_hl(0, 'MiniIconsAzure' , { fg = vim.g.terminal_color_12 } )
vim.api.nvim_set_hl(0, 'MiniIconsBlue'  , { fg = vim.g.terminal_color_4  } )
vim.api.nvim_set_hl(0, 'MiniIconsCyan'  , { fg = vim.g.terminal_color_6  } )
vim.api.nvim_set_hl(0, 'MiniIconsGreen' , { fg = vim.g.terminal_color_2  } )
vim.api.nvim_set_hl(0, 'MiniIconsGrey'  , { fg = vim.g.terminal_color_7  } )
vim.api.nvim_set_hl(0, 'MiniIconsOrange', { fg = vim.g.terminal_color_3  } )
vim.api.nvim_set_hl(0, 'MiniIconsPurple', { fg = vim.g.terminal_color_5  } )
vim.api.nvim_set_hl(0, 'MiniIconsRed'   , { fg = vim.g.terminal_color_1  } )
vim.api.nvim_set_hl(0, 'MiniIconsYellow', { fg = vim.g.terminal_color_11 } )
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I considered it during writing of 'mini.icons', but decided to use default links to built-in groups for at least these reasons:
- Having defined [linked built-in groups](https://github.com/echasnovski/mini.nvim/blob/7c00ea1a6b35332746e1a2fa768e26c5fa9c3589/lua/mini/icons.lua#L1947-L1955) is most certainly more common in color schemes than having set terminal colors. Yes, it does not always result in the specified hues, but at least most of them (I'd say 6 out of 9) are usually different, which is good enough.
- Having explicit definition instead of default linking would require an extra autocommand for `ColorScheme` event to keep highlight groups defined. This results in extra code and tests.

Closing as not planned.
