### ISSUE TITLE
Folder icons like .git do not look any different from other, yaml and yml files have exclamation mark as icon

### ISSUE THREAD

**Issue by zayihu** [echasnovski/mini.nvim#1143]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.icons

### Description

I use mini.icons as standalone package. I tried both mapping Nerd Font Symbols only font or using patched JetBrains Mono font still get same results. I use latest Nerd Font version 3.2 + Kitty terminal emulator.

### Neovim version

0.10

### Steps to reproduce

1. Install JetBrains Mono Nerd from archlinux repo
2. Setup mini.icons with lazy.nvim
3. Open project with .git, .github folder, containing yml and yaml files

### Expected behavior

Different icons for folders like .git, .github. Correct icons for yaml, yml files not exclamation mark.

### Actual behavior

![image](https://github.com/user-attachments/assets/d202be18-515d-4ad2-bab8-ec1bb5b0a2d0)
![image](https://github.com/user-attachments/assets/c3d13a5c-df96-4702-882a-d3a6009abcff)
![image](https://github.com/user-attachments/assets/1889112d-2dd1-4515-8701-671c16d507dc)

**Comment by echasnovski** [comment]
Everything works as expected:

- There is no special icons for '.git' or '.github' directories because file explorer plugin in the screenshot (probably, 'neo-tree.nvim' or 'nvim-tree.lua') does not have direct support for 'mini.icons'. Instead it probably uses mocked 'nvim-web-devicons' which does not have support for special directory icons. You can verify that everything works as expected by executing the following command `:=MiniIcons.get('directory', '.git')` or by using 'mini.files'.
- The exclamation mark for 'yml' is how its intended icon looks. You can navigate to https://www.nerdfonts.com/cheat-sheet and search for "yml".

**Comment by zayihu** [comment]
Okay, thank you!
