### ISSUE TITLE
Surround Delays Visual Mode Yank

### ISSUE THREAD

**Issue by JoeDaBu** [echasnovski/mini.nvim#1145]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

There is a noticeable delay when yanking in visual mode. This only occurs with yanking, not changing or deleting. Only occurs when mapping are set to tpope's style: `add = 'ys',`

I'm guessing it has to do with timeoutlen, but as to why the tpope mapping with nvim-surround trigger it I have no clue.

https://github.com/user-attachments/assets/88b2d98d-4b4a-4b97-bbc8-eefef0fc5362

### Neovim version

NVIM v0.10.0

### Steps to reproduce

1. install mini.surround
2. set up mappings to tpope's
3. My config:
return {
	{
		"echasnovski/mini.surround",
		enabled = true,
		version = "*",
		config = function()
			require("mini.surround").setup({
				highlight_duration = 1000,
				mappings = {
					add = "ys",
					delete = "ds",
					find = "",
					find_left = "",
					highlight = "<Leader>sh",
					replace = "cs",
					update_n_lines = "",

					-- Example with default values (`n` for `suffix_next`, `l` for
					-- `suffix_last`)
					-- and initial line `(aa) (bb) (cc)`.
					-- - Typing `sdn)` with cursor inside `(aa)` results into `(aa) bb (cc)`.
					-- - Typing `sdl)` with cursor inside `(cc)` results into `(aa) bb (cc)`.
					-- - Typing `2srn)]` with cursor inside `(aa)` results into `(aa) (bb) [cc]`.
					suffix_last = "l",
					suffix_next = "n",
				},
				n_lines = 50,
				search_method = "cover_or_next",
				respect_selection_type = true,
			})
		end,
	},
}
4. Enter visual mode and yank

### Expected behavior

There should be no delay when yanking in visual mode.

### Actual behavior

There is a delay when yanking in visual mode. A delay about 1 second.

**Comment by echasnovski** [comment]
This is expected because 'mini.surround' uses the same keys to add surrounding in both Normal and Visual modes. This requirement was one of the main reasons to use prefix-style default keys (`sa`, `sd`, etc.) instead of suffix-style (`ys`, `ds`, etc.).

There is a [documented suggested config](https://github.com/echasnovski/mini.nvim/blob/49e2699dc0d585b445eda24ed4bb45952ac20508/doc/mini-surround.txt#L533) to achieve functionality similar to 'tpope/vim-surround'. In particular, it requires [tweaking some mappings manually](https://github.com/echasnovski/mini.nvim/blob/49e2699dc0d585b445eda24ed4bb45952ac20508/doc/mini-surround.txt#L555-L560).
