### ISSUE TITLE
`permanent_delete = false` not working with `windows` when deleting files from a different drive of `stdpath('data')`

### ISSUE THREAD

**Issue by echaya** [echasnovski/mini.nvim#1152]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Hey there, hope you are well! I have just started to use `mini.files` and love the concept so far. In my opinion, it combines `Oil` and `nvim-tree` very well!

One thing I found is in Windows,  mini.files won't be able to send files from `D:\` to `stdpath('data')` which is located in `C:\` when  `permanent_delete=false` is set. This could be due to system limitation but like to check in case this can be fixed with some workaround. 

I have just tested, moving files using `!mv` from Command Mode from `D:\` to `C:\` is working fine. 

Thanks!

### Neovim version

0.10.1

### Steps to reproduce

0. Config `permanent_delete = false`
1. Assuming `stdpath('data')` in drive C, cd to `d:\` using Nvim Command mode
2. Open mini.files and delete any file and then sync 
3. File will be back (without removing / moving)

### Expected behavior

File to be moved to the desiganted dir. 

### Actual behavior

File is never moved. Buffer is updated with the file been added back

**Comment by echasnovski** [comment]
Thanks for the issue!

This sounds plausible, but I can not reproduce because I don't have proper access to Windows machine to confirm myself.

It seems to be a fundamental limitation of chosen 'mini.files' approach to not permanent delete, because moving files across different partition [seems to be not supported by `vim.loop.fs_rename()`](https://github.com/nodejs/node-v0.x-archive/issues/2703). This will also manifest itself in that regular moving files across disks/partitions doesn't work. Could you, please, confirm that also?

------

There are several solutions to this:
- Implement own move function which recursively copies to the destination and then deletes the original. I didn't really want to do this because it might not play nicely with file metadata (like when it was created, modified, etc.). But this will also make regular move work across partitions.
- Create separate "trash" directory on every partition/volume so that not persistent delete works.

I'll think about it.

**Comment by anieshav** [comment]
Lua's os.rename does seem to have this limitation. Maybe it is okay to use os.rename instead of fs_rename if the platform is Windows.

**Comment by echasnovski** [comment]
> Lua's os.rename does seem to have this limitation. Maybe it is okay to use os.rename instead of fs_rename if the platform is Windows.

Sorry, do you mean that something like `os.rename('D:\\hello\\world', 'C:\\other\\directory')` works or does not work? If it works, then it makes things a bit easier, but still would require recursive wrapper to work for directories.

**Comment by anieshav** [comment]
Sorry, I made a typo in the previous comment. os.rename seems to work only for files. So not useful after all.

**Comment by echasnovski** [comment]
I totally forgot that recursive copy is already implemented as 'mini.files' helper. So making moving across devices work was [quite a concise change](https://github.com/echasnovski/mini.nvim/commit/ce55a9fe9853c12162f16176a3c16d7b4e5c59b3#diff-3887c91f311fab10378f1a9cfa5f36a4b04f9efd4429fccacbb8632201831da5). If it mattered only for moving files, I'd probably won't add this, but this case of "move to trash from different volume" tips the scale.

This should now be resolved on latest `main`. Thanks again for pointing this out!

------

Also (as a drive-by improvement), the "delete" action description now depends on whether it is permanent or not ("DELETE" vs "MOVE TO TRASH"). This should add an extra layer of visual feedback that files won't get permanently deleted.

**Comment by echaya** [comment]
Confirm this is working now and come to say Thank you!!!

Also can I get your opinion on the following (happy to oen a new issue) if this is not a bug:

When sending "trash" to stdpath('data'), if a file with the same name already exists, the new one will not overwrite the old one. May I check if this is work as design?

**Comment by echasnovski** [comment]
> When sending "trash" to stdpath('data'), if a file with the same name already exists, the new one will not overwrite the old one. May I check if this is work as design?

It is [explicitly ensured](https://github.com/echasnovski/mini.nvim/blob/71b5694a2df4f7e3661855eb8e2814980d2e0ac9/lua/mini/files.lua#L2581-L2586) that before file/directory is moved to the "trash directory" (`stdpath('data')` + '/mini.files/trash'), there is no file with the same basename there.

Let's clarify this a bit. So the steps are:
- Have 'mini.files' set up with `require('mini.files').setup({ options = { permanent_delete = false } })`.
- Create a file 'aaa' with content "This is old file".
- Delete it (move to trash) with 'mini.files'. There now should be file named 'aaa' in "trash directory"  with content "This is old file".
- Again create a file 'aaa' with content 'This is new file'.
- Delete it (move to trash) with 'mini.files'.

After these steps I have a file named 'aaa' in "trash directory" with content "This is new file". I.e. it has replaced the previous one. Do you observe a different behavior?

**Comment by echasnovski** [comment]
> Also (as a drive-by improvement), the "delete" action description now depends on whether it is permanent or not ("DELETE" vs "MOVE TO TRASH"). This should add an extra layer of visual feedback that files won't get permanently deleted.

Just a follow up for completeness. There are now [many changes](https://github.com/echasnovski/mini.nvim/blob/main/CHANGELOG.md#minifiles) in how confirmation lines are computed. This also includes another change to how delete is shown: always with "DELETE" description but entry name followed by either "(permanently)" or "(to trash)". I reconsidered this because the new way is more aligned with how create action is shown.
