### ISSUE TITLE
mini.sessions get error when use nui instead of vim.ui.select

### ISSUE THREAD

**Issue by liuhq** [echasnovski/mini.nvim#1153]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

when using **nui** to take over vim.ui.select (code like below 👇)

https://github.com/MunifTanjim/nui.nvim/wiki/vim.ui#vimuiselect

require('mini.sessions').select('read') will get a error 👇

![image](https://github.com/user-attachments/assets/f78eba48-50e9-4c1f-b4d7-41708400292b)

I read **the mini.sessions source code** and find the error maybe happen in 👇

![image](https://github.com/user-attachments/assets/903450f6-f492-465b-8e5c-4d5c643aa1bf)

nui the error-related code maybe as follows 👇

![image](https://github.com/user-attachments/assets/9f7a640e-fbd9-4f58-a62c-aef04a226c24)
and
![image](https://github.com/user-attachments/assets/4e72a278-b885-496f-82f0-bfdaee4b7476)

But I don't know the bug which is from nui code or mini.sessions

### Neovim version

0.10

### Steps to reproduce

1. configure nui code (from https://github.com/MunifTanjim/nui.nvim/wiki/vim.ui#vimuiselect)
2. configure mini.sessions to bind a keymap to `require('mini.sessions').select('read')`

### Actual behavior

An error occurred

**Comment by echasnovski** [comment]
Thanks for the detailed question!

This doesn't look like an issue with 'mini.sessions', but rather a code snippet from 'nui.nvim'. The reason is that input items to `vim.ui.select()` are plain strings. The 'nui.nvim' code has the line of `local format_item = opts.format_item or function(item) return tostring(item.__raw_item or item) end` (meaning `format_item` is equal to `opts.format_item` if it is supplied) which later is used with the *transformed* item (after `if type(item) ~= 'table' then item = { __raw_item = item } end`) and not with the original item. This is not according to the specification, see `:h vim.ui.select()`.
