### ISSUE TITLE
Option to disable buffer word completion for mini.completion on large files.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1170]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

Hi echasnovski! I had one more doubt. Is it possible to disable buffer word completion for files larger than lets say 1MB. Is there any functionality like this or are there any hacky ways to implement this. The issue is that for a fairly large file, I am testing this with sqlite.c(8.7MB C code) amalgamation file btw, the editor hangs a lot because mini.completion has to process buffer words and show it in completion-menu afaik and see. Is something of this sort really possible with mini.completion.

**Comment by echasnovski** [comment]
The "buffer word" completion is a result of applying [fallback action](https://github.com/echasnovski/mini.nvim/blob/a8185957febe7dae31556dbd7326cfa597b812f1/doc/mini-completion.txt#L213), which indeed is synchronous and can result into lag.

What can probably be done here is to set [buffer-local config](https://github.com/echasnovski/mini.nvim/blob/a8185957febe7dae31556dbd7326cfa597b812f1/doc/mini-completion.txt#L63-L65) to disable fallback action in particular buffer. Like this:

```lua
vim.b.minicompletion_config = { fallback_action = function() end }
```

When and how this is set is left for user to decide. For example, you can set this in autocommand for `BufAdd` event after checking that file size (or line number) is too big.

One thing to know, though, is that this fallback action (similarly to built-in `<C-n>`) checks **all** opened buffers. So disabling it in only big one might not be enough, because as long as there is a big buffer open, it will be scanned in other buffers.

**Comment by 231tr0n** [comment]
> One thing to know, though, is that this fallback action (similarly to built-in `<C-n>`) checks **all** opened buffers. So disabling it in only big one might not be enough, because as long as there is a big buffer open, it will be scanned in other buffers.

Can we use `complete` to do something like ``set complete=.`` so that the it only uses current buffer for completion. Is that possible?

**Comment by echasnovski** [comment]
> @echasnovski, can we use `complete` to do something like `set complete=.` so that the it only uses current buffer for completion. Is that possible? Does this effect how mini.completion fallback mechanism works.

You can try and see. But I think it might work and is indeed a good solution if you want only current buffer completion as fallback action.
