### ISSUE TITLE
Write plugin: mini.clue

### ISSUE THREAD

**Issue by Betelgeuse1** [echasnovski/mini.nvim#118]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

whichkey, hydra

### Description

Me again ahah

Since the buffer idea isn't really pertinent, and I want to contribute real bad to this amazing project, is it possible to write the `mini.clue` plugin, which you mention in https://github.com/echasnovski/mini.nvim#planned-modules.

Totally understand if you were planning to write it yourself though :)

**Comment by echasnovski** [comment]
Hi again! Thanks so much for your enthusiasm!

I usually prefer writing them on my own because of a joy I am getting while creating new API and functionality. However, I am totally not opposed to the idea of someone else implementing whole module (it basically was the case with 'mini.jump'). 

The 'mini.clue' in particular has a certain idea behind it. I use and love 'folke/which-key' but it has a design decision which I really don't like: it completely relies on making a bunch of extra keybindings. So I have the idea to try to implement it without them, just by tracking user keys with `vim.on_key()`. Really not sure if it will work, to be honest (that design decision might be a necessity). To write this, you'll need to know/discover at least about:
- Key tracking in Neovim.
- How keymappings are created and executed.
- How to create and manage floating windows.
- Quite a bit of Lua to efficiently manage tables.

All in all, I can't really recommend this as a first time contribution (especially in case of not very deep Lua knowledge).

If you really want to contribute, I might suggest one of the following (in increasing order of complexity):

- Spreading a word about existence and usefulness of this plugin. Write blog post, make a video, etc. It is **really** appreciated.
- What is [described in 'CONTRIBUTING.md'](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md), i.e. fix typos, add support of 'mini.nvim' to some color scheme plugin of your choice, etc.
- I plan to make wiki page dedicated to examples of 'mini.ai' custom textobjects. There are already great examples of textobjects for line, buffer, diagnostic, git chunk. There might be more creative ways for you to explore.
- Some small but non-trivial utility function in 'mini.misc'. One of the ideas I plan to implement is something similar to [FooSoft/vim-argwrap](https://github.com/FooSoft/vim-argwrap) but in Lua and using this [idea of an "argument"](https://github.com/echasnovski/mini.nvim/blob/93e0f4b2e886813c65c94c5071f08cac6aacaed1/lua/mini/ai.lua#L642).
- If you want to implement whole module, there is 'mini.root'. I plan to write it after the next planned 'mini.align' and explained general design idea in more detail [here](https://github.com/echasnovski/mini.nvim/pull/88#issuecomment-1154832882). Shouldn't require a lot of Neovim-specific knowledge here). It will be a long process because there are usually a lot of small details that I want to get right.

Any from the above contributions will be welcome.

**Comment by folke** [comment]
Just a heads up that the current implementation of `vim.on_key()` is not useable. It's what I initially looked at :)

**Comment by echasnovski** [comment]
> Just a heads up that the current implementation of `vim.on_key()` is not useable. It's what I initially looked at :)

Interesting. Thanks for sharing!

Is it because of "receive the keys after mappings have been evaluated"? I didn't do any experiments yet, but at least restricting suggestions only to a subset of mappings (like `<Leader>` in Normal mode) seems doable.

**Comment by folke** [comment]
The `on_key` calback only gets called **after** evaluating the mappings. And the keys are indeed the evaluated keys.

What we would need to do it properly, is:
- an event when a mapping has been completed (including internal key binding without a mappping like `viw`)
- a callback that is triggered on every single key that was pressed by the user

Restricting it to just `<leader>` is simple and can be configured by setting ` triggers = {"<leader>"}` in **WhichKey**

**Comment by folke** [comment]
So you would just need to create a mapping that binds `<leader>` to **mini.clue**. No need to mess around with `vim.on_key`

**Comment by echasnovski** [comment]
> The `on_key` calback only gets called **after** evaluating the mappings. And the keys are indeed the evaluated keys.
> 
> What we would need to do it properly, is:
> 
> * an event when a mapping has been completed (including internal key binding without a mappping like `viw`)
> 
> * a callback that is triggered on every single key that was pressed by the user

Yeah, quick test confirms that it is not straightforwardly usable. Shame :(

> So you would just need to create a mapping that binds `<leader>` to **mini.clue**. No need to mess around with `vim.on_key`

And also for any non-terminal `<Leader>` mappings. Having to do this is the reason I wanted to try and use `on_key()` in the first place.
The only alternative I see right now is to indeed make custom mapping only for `<Leader>` and implement own `getchar()` based logic for retrieving next keys (something along the lines of 'mini.jump2d').

Anyway, 'mini.clue' is not yet even in top 3 of my priority list, so it will be a while. Besides some rare mappings-related issues, yours 'which-key.nvim' does a great job.

**Comment by echasnovski** [comment]
I'll close this as 'mini.clue' is still planned but probably is indeed too complicated for a first time contribution. If anyone thinks they **really want** to help implementing this, feel free to comment here.
