### ISSUE TITLE
Different color for @tag, @tag.attribute and @tag.delimiter for HTML in mini.base16

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1188]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.base16

### Description

Hi echasnovski! Can different colors be set for @tag, @tag.attribute and @tag.delimiter for HTML in mini.base16.
Currently HTML looks something like below with no differentiation between tag, attribute and delimiter.
![image](https://github.com/user-attachments/assets/0a4193ec-898d-43ee-a2b1-dc4e03439411)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The 'mini.base16' has intentionally very minimal tree-sitter highlight groups definition in order to rely on defaults as much as possible. The 'mini.hues' is a bit different and already has `@tag.delimiter` different, so already taken care of.

Any further tweaking can (and should) be done manually via `:highlight` command or `vim.api.nvim_set_hl(0, ...)` Lua function call.

Closing as not planned.
