### ISSUE TITLE
Mini.pick slow with moving across buf_lines in preview mode on files which are horizontally big.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1190]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

This bug is a reproduction of the issue which I mentioned in discussion. Below is the source code to reproduce it. I made it as simple as possible.
[try.zip](https://github.com/user-attachments/files/16829230/try.zip)

To give some context, I deal with json files as large as 5MB+ at work and most of the lines are very big in those jsons. I was able to see noticable delay with it when navigating through those json files.

### Neovim version

nightly latest

### Steps to reproduce

1. Unzip the zip file attached in description and navigate to the unzipped directory where trial.lua and 9.OeaLULSY.js exist.
2. Run the command ``nvim -u trial.lua 9.OeaLULSY.js``.
3. Once lazy.nvim downloads the plugins necessary and finishes everything run buf_lines picker using ``Pick buf_lines``
4. Press `<tab>` to open preview and press the `<up>` key continuously for a second and leave it after some time. You can see that there is a lag between input keys and the movement of the UI and the UI still moves even after you stop pressing the `<up>` key.

### Expected behavior

No lag

### Actual behavior

Lag

**Comment by 231tr0n** [comment]
To be frank, this is a very rare scenario and I dont think most people will deal with such files. Suck to be me since I have to deal with such files. Anyways all I can say is fzf works like a charm without any input lag in such scenario since it runs in a seperate thread and is written in go which is compiled and is much faster than lua. So you can actually ignore this bug if you think it is not relevant afaik.

**Comment by echasnovski** [comment]
Thanks for following through!

I'll take a look a bit later.

**Comment by echasnovski** [comment]
> To be frank, this is a very rare scenario and I dont think most people will deal with such files.

I am afraid this is indeed the case. But not only because it is a big file, but because it is *big enough* to cause delays but *not big enough* to enable preview's large file optimization.

Buffer previews in 'mini.pick' are not done via simply showing the target buffer in a window (here is [an explanation why](https://github.com/echasnovski/mini.nvim/blob/d231729b13da28fd1625c3d85f2315886ddeb05d/lua/mini/pick.lua#L3093)). So they read necessary lines from the buffer and reapply highlighting *on every buffer lines preview*. Usually enabling highlighting is the most performance heavy part of this (and it is indeed true here also). To counter this, highlighting in preview is enabled [based on certain conditions](https://github.com/echasnovski/mini.nvim/blob/d231729b13da28fd1625c3d85f2315886ddeb05d/lua/mini/pick.lua#L3138-L3142), which pass in this case. In particular, the file is around 590 KiB (which is not enough for 1 MiB threshold) and there are only a handful of very long lines compared to the number of short ones (thus bypassing the 1000 bytes per line threshold). This particularly is indeed more visible when trying to preview lines closer to the end (because preview reads all lines from the start to have a more coherent highlighting).

I don't really want to make preview highlighting threshold configurable. Mostly because it will also have to be done in 'mini.files' (as they share the "preview buffer" code) *and* this problem can mostly be worked around by navigating through the items in main (not preview) view.

I think I indeed will close this as a known limitation.

**Comment by 231tr0n** [comment]
Cool, really thank you for helping me out by debugging this rare scenario. Your modules are the best!!!

**Comment by 231tr0n** [comment]
Also, If you dont mind revealing it, what will the next mini.________ be? I was just too curious to know.

**Comment by echasnovski** [comment]
Probably, 'mini.snippets'.
