### ISSUE TITLE
`mini.map`: allow setting `height` property of the map window

### ISSUE THREAD

**Issue by TomJo2000** [echasnovski/mini.nvim#1199]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.map

### Description

It would be nice to be able to set the window height for the MiniMap, as currently the window is the full height of the Neovim window.
This causes the `winblend` to get applied to anything "behind" the map window, even when there is no part of the map on that line.
![image](https://github.com/user-attachments/assets/e214bdc0-8811-4356-a0ac-f5efc561561c)
I have set my cursor line to white to demonstrate the effect.

It would be nice to be able to, for example set the height of the map window to the "text height" of its contents.
e.g.
```lua
window.height = vim.api.nvim_win_text_height(MiniMap.current.win_data[1], {}).all
```
Which currently has no effect when put in the config for mini.map, as the height is forced.
```lua
-- In function H.normalize_window_options
height = vim.o.lines - vim.o.cmdheight - (has_tabline and 1 or 0) - (has_statusline and 1 or 0),
```
[See source@mini.map:1357-1382](https://github.com/echasnovski/mini.map/blob/8baf542570cbff05b568958d20e3f842bd941545/lua/mini/map.lua#L1357-L1382)
As such, setting `window.height` currently seem to have no effect.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Setting `window.height` indeed has no effect because it is [not a support configuration setting](https://github.com/echasnovski/mini.nvim/blob/eb0f557a5797cfe9c720ed84a71582c22bccb4f8/doc/mini-map.txt#L214-L230). Map window indeed is forced to full available height mostly to simplify code and available configuration. [This is documented](https://github.com/echasnovski/mini.nvim/blob/eb0f557a5797cfe9c720ed84a71582c22bccb4f8/doc/mini-map.txt#L10). Having more flexible window configuration is also [documented as something that won't be done](https://github.com/echasnovski/mini.nvim/blob/eb0f557a5797cfe9c720ed84a71582c22bccb4f8/doc/mini-map.txt#L55-L57).

Closing as not planned.

**Comment by TomJo2000** [comment]
Thanks for the quick response.
I completely understand not wanting to take on the additional complexity.

I guess I'll try monkey-patching it to see if I can make it work for my specific usecase.
