### ISSUE TITLE
Update when deleting a session from mini.sessions on the mini.starter screen.

### ISSUE THREAD

**Issue by jiggol** [echasnovski/mini.nvim#1213]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter, mini.sessions

### Description

Hello,

I’ve been using mini.starter and mini.sessions and they work great. However, I’ve encountered one issue. When I delete a session from the starter screen, the starter screen does not update. Even after calling refresh on the starter, it still doesn’t update.

Please excuse any awkward expressions as I used a translation tool to write this.
Thank you for creating such a great program.

### Neovim version

0.10.1

### Steps to reproduce

1. run nvim
2. Call require('mini.sessions).select('delete') on the starter screen to delete the session.

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce. Calling `MiniStarter.refresh()` indeed is needed for items to be updated. Here is the demo with the default `require('mini.starter').setup()`:

https://github.com/user-attachments/assets/587a5426-f8c6-4579-9caf-891f40858a71

The behavior you describe *can* happen if items are computed during startup. However, all examples (even this [one](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/doc/mini-starter.txt#L96)) are wrapped inside a function which is recomputed after `MiniStarter.refresh()`.

------

Could you, please, share how you set up 'mini.starter' and 'mini.sessions'?

**Comment by echasnovski** [comment]
> As shown on your screen, I also have no issues during testing. I set a specific keymap to trigger session deletion and refresh, but it is not working.

I see. I still can not reproduce this, but probably for a known reason.

The `MiniSessions.select()` [uses `vim.ui.select()`](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/doc/mini-sessions.txt#L205-L207) function which is by design overridable and designed to allow asynchronous (i.e. code doesn't "wait" for function to finish but instead executes callback after selection is done) implementation. Probably you have it overridden by Telescope or some other asynchronous implementation, which means that `session.select('delete')` returns immediately and the next `starter.refresh()` is executed *before session is actually deleted*.

Using synchronous `vim.ui.select` implementation (i.e. code "waits" for the function to finish) like default or [`MiniPick.ui_select()`](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/doc/mini-pick.txt#L1037) should make "Delete Sessions" function refresh Starter buffer as expected.

If you want to keep using your current `vim.ui.select()` implementation, there are several options:
- Accept that 'mini.starter' "Sessions" section will not update immediately.
- Call `MiniStarter.refresh()` manually *after* deleting session.
- Use manual implementation instead of `MiniSessions.select('delete')`. Something like this:
    ```lua
    -- Use this function as right hand side of the `<Leader>qd` mapping
    local del = function()
      local detected_names = vim.tbl_map(function(x) return x.name end, vim.tbl_values(MiniSessions.detected))
      table.sort(detected_names)

      local callback = function(item)
        if item == nil then return end
        MiniSessions.delete(item)
        MiniStarter.refresh()
      end
      vim.ui.select(detected_names, { prompt = 'Select session to delete' }, callback)
    end
    ```

**Comment by jiggol** [comment]
Thank you for your kind response, especially when you must be busy.
