### ISSUE TITLE
Expose chroma config option for mini.hues

### ISSUE THREAD

**Issue by wpaulino** [echasnovski/mini.nvim#1215]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.hues

### Description

I find the current saturation values of medium and high are often outside of the chroma range I would like. Are you open to exposing a config option for it that's mutually exclusive with the saturation one? An alternative could be to introduce a fourth value in between medium and high, but of course that's not as flexible.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The explicit constraints in configuration was an intentional choice, so allowing variable chroma level is out of question. If you want to precisely control the palette, there are [`make_palette()`](https://github.com/echasnovski/mini.nvim/blob/5c72e4d74e05f50325641e5fa921fca97a24cb13/doc/mini-hues.txt#L226) (to make/get the current palette), [`MiniColors.convert()`](https://github.com/echasnovski/mini.nvim/blob/5c72e4d74e05f50325641e5fa921fca97a24cb13/doc/mini-colors.txt#L785) (to convert between Hex and Oklch color spaces), and [`apply_palette()`](https://github.com/echasnovski/mini.nvim/blob/5c72e4d74e05f50325641e5fa921fca97a24cb13/doc/mini-hues.txt#L307) (to apply the palette).

I was going to close this, but decided to take a look at which chroma levels are low-medium-high. Those are 4-8-16. So maybe fitting a 12 there is reasonable. Unfortunately, I don't have a good name for something between "medium" and "high", so will have to think if it is worth making a breaking change and make "high" be chroma 12 and something new (like "max") be 16. If there are name suggestions for something between "medium" and "high", that would be helpful.

**Comment by pkazmier** [comment]
> **Edit**: maybe "moderate", "rich", and "vivid" are good values. For once LLMs are useful :)

LOL. I just doing the same. I struggled with "vivid" as I would think of that as stronger than "high" given the current scale. The other one option my LLM gave back that I thought was decent was "boosted".

**Comment by echasnovski** [comment]
Yeah, there are other more abstract ones: "rich", "deep", "lush", "juicy", "strong".

**Comment by echasnovski** [comment]
There are now `'lowmedium'` and `'mediumhigh'` saturation levels. They are essentially exactly in the middle of 'low'-'medium' and 'medium'-'high' ranges. The eventual grades are not uniform (chromas 4-6-8-12-16 instead of a uniform 3-6-9-12-15), but making it uniform has small gains while still technically being breaking change (which are bad).

Thanks again for the (alternative) suggestion! This will benefit some of the future planned work.
