### ISSUE TITLE
can't open file with parentheses in path

### ISSUE THREAD

**Issue by sadguitarius** [echasnovski/mini.nvim#1237]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

I'm working through a Next.js tutorial and I found that when trying to access a file with parentheses in the path (a pattern used in Next.js) in mini.files, a blank buffer is shown. As far as I can tell, this may be the same as [this](https://github.com/ms-jpq/chadtree/issues/362) and [this](https://github.com/neovim/neovim/issues/24542). It's unclear to me if the issue was ever resolved in Neovim itself, but would this be something that could be dealt with on a case-by-case basis in mini.files?

### Neovim version

0.10.1 (Windows)

### Steps to reproduce

1. create a file nested in a directory with the path name enclosed in parentheses
2. try to open the file in mini.files

### Expected behavior

A buffer should appear showing the contents of the file

### Actual behavior

An empty buffer is shown

**Comment by echasnovski** [comment]
Thanks for the issue!

Have you tried playing with `'isfname'` as suggested [here](https://github.com/neovim/neovim/issues/24542#issuecomment-1664011069)?

The 'mini.files' modules already tries to handle special characters in file names [by using `fnameescape()`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/lua/mini/files.lua#L1815). Judging by its help:

```
For most systems the characters escaped are
" \t\n*?[{`$\\%#'\"|!<".  For systems where a backslash
appears in a filename, it depends on the value of 'isfname'.
```

And here is an excerpt from `'isfname'` help:

```
Note that on systems using a backslash as path separator, Vim tries to
do its best to make it work as you would expect.  That is a bit
tricky, since Vi originally used the backslash to escape special
characters.  Vim will not remove a backslash in front of a normal file
name character on these systems, but it will on Unix and alikes.  The
'&' and '^' are not included by default, because these are special for
cmd.exe.
```

As I understand it, the issue is that paths like "aaa\(bbb)\ccc.jsx" are treated as "aaa(bbb)cc.jsx" due to using backslash as path separator. 

Could you try adding `(` and `)` to 'isfname' and see if this fixes things for you? It can be done via `:set isfname+=(,)` interactively or `vim.opt.isfname:append('(')` + `vim.opt.isfname:append(')')` in Lua.

**Comment by sadguitarius** [comment]
Ha, that worked! I was having trouble figuring out how that solution would be implemented. Thanks!

**Comment by echasnovski** [comment]
Thanks for confirming! I don't have reliable access to Windows machine, so having this information is very useful.
