### ISSUE TITLE
haskell and purescript type splitjoin

### ISSUE THREAD

**Issue by srghma** [echasnovski/mini.nvim#1261]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

splitjoin

### Description

having 

```
{parse, parser, moduleName, functionName, outputType, filePath}
```

I click `gS`

changes to

```
  {
    parse,
    parser,
    moduleName,
    functionName,
    outputType,
    filePath
  }
```

this is ok for js, but for haskell and purescript better

```
  { parse
  , parser
  , moduleName
  , functionName
  , outputType
  , filePath
  }
```

make splitjoin depent on buffer filetype

**Comment by echasnovski** [comment]
This type of fine-tuning is left to users via [hooks](https://github.com/echasnovski/mini.nvim/blob/61e5d46fc0cf71306c51275383767d996f559a60/doc/mini-splitjoin.txt#L214). Those can also be set on per buffer basis by using [buffer-local config](https://github.com/echasnovski/mini.nvim/blob/61e5d46fc0cf71306c51275383767d996f559a60/doc/mini-splitjoin.txt#L58-L60).

First steps of this particular use case are as follows:
- Create a '~/.config/nvim/after/ftplugin/haskell.lua' file.
- Put there the following code:
    ```lua
    local move_splits_to_left = function(positions)
      local res = {}
      -- Start from index 2 to have first argument on the same line
      -- End wth second to last to move right bracket on separate line
      for i = 2, #positions - 1 do
        table.insert(res, { line = positions[i].line, col = positions[i].col - 1 })
      end
      table.insert(res, positions[#positions])
      return res
    end
    vim.b.minisplitjoin_config = { split = { hooks_pre = { move_splits_to_left } } }
    ```

This *almost* implements the described output, but not 100%. 'mini.splitjoin' is designed to automatically indent all "inner" lines, which seems to be not the goal here. This can be undone in split post-hook, but I'd leave it to users to tweak (admittedly, this is not trivial to get 100% right, because 'mini.splitjoin' can work inside comments thanks to using [its own way of computing indent](https://github.com/echasnovski/mini.nvim/blob/61e5d46fc0cf71306c51275383767d996f559a60/doc/mini-splitjoin.txt#L512)).

------

Closing as not planned to be built-in and can be configured on user side.

**Comment by srghma** [comment]
yes, almost as needed

```
  { parse
    , parser
    , moduleName
    , functionName
    , outputType
    , filePath
  }
```

tnx!
