### ISSUE TITLE
mini.completion: Completion problems for variable names starting with `$`

### ISSUE THREAD

**Issue by leaysgur** [echasnovski/mini.nvim#1268]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

I found a few issues related to variables start with `$` like `$a`.

- 1: It does not open completion window when start typing `$`
- 2a: Items are listed with doubled `$`
- 2b: `$` is duplicated when accepting item
- 2c: Item disappears when typing next character of `$`

LSP used here are `ts_ls` for 1 and `svelte` for 2.

### Neovim version

0.11.0-dev-888+g4075e613b

### Steps to reproduce

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"neovim/nvim-lspconfig",
		dependencies = {
			{ "williamboman/mason.nvim", config = true },
			"williamboman/mason-lspconfig.nvim",
		},
		config = function()
			require("mason-lspconfig").setup_handlers({
				function(server_name)
					require("lspconfig")[server_name].setup({})
				end,
			})
		end,
	},
	{
		"echasnovski/mini.completion",
		config = true,
	},
})
```

### Expected behavior

See below.

### Actual behavior

See these videos.

> It does not open completion window when start typing `$`

https://github.com/user-attachments/assets/bd0fb776-a766-4454-8fec-6cf9dc9e5f32

`$` is valid character as variable name, it should trigger completion.

---

> Items are listed with doubled `$`

https://github.com/user-attachments/assets/5f2f8cd9-0bfa-4389-b078-4310b5622fe0

Items like `$effect`, `$state` are valid, but `$$effect`, `$$state` are not.

---

> `$` is duplicated when accepting item from LSP source

https://github.com/user-attachments/assets/be4a4687-4063-4211-8fcd-9d05c6961883

It should not add extra `$`.

---

> Item disappears when typing next character of `$`

https://github.com/user-attachments/assets/ac298dff-5035-4b64-ad00-f3cd3e3b207e

It should work like normal characters.

**Comment by echasnovski** [comment]
Thanks for the issue!

I could not get LSP servers to run with the reproduction steps, so reserved to reproducing with my setup.

------

> It does not open completion window when start typing `$`

I can not reproduce:

https://github.com/user-attachments/assets/5ad3c52a-feb6-4311-811d-544bab4e9f9f

I have `typescript-language-server` version 4.3.3 and (almost) latest `master` of 'nvim-lspconfig`. The LSP is initiated with the following setup:

```lua
local on_attach_custom = function(client, buf_id)
  vim.bo[buf_id].omnifunc = 'v:lua.MiniCompletion.completefunc_lsp'
end
require('lspconfig').ts_ls.setup({ on_attach = on_attach_custom })
```

------

All of 2a, 2b, and 2c are probably due to `$` not being recognized as a part of completion word. 'mini.completion' [tries to get based on LSP server response](https://github.com/echasnovski/mini.nvim/blob/a535342b6105a684f16114f598d44318e6a1d20f/lua/mini/completion.lua#L1373-L1384), but `svelte-language-server` doesn't provide `textEdit.range` in its responses (I checked). In this case 'mini.completion' falls back to computing keyword before cursor, which uses 'iskeyword' option.

You can solve this particular issue by putting `vim.bo.iskeyword = vim.bo.iskeyword .. ',$'` in file '~/.config/nvim/after/ftplugin/svelte.lua' (filetype plugin for 'svelte' filetype).

------

I'll wait a bit for possible new details about `ts_ls` issue, but currently I don't see issues with 'mini.completion'.

**Comment by leaysgur** [comment]
Thank you for your response.

First, regarding 1.
I noticed from watching your video that the behavior seems to change depending on whether the file is named tmp`.js` or tmp`.ts` in my environment.

In other words, it appears that this behavior is not related to `mini.completion`.

I apologize for the confusion! 🙇🏻 

Regarding 2, I was able to confirm that adding `,$` serves as a workaround.

And I will also investigate if there's a way to address this on the `svelte-language-server` side.

Once again, thank you so much for your help~! Your consistent and thorough support is greatly appreciated as always. 😃
