### ISSUE TITLE
[mini.files] Renaming is case sensitive

### ISSUE THREAD

**Issue by iamxiaojianzheng** [echasnovski/mini.nvim#1269]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

1. Cannot rename `abc` to `ABC`
2. If a file with the same name exists in the directory, cannot cut and overwrite it.

### Neovim version

0.10.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Expected behavior

1. Rename case sensitive
2. Support shear override

### Actual behavior

 1. Error `(mini.files) Can not move or rename xxx. Target path already exists.` occurred while renaming abc to ABC
 2. Cut `test.txt` from directory A to directory B. If Directory B contains test.txt. Error `Target path already exists.`

**Comment by echasnovski** [comment]
1. This is most certainly due to case insensitive operating system: Windows or MacOS. Those treat file paths which differ only in letter cases as the same path.
2. Not performing action that might damage existing files is by design. To override already existing file with the same name, delete present file first and then move/copy the new file.
