### ISSUE TITLE
Add customizable highlights for each diagnostic level in mini.statusline

### ISSUE THREAD

**Issue by 0xJWLabs** [echasnovski/mini.nvim#1278]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

t would be great to have the ability to customize the highlights for each diagnostic level (e.g., Error, Warn, Info, Hint) in the mini.statusline plugin. This enhancement would allow users to visually distinguish between different types of diagnostics more easily in the statusline.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is already possible via utilizing [`signs` option of `section_diagnostics()`](https://github.com/echasnovski/mini.nvim/blob/df1559e2ed7ece458e0a97a8bb9556d465d1c775/doc/mini-statusline.txt#L271-L274). Because the output of any `config.content` method is treated as a regular string for statusline (see `:h statusline`), signs can also use special characters to change their highlighting (`%#HighlightGroupName#` in particular).

Here is an example of how to achieve this:

```lua
local diag_signs = {
  ERROR = '%#DiagnosticError#E',
  WARN  = '%#DiagnosticWarn#W',
  INFO  = '%#DiagnosticInfo#I',
  HINT  = '%#DiagnosticHint#H',
}

local active_content = function()
  local mode, mode_hl = MiniStatusline.section_mode({ trunc_width = 120 })
  local git           = MiniStatusline.section_git({ trunc_width = 40 })
  local diff          = MiniStatusline.section_diff({ trunc_width = 75 })
  local lsp           = MiniStatusline.section_lsp({ trunc_width = 75 })
  local filename      = MiniStatusline.section_filename({ trunc_width = 140 })
  local fileinfo      = MiniStatusline.section_fileinfo({ trunc_width = 120 })
  local location      = MiniStatusline.section_location({ trunc_width = 75 })
  local search        = MiniStatusline.section_searchcount({ trunc_width = 75 })

  -- Compute colored diagnostics and reset color for later LSP section
  local diagnostics = MiniStatusline.section_diagnostics({ trunc_width = 75, signs = diag_signs })
  diagnostics = diagnostics .. '%#MiniStatuslineDevinfo#'

  return MiniStatusline.combine_groups({
    { hl = mode_hl,                  strings = { mode } },
    { hl = 'MiniStatuslineDevinfo',  strings = { git, diff, diagnostics, lsp } },
    '%<', -- Mark general truncate point
    { hl = 'MiniStatuslineFilename', strings = { filename } },
    '%=', -- End left alignment
    { hl = 'MiniStatuslineFileinfo', strings = { fileinfo } },
    { hl = mode_hl,                  strings = { search, location } },
  })
end

require('mini.statusline').setup({ content = { active = active_content } })
```

If run this setup, you'd probably notice that highlighted diagnostics have "good colored" foreground (text color) but not matching background color. This is an issue with how statusline computes its colors (it doesn't properly "combine" colors)  and is one of the main reasons why 'mini.statusline' and 'mini.tabline' don't come with built-in color support. There are attempts to make it work in Neovim, but (as far as my initial tests show) they are not ideal yet.

The solution to this highlighting problem is to define your own highlight groups (something like `Diagnost{Error,Warn,Info,Hint}Statusline`) which will have both foreground and background.

------

Closing as already possible (albeit with extra hurdles).

**Comment by 0xJWLabs** [comment]
@echasnovski We can also set our own hl right? like lets say MiniStatuslineDiagnosticsError etc right?
