### ISSUE TITLE
[mini.pick] Allow for matching filepath in grep_live

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#1291]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Related discussion: https://github.com/echasnovski/mini.nvim/discussions/33#discussioncomment-10941958

It would be useful to allow filtering of files in `grep_live`. As per the discussion we have found a solution, but I still think this could be eventually builtin functionality. It could be done in several ways:
- By introducing some functionality for filtering inside the picker, behaving similar to the `<C-Space>` keymap in `Pick files`
- By allowing the modification of the command of pickers, either totally or by specifying specific arguments that the user can modify

**Comment by ndavd** [comment]
That's a great idea. Doing it at git level would make it work with all supported tools. 🙌🏻

**Comment by echasnovski** [comment]
> Doing it at git level would make it work with all supported tools.

That's not *quite* what is meant here. Pattern search itself can be done either via `rg` or `git` CLI tools (with [these different commands](https://github.com/echasnovski/mini.nvim/blob/9618cf56e76cc0caab54ad60116a8d72f99d7b3b/lua/mini/pick.lua#L3259-L3269)). And ideally support for "pre-filtering" should be present in both.

Luckily I have a working prototype which seems to work for both CLI tools and both `grep` / `grep_live`. It will need a period of manual testing and polishing, though.

**Comment by echasnovski** [comment]
I have a working prototype in [`pick-glob`](https://github.com/echasnovski/mini.nvim/tree/pick-glob) branch. Would you mind giving it a spin and give a feedback?

**Comment by ndavd** [comment]
Niice, of course, I'll get back to you later today.

**Comment by echasnovski** [comment]
> UPDATE: Upon further testing I've noticed that [using a temporary `rg` config](https://github.com/ndavd/dotfiles/blob/a928f388e5df598f14de77dd618edf6c32802f53/.config/nvim/lua/plugins/mini.lua#L163-L169) no longer works if I use that branch (it's something I still use regardless to, for example, follow gitignore).

What exactly do you mean by "no longer works"? Does it not load the config at all (because I mostly positive it should load)? Or does it override the "glob" pattern (because I don't think it should)? Does it work with default "glob" (i.e. workflow same as on the `main` branch)?

**Comment by ndavd** [comment]
What I noticed is that it no longer respects my gitignore, showing results from gitignored folders

**Comment by echasnovski** [comment]
> * It no longer respects my `.gitignore` (e.g. shows results inside `node_modules` directory)
> 
> * My temporary rg config has a glob which just ignores anything inside the `.git` directory, it's not respecting that as well

Yeah, so this is the effect of using extra `--glob`, not that it doesn't respect config file. Based on the `man rg`, together with that config search was essentially the `rg --glob=!.git/ --glob=*` (in this specific order of `--glob`, because arguments from config file are put first in the command). This has the effect that `--glob=*` "overrides" the previous glob.

The fact that `.gitignore` is not respected when there is at least one `--glob` argument seems to be by design (BurntSushi/ripgrep#2252). Not sure why this doesn't conflict with `--glob=!git/` in the config file, but that is to the best.

------

I've force pushed the updated version to [`pick-glob`](https://github.com/echasnovski/mini.nvim/tree/pick-glob) branch. Now it:
- Allows array `globs` instead of a single string `glob`. Pressing `<C-o>` will *add* glob to the array allowing things like `{ '*.ts', '!node_modules/', '!.git/' }` to filter files.
- Explicitly does nothing if there is no `glob` supplied. This should at least preserve the gitignore behavior when no manual glob patterns are supplied.

Would you mind giving it a second spin, please?

**Comment by ndavd** [comment]
Interestingly, now I no longer get that issue of showing me gitignored files, and now `!.git` is respected — So everything is working correctly on my end!

> The fact that .gitignore is not respected when there is at least one --glob argument seems to be by design (https://github.com/BurntSushi/ripgrep/issues/2252). Not sure why this doesn't conflict with --glob=!git/ in the config file, but that is to the best.

I'm curious why `.gitignore` is still respected in my case, in any case that's what I intend so that's fine by me 🤷🏻‍♂️

**Comment by echasnovski** [comment]
> Interestingly, now I no longer get that issue of showing me gitignored files, and now `!.git` is respected — So everything is working correctly on my end!

I presume this is the case by default, i.e. before setting any globs? Because after setting any globs (either via option or after `<C-o>`), it follows the same logic as before: all `.gitignore` are overridden by `--glob`.

**Comment by ndavd** [comment]
Yes, turned out my globs just weren't overlapping with my `.gitignore`.

The new features are working as intended from my side, thanks! Using the `pick-glob` branch now — Please ping this issue once it's merged into `main` 🙌🏻.

**Comment by ndavd** [comment]
Thanks!
