### ISSUE TITLE
Preserve HTML attributes when replacing tag via `srtt`

### ISSUE THREAD

**Issue by jesseleite** [echasnovski/mini.nvim#1293]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Firstly, let me say thank you for all your work on these awesome mini.nvim plugins! ❤️❤️❤️

I was hoping you [might reconsider](https://github.com/echasnovski/mini.nvim/issues/397#issuecomment-1615999605) preserving html attributes when replacing tag via `srtt`. Here are a few reasons why I think it's in scope of your plugin to do so 🙏

1. Often when changing a tag in HTML, it's because the user renamed a JS component, or because they want to switch to a different header level (ie. `<h2>` to `<h3>`), etc. In both scenarios, they would want to keep your HTML classes or JS component props, despite the tag rename.

2. Users coming over from [tpope/vim-surround](https://github.com/tpope/vim-surround) are used to this functionality, as vim-surround preserves HTML attributes when replacing tags. This would make the move to mini.surround more enticing for vim-surround users.

3. You mention dealing with HTML attributes is out of scope, but if the user adds surrounding tags via `sat` and types `h3 class="font-bold"`, I notice you already nicely handle adding that attribute to the opening tag, but not to the closing tag (ie. `<h3 class="font-bold">...</h3>`). Given that you're already handling attributes so nicely with `sa`, why not also with `sr`?

4. I can't think of any downsides to preserving HTML attributes with `sr`. I personally LOVE mini.surround, but really miss attribute preservation in tpope's plugin, and find myself without a solution for this. If some people rely on the current functionality, maybe it could be a configuration option that we could opt-in to or opt-out of?

You've created a wonderful plugin, and I want to thank you again for your work on it! Curious what you think of the above? 🙏

**Comment by echasnovski** [comment]
Thanks for the detailed reasons.

All motivation for the current behavior is outlined in the linked comment.

> 3\. You mention dealing with HTML attributes is out of scope ...

Not HTML attributes, but specifically preserving attributes during "replace" action. The reason for that is described in the linked comment: during `srtt` the first `t` matches the whole left and right `<...>` (as it is its "input" specification) and the second `t` replaces them with content supplied by the user (as it is its "output" specification).

Replacing "input" specification in `t` surrounding to mean only "tag name inside <...>" would lead to `sdt` deleting only that part and not the whole `<...>` left and right parts. Which is probably not what most users expect.

> 4\. I can't think of any downsides to preserving HTML attributes with `sr`.

The main downside is that it doesn't fit the design of surrounding specification in 'mini.surround' and how "replace" action works in general.

------

One way of doing so (which should have come to mind sooner) is to create a separate surrounding specifically for "tag name". With something like this:

```lua
require('mini.surround').setup({
  custom_surroundings = {
    T = {
      input = { '<(%w-)%f[^<%w][^<>]->.-</%1>', '^<()%w+().*</()%w+()>$' },
      output = function()
        local tag_name = MiniSurround.user_input('Tag name')
        if tag_name == nil then return nil end
        return { left = tag_name, right = tag_name }
      end,
    },
  },
})
```

Now replacing a tag name can be done with `srTT`, replacing the whole tag pair with another tag pair with `srtt`, and deleting tag pair is also the same with `sdt`.

Closing as not planned, duplicate, and which have a workaround.

**Comment by jesseleite** [comment]
@echasnovski Ah, that's a great solution with the custom surroundings! Thank you very much 😍

**Comment by vdegenne** [comment]
Thanks awesome solution @echasnovski 

Though I'd like to disagree. `T` is more tedious to write than `t` so `T` should be seen as something less common right?
In my +20 years of web development, replacing a tag name vs replacing tag name + all attributes is roughly a 99 against a 1.

IMHO the default `gstt` should only replace the tag name and preserve all attributes because again, that's the most common thing and what people would expect.

Now people would use `sdT` to delete the whole thing but again `T` is less common, so is the deletion feature. I want to bet that most user use mini-surround in html to rename, there are so many more ways to delete a tag like just line deletion, visual selection + `c` or using tree sitter, etc... 

`t` and `T` should be both implemented with `t` defaulting to only tag name.
it's a bummer that not only we need to implement `T` ourselves but also so it works as expected...

**Comment by echasnovski** [comment]
I am afraid, the current behavior with not change. Every built-in surrounding has to be consistent across all actions:
- "Add" should the whole tag structure (i.e. `<tag_name>` + `</tag_name>`) on left and right. Not only a single tag name.
- "Delete" should be able to delete the whole tag structure. Deleting only tag name will make the result not valid.
- "Replace" shares the same logic as "delete" when it comes to determining which regions should be replaced. So it is fixed on the full tag structure.

The suggested solution of separate surrounding for a tag name is a reasonable compromise here, I believe.

**Comment by vdegenne** [comment]
@echasnovski Can't at least `T` be part of the package?

Also I have an issue with the regexp you provided. It won't work if there are arrow functions in the template, e.g.

```html
<md-text-button
	@click=${() => isUserLoggedIn().then(toast)}
	style="color:blue"
>
	is Logged In?
</md-text-button>
```

I tried to find a way but I'm not a regexp expert... Also asked AI but even it can't find a proper solution! If you ever find a solution, *please* let me know. Thanks

**Comment by vdegenne** [comment]
Correction: The issue is not about the arrow function but hyphens in the name.

even this

```html
<my-element>test</my-element>
```
will fail to rename

**Comment by echasnovski** [comment]
> [@echasnovski](https://github.com/echasnovski) Can't at least `T` be part of the package?

I don't think it is a good idea to have this built-in for 'mini.surround' itself. The `t` surrounding itself is only present because `it` and `at` are built-in textobjects and 'mini.surround' + 'mini.ai' are kept as aligned as reasonably possible. Otherwise it would not have been built-in because it is not very versatile for any non-add action.

Maybe if there are some language packs in the future, then including this dedicated surrounding for languages that use a lot of HTML tags might make sense.

> Correction: The issue is not about the arrow function but hyphens in the name.
> 
> even this
> 
> <my-element>test</my-element>
> 
> will fail to rename

Yes, because the example only assumes alphanumeric characters as part of a tag name (same as default `t` surrounding and textobject from 'mini.ai'). To account for that, you can try to use `[%w_-]` instead of every `%w` in the `input` pattern.

And as always with anything tag surrounding/textobject related, my suggestion is still to try and use tree-sitter here. It might be a bit tougher for this "tag name" surrounding, but should be possible.

**Comment by vdegenne** [comment]
Thanks

yes 

```lua
          input = {
            -- original patterns
            "<([%w-]+)[^<>]->.-</%1>",
            "^<()[%w-]+().*</()[%w-]+()>$",
          },
```
works~
