### ISSUE TITLE
mini.starter displays paths in an invalid way

### ISSUE THREAD

**Issue by B4mbus** [echasnovski/mini.nvim#133]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.session

### Description

Mini.session didn't work correctly on windows at first, at startup it just kept saying `(mini.sessions) "C:\\\\Users\\\\B4mbus\\\\AppData\\\\Local\\\\nvim-data\\\\session" is not a directory path.` So I changed it manually to `vim.fn.stdpath('data') .. '\\sessions\\` and it doesn't display that error anymore, but the paths that are displayed use `%` or `++` as a separator instead of `\`.

### Neovim version

0.8.0-dev-922-g42e9fe7d9

### Steps to reproduce

1. `nvim -nu minimal.lua`
Contents of `minimal.lua`:
```lua
require('mini.sessions').setup({
  directory = require('plenary.path')
    :new(vim.fn.stdpath('data'))
    :joinpath('sessions\\')
    .filename
})

```
3. Same thing

### Expected behavior

Paths displayed properly, that is either `F:\prv.vim` or `f/prv.vim`.

### Actual behavior

Paths are displayed incorrectly, with `++` and `%`.
![image](https://user-images.githubusercontent.com/75364377/192162911-ce51a96d-c728-4a5c-80d9-e3941c123327.png)

(here with minimal config)
![image](https://user-images.githubusercontent.com/75364377/192163038-97e44cfe-f4b5-4c1b-9fd1-93aa4f962dec.png)

**Comment by echasnovski** [comment]
Thanks for making an issue. I don't have Windows myself, so it will take time to figure this out. I'll look into it.

Although not sure if this is a 'mini.session' or 'mini.starter' issue. There shouldn't be full paths in 'Sessions' section.

**Comment by B4mbus** [comment]
Hmm right. I am actually willing to look into that myself and fix it. It actually seems like these are two separate issues. How about I edit this issue to only address `mini.starter` incorrect path displaying and create another one addressing `mini.session` being unable to create session directory under windows and file two separate PRs fixing those?

**Comment by echasnovski** [comment]
If you are willing to spend your time here, sure, go for it!

On first and second glances it is hard to see why this might be separate issues, though. In 'mini.starter' session names are taken directly from `MiniSessions.detected` (see [here](https://github.com/echasnovski/mini.nvim/blob/17f40dc27a46dbca97af3a29688c5ea6ab444423/lua/mini/starter.lua#L461-L468)). And `MiniSessions.detected` is computed during `require('mini.sessions').setup()`.

For reference:
- [Here](https://github.com/echasnovski/mini.nvim/blob/17f40dc27a46dbca97af3a29688c5ea6ab444423/lua/mini/sessions.lua#L449-L467) is how global sessions are detected.
- [Here](https://github.com/echasnovski/mini.nvim/blob/17f40dc27a46dbca97af3a29688c5ea6ab444423/lua/mini/sessions.lua#L102) and [here](https://github.com/echasnovski/mini.nvim/blob/17f40dc27a46dbca97af3a29688c5ea6ab444423/lua/mini/sessions.lua#L53) is how default directory for global sessions is computed. My first guess is that problem is somewhere here.

**Comment by echasnovski** [comment]
@B4mbus, can you look into this again please? Is this issue still there?

The 'mini.sessions' module now automatically creates missing directory for global sessions, so there shouldn't be any errors (see #134). The issue of weird 'mini.starter' behavior may still persist.

I have a follow up question. What files are **actually there** in directory `vim.fn.stdpath('data') .. '\\sessions\\` (to which you changed). Because I suspect that those can be actual base names of files there, which were created earlier by some other sessions management tool.

**Comment by echasnovski** [comment]
I was just able to verify on Windows machine that 'mini.sessions' and 'mini.starter' work as expected after initial set up. Both 'mini.sessions' created global default directory, was able to create a file there which 'mini.starter' recognized with correct name in "Sessions' section.

So closing this now.If you still experience this, feel free to reopen.
