### ISSUE TITLE
Add `@class` annotations for the various `setup()` option tables

### ISSUE THREAD

**Issue by tristan957** [echasnovski/mini.nvim#1330]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

all

### Description

It would be awesome if all the `mini` plugins could provide `@class` annotations, so we could all make our configs a little bit more type-safe.

My use case right now is:

```lua
---@type LazySpec
return {
  "echasnovski/mini.diff",
  ---@type MiniDiff.Config
  opts = {
  },
}
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

At the moment I don't support the decision to add LuaLS-EmmyLua-LuaCATS annotations to 'mini.nvim'. Mostly because it will add too much boilerplate lines which will duplicate already existing documentation.

One possible more or less bearable solution to this is to have a whole separate 'lua/mini/_meta/' directory with each module having its own file with its annotations. It has to be separate files to work nicely with dual distribution. Main big issue here is that it will not only significantly increase maintenance burden but also will separate code from its documentation (which I generally don't like).

I think I'll close this for now. **If** (a very big if) there will be work for adding class type annotations, it will be more general with all data structures used in 'mini.nvim'.
