### ISSUE TITLE
Can't get mini.icons to work?

### ISSUE THREAD

**Issue by tonebender** [echasnovski/mini.nvim#1335]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.icons

### Description

I have installed mini.icons (using vim.plug) and have require('mini.icons').setup() in my ~/.config/nvim/lua/init.lua (which is called from ~/.config/nvim/init.vim). I seem to have all the MiniIcons.* functions, but when I call them I get errors.

I'm using mini.icons standalone, not the whole mini library.

I have tried main and stable, same results with both.

I am using urxvt as terminal. OS is Debian Testing.

### Neovim version

0.9.5

### Steps to reproduce

1. Add `Plug 'echasnovski/mini.icons', { 'branch': 'stable' }` to ~/.config/nvim/init.vim
2. Call :PlugInstall
3. Add `require('mini.icons').setup()` to ~/.config/nvim/lua/init.vim
4. Call :lua MiniIcons.list()

### Expected behavior

A list of icons?

### Actual behavior

```
E5108: Error executing lua .../.local/share/nvim/plugged/mini.icons/lua/mini/icons.lua:496: attempt to concatenate local 'category' (a nil value)                                                                                     
stack traceback:
        .../.local/share/nvim/plugged/mini.icons/lua/mini/icons.lua:496: in function 'list'
        [string ":lua"]:1: in main chunk
```

What am I doing wrong?

How can I verify if mini icons are working?

**Comment by echasnovski** [comment]
Judging by the error message, 'mini.icons' is set up and working. The issue is that [`MiniIcons.list()` takes a mandatory string `category` argument](https://github.com/echasnovski/mini.nvim/blob/7b4d5d48b6b5a75009d63f8f3e4ef4819b7e8139/doc/mini-icons.txt#L453). So you can verify with something like `:=MiniIcons.list('filetype')` (note using `:=` as it will print the output; just using `:lua MiniIcons.list('filetype')` will show nothing).
