### ISSUE TITLE
Add togglability for terminal colors in mini.hues and mini.base16.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1344]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.hues, mini.base16

### Description

Hi echasnovski! Currently, the terminal colors are being set by the colorscheme generated using mini.hues in this line https://github.com/echasnovski/mini.nvim/blob/b07157c51e52a1b004ec7959f9618e9bc24686d3/lua/mini/hues.lua#L1370 and there is no way to turn it off. Is it possible to add some kind of option to plugins table to toggle these.

**Comment by echasnovski** [comment]
I don't think having terminal colors being not defined is a good idea. As you can see from the link you provided, terminal colors are defined through regular Vimscript global variables, i.e. `vim.g`. Toggling them should be a matter of custom helper function. For example:
- If at least one color is set, cache all current values and unset then (with `vim.g.terminal_color_x = nil`).
- Otherwise restore from cache and clear cache.

Closing as not planned.
