### ISSUE TITLE
mini.ai: Option to disable warning when no textobject was found

### ISSUE THREAD

**Issue by jooooscha** [echasnovski/mini.nvim#135]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

I would like to see an option for mini.ai, which disables all warnings when no textobject was found.

Problem:
When the neovim window is smaller than the warning message, it requires user input to go away.

Thanks for this very good module collection.

**Comment by echasnovski** [comment]
> When the neovim window is smaller than the warning message, it requires user input to go away.

I plan in the near future to update all such messages to respect window width and not cause hit-enter-prompt (i.e. not require user input to go away). It will truncate message. Will this solve your problem?

**Comment by jooooscha** [comment]
That sounds great. It would certainly help, but I would still like an option to display no warning at all.
But that's completely personal, and I would fully respect if you decided to not add that option.

Thanks for the fast reply :)

**Comment by echasnovski** [comment]
> That sounds great. It would certainly help, but I would still like an option to display no warning at all. But that's completely personal, and I would fully respect if you decided to not add that option.
> 
> Thanks for the fast reply :)

I also considered adding a unified `verbose` options to all modules producing such help messages. If `false`, it would not show them.

I will start with updating message logic to not result into hit-enter-prompt and think about not showing messages later.

To add. The reasoning behind showing this warning is for user to be aware that textobject is not found within `n_lines` lines and using current search method. Because it can cause confusion when textobject is large and don't fit inside searched neighborhood. Same goes for 'mini.surround'.

**Comment by jooooscha** [comment]
Yes. Thank you very much ❤

**Comment by echasnovski** [comment]
Should be possible now with global/buffer-local variables. See [this comment](https://github.com/echasnovski/mini.nvim/pull/224#issuecomment-1444005833).
