### ISSUE TITLE
Cursor should move when commenting

### ISSUE THREAD

**Issue by joshuajeschek** [echasnovski/mini.nvim#136]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

I want to comment out the current line in insert mode, so I mapped `<C-#>` in insert mode to `<C-o>:lua MiniComment.operator("line")<CR>`.
However, when executing this, my cursor does not move the appropriate amount of characters to the right / left because of the added / removed characters.

### Neovim version

0.7.2

### Steps to reproduce

comment line with `lua MiniComment.operator("line")`

### Expected behavior

the cursor should move with line content
- when there is text on the line the cursor should be at the same position in that text (relative to content, not absolute)
- when there is none, the cursor should be at the end of the line, not at the front

### Actual behavior

the cursor stays at the same character number, not relative to the text
![bug demonstration](https://user-images.githubusercontent.com/64850647/193250168-4df77e57-6d6c-4553-bc54-6e0679b9ca4e.gif)

**Comment by echasnovski** [comment]
Thanks for the issue!

This seems to be a result of `<C-o>` and `lua` command: it restores cursor to its original location. Similar to typing in Insert mode `<Esc>gcc` followed by `gi`.

The reason this is happening is because Neovim marks (used here) are fixed `(line, column)` pairs. Mechanism which respects adding and removing text is called extmarks. I tried to come up with solution for your case (set extmark, toggle line, set cursor to extmark location). But it also doesn't work since 'mini.comment' changes whole line for efficiency and extmark is moved to the next line.

The 'mini.comment' doesn't support Insert mode (and, probably, won't) and I can't see a way to fix this on 'mini.comment' side.
So sorry, I'll close this.

For reference, here is the code I tried for incorporating extmarks:
```lua
local ns_id = vim.api.nvim_create_namespace('MyInsCommentLine')
_G.comment_line_insert_mode = function()
  local cur_pos = vim.api.nvim_win_get_cursor(0)
  local extmark_id = vim.api.nvim_buf_set_extmark(0, ns_id, cur_pos[1] - 1, cur_pos[2], {})

  vim.cmd(string.format('lockmarks lua MiniComment.toggle_lines(%d, %d)', cur_pos[1], cur_pos[1]))
  local new_pos = vim.api.nvim_buf_get_extmark_by_id(0, ns_id, extmark_id, {})
  vim.api.nvim_win_set_cursor(0, { new_pos[1] + 1, new_pos[2] })

  vim.api.nvim_buf_del_extmark(0, ns_id, extmark_id)
end

vim.keymap.set('i', '<M-m>', '<Cmd>lua _G.comment_line_insert_mode()<CR>')
```

**Comment by joshuajeschek** [comment]
Thanks a lot! And also, thanks for the great plugin :)
