### ISSUE TITLE
mini.bracketed feature request: next/previous tab

### ISSUE THREAD

**Issue by gsinclair** [echasnovski/mini.nvim#1373]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bracketed

### Description

I would like to use ]t and [t to go to the next tab and the previous tab. This seems like a good fit given we can use mini.bracketed to navigate buffers, windows and files.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

`t` is reserved for [treesitter target](https://github.com/echasnovski/mini.nvim/blob/c8922aef8207137e66c80acdb9523668599ba62a/doc/mini-bracketed.txt#L57). It is intentional because tabpage navigation is already possible with `gt` and `gT`. As those are long standing built-in mappings, I think it is better for users in the long term to get used to them.

Closing as not planned.
