### ISSUE TITLE
mini.animate scroll is very slow for vertically long files.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1374]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

Pressing gg to go to top of the file and pressing G to go to bottom of file when scrolling animation is enabled is not smooth. It lags on big files and the ui stutters.

### Neovim version

v0.11.0-dev-1261+gab9cfc4dc3

### Steps to reproduce

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro({
	spec = {
		"echasnovski/mini.animate",
	},
})

vim.o.mousescroll = "ver:1,hor:1"
require("mini.animate").setup()
```

Please rename this file to sqlite3.c since github is not allowing me to upload files with .c extension
[sqlite3.c.txt](https://github.com/user-attachments/files/17967981/sqlite3.c.txt)
```sh
nvim -u repro.lua sqlite3.c
```

### Expected behavior

Scroll smoothly

### Actual behavior

Not scrolling smoothly

**Comment by 231tr0n** [comment]
On a side note, I do think the file sqlite.c is quite big and since a lot of calculations are done probably to get the scrolling effect it is slow. But I just wanted to see if you could make some performance optimizations to make this work.

**Comment by 231tr0n** [comment]
Also one last thing, for bug reproduction, I think it should be possible to create a minimal repro with mini.deps afaik. Do you think something like the lazy minimal repro but with mini.deps could be added to the bug_report template file if you think it is fine?

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce, but with some caveat: there is a smooth animation (at least) if it is the first scroll of the entire Neovim session. Later it is done in kind of two-step. Here is a demo of `G` and later `gg`:

https://github.com/user-attachments/assets/f4ce2f76-5a62-4798-a72f-055502f29460

Do you have the same experience?

**Comment by 231tr0n** [comment]
> Thanks for the issue!
> 
> I can reproduce, but with some caveat: there is a smooth animation (at least) if it is the first scroll of the entire Neovim session. Later it is done in kind of two-step. Here is a demo of `G` and later `gg`:
> mini-animate_scroll-bigfile-lag.mp4
> 
> Do you have the same experience?

For me it gets stuck while going up and down both.

**Comment by echasnovski** [comment]
> For me it gets stuck while going up and down both. Basically there is no scrolling effect anymore. That is the main issue.

That's not what I described. I also have it both up and down but *only after the first valid animation*.

**Comment by 231tr0n** [comment]
> > For me it gets stuck while going up and down both. Basically there is no scrolling effect anymore. That is the main issue.
> 
> That's not what I described. I also have it both up and down but _only after the first valid animation_.

Ohh ok my bad yeah.

**Comment by 231tr0n** [comment]
You are right the first animation is going correct. From then it stutters for both up and down motions. I can confirm.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.

The issue was not in scrolling per se, but the fact that its drawing was (somehow) blocked by cursor animation. I noticed it because disabling cursor animation made things work. "Works on first scroll" was also an indicator of this as cursor animation is not done on first move.

This problem in this issue manifested itself because cursor animation was done *on every line between start and end positions*. As each step was about 0.00096 milliseconds on 260000 line jump and [timers not working on sub-millisecond delay](https://github.com/echasnovski/mini.nvim/blob/ad46fda7862153107124f95d4ea0e510eafc1dd8/doc/mini-animate.txt#L504-L509) there were a lot of steps (about 1040) which were done "immediately". As each step is "delete extmark and add extmark", this somehow resulted into blocking the scroll redraw.

The solution here is to limit the number of steps in cursor animation. This is technically breaking, but nothing serious should be visible on user side (hopefully).

**Comment by 231tr0n** [comment]
As always awesome work.
One last thing @echasnovski how much time more till mini.snippets release.

**Comment by echasnovski** [comment]
> As always awesome work. One last thing @echasnovski how much time more till mini.snippets release.

I don't know. I have settled on design and the code is mostly working. Right now I am extensively beta-testing with daily usage. Testing and documentations remains. I am hopeful to release this month.
