### ISSUE TITLE
mini.deps and BufEnter autocmd

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1378]
I saw your reply here:

https://github.com/echasnovski/mini.nvim/issues/689#issuecomment-1939509494

and I also noticed this line in your configuration:

https://github.com/echasnovski/nvim/blob/4a8868a3aa082a18ed9c277c1c0354fd95a2566d/init.lua#L433

If I copy your configuration, and open markdown file, Neovim prompts me with `E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim:E492: Not an editor command: MarkdownPreview.`

Does this mean that all plugins using `BufEnter` autocmds need to be included in `MiniDeps.now`?

**Comment by aidancz** [comment]
a workaround is:

```
MiniDeps.later(function()

vim.api.nvim_exec_autocmds(
	{
		"BufEnter",
	},
	{})

end)
```

but this will execute `BufEnter` autocmds in `MiniDeps.now` twice, which will cause side effetcs

**Comment by echasnovski** [comment]
> If I copy your configuration, and open markdown file, Neovim prompts me with `E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim:E492: Not an editor command: MarkdownPreview.`
> 
> Does this mean that all plugins using `BufEnter` autocmds need to be included in `MiniDeps.now`?

Use `now()` if you want/need functionality to be available immediately after opening Neovim. Use `later()` otherwise.

This includes situations like `nvim -- README.md` and `:MarkdownPreview` command. If 'iamcco/markdown-preview.nvim' is loaded in `later()` then `nvim -- README.md` won't have `:MarkdownPreview` command because [it is created per buffer](https://github.com/iamcco/markdown-preview.nvim/blob/a923f5fc5ba36a3b17e289dc35dc17f66d0548ee/plugin/mkdp.vim#L138-L142) and those events were already triggered for 'README.md' file *before* `later()` callback was executed.

So if you want to be able to do `nvim -- README.md`, use `now()` (always or conditionally on whether there are arguments in this sesssion). Otherwise use `later()`.
