### ISSUE TITLE
Can mini.nvim modules use snacks.nvim's input module?

### ISSUE THREAD

**Issue by SwayKh** [echasnovski/mini.nvim#1394]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick mini.files

### Description

With snacks.nvim recently introducing a input modules. I was wondering if there's a way to use that with mini.nvim's modules like MiniPick's `MiniPick.builtin.grep()` word input or MiniFiles confirmation message? Snacks.nvim input seems to work for things like vim.lsp.buf.rename.

Or is that a different kind of input for the plugin. I'm not sure how this works, or if this already works, and maybe my config is wrong.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

All 'mini.nvim' modules prefer using `input()` Vimscript function (i.e. `vim.fn.input()`) to get input from the user because it is a blocking function which returns user's input as a string.

The 'folke/snacks.input' is an implementation of `vim.ui.input()` which is designed for asynchronous user input (by assuming later call to supplied callback). As documented design of `vim.ui.input()` is not suited for blocking call with returned value, it is relatively complicated to move 'mini.nvim' to use it *in all cases*. That's why I don't think this will happen any time soon (if at all).

One way to make `snacks.input` work with 'mini.nvim' input methods is to monkey-patch `vim.fn.input` to be a blocking call to `vim.ui.input()`. This is possible, but I'd not recommend this as it might cause unanticipated trouble.

So all in all, moving all 'mini.nvim' from `vim.fn.input()` to `vim.ui.input()` is certainly possible, but not worth a churn at this moment. I'd consider doing it if/when there is a dedicated `vim.ui.input()` in 'mini.nvim' (either synchronous or not). Closing as not planned (yet; in this form).

------

> ... like MiniPick's `MiniPick.builtin.grep()` word input

This [indeed uses `vim.fn.input()`](https://github.com/echasnovski/mini.nvim/blob/d084df4d6bf58abcc768b9bb326241ff0c502793/doc/mini-pick.txt#L1097-L1098), but can be made into a custom helper which uses `vim.ui.input()` for default `local_opts.pattern`:

```lua
local my_grep = function()
  vim.ui.input({ prompt = 'Grep pattern: ' }, function(pattern) MiniPick.builtin.grep({ pattern = pattern }) end)
end
vim.keymap.set('n', '<Leader>fp', my_grep, { desc = 'Find pattern' })
```

> ... MiniFiles confirmation message

This one uses `vim.fn.confirm()` which will is slightly different than both `vim.fn.input()` and `vim.ui.input()`.

**Comment by SwayKh** [comment]
Thanks for the quick and detailed response. And explaining the issues and differences between the input methods.

I love mini.nvim btw and can't wait for all the new modules you make! Thanks again and have a great day!
