### ISSUE TITLE
Beta-testing 'mini.starter'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#14]
Please leave your feedback about new 'mini.starter' module here. Feel free to either add new comment or positively upvote existing one.

Some things that I am interested to find out (besides seemingly omnipresent bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation clear enough? In particular, was it easy enough to find out about configurations similar to 'vim-startify' and 'dashboard-nvim'. Otherwise I understand that it might be a bit complex, but it is a price to pay for flexibility.

**Comment by JoseConseco** [comment]
I'm bit late to party but here are my feedback.
a) When pressing 'R' I got to 'Recent Files' but I'm not sure why there are weird highlights happening on  Sessions:
![image](https://user-images.githubusercontent.com/13521338/155516369-579e692a-5305-42a0-8b4e-9f7b085eaea1.png)

b) After pressing unique letter or number - I wish mini would immediately  execute 'Recent Files' action (or any other selected action) rather than having to confirm with RET
c) would be cool to be able to  navigate up or down with  jk.
Overall config is seems bit complicated, but I can live with it.  Maybe in future  starter could be configured as so:

```
 'Category/Section name' = 'Telescope',    'indexing' = 'number or letters' = {
  { item_name = ' recent files',  action = 'telescope recent_files',  optional_key_override = 'r'  },
  { item_name = ' recent sessions',  action = 'telescope recent_sessions',  optional_key_override = 'r'  },
  etc.
```

**Comment by echasnovski** [comment]
Thanks for using 'mini.starter'! Answers:
a) I believe, you are using Neovim nightly. This seems like a consequence of neovim/neovim#17358. I have a fix for that, but I would like to wait for an official resolution of this issue.
c) Yeah, I feel you. But they are used for quering items. I added `<Alt-j>` and `<Alt-k>` for more familiar navigation.
