### ISSUE TITLE
mini.ai: 2daa only deletes a single argument

### ISSUE THREAD

**Issue by SamuelBorn** [echasnovski/mini.nvim#1406]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

When inside a function with multiple arguments I expect `[n]daa` to delete the `n` two arguments.
But it only deletes that last (n-th) argument of `[n]daa]`.

### Neovim version

v0.10.2

### Steps to reproduce

1. Install mini.ai
2. Open reproduce.lua
 ```lua
function(foo, ba<CURSOR HERE>r, baz)

end
```
3. `2daa`

### Expected behavior

 ```lua
function(foo)

end
```

### Actual behavior

 ```lua
function(foo, bar)

end
```

**Comment by echasnovski** [comment]
I am afraid this is how "argument" textobject works. It is documented [in the help](https://github.com/echasnovski/mini.nvim/blob/7ebfab26d77a4b9b05aaae565907e7fa4b2ee154/doc/mini-ai.txt#L165C24-L165C39): when pressing `v2ia` it selects "next" argument and not both.

The reason for this is that it is an "argument" textobject and not "argument**s**", so it is designed to select only single argument at a time.

Moreover, when user executes textobject with `[count]`, it behaves [as if consecutive application was done in Visual mode](https://github.com/echasnovski/mini.nvim/blob/7ebfab26d77a4b9b05aaae565907e7fa4b2ee154/doc/mini-ai.txt#L129-L131) (so for `2aa` it is like pressing `aa` followed by another `aa`). Selecting "second next" argument works here because default `config.search_method` is `'cover_or_next'` and second consecutive application selects next argument (because there is no covering one as "argument" textobject doesn't support that). If search method were `'cover'`, there will be a warning about not being able to find the second textobject.

All in all, it works as expected (and documented). Hope this helps clarifying the reasoning.
