### ISSUE TITLE
pressing <C-t> in the mini.pick while selecting a session crashes neovim

### ISSUE THREAD

**Issue by Rishabh672003** [echasnovski/mini.nvim#1422]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

when mini.pick is selected as the frontend to vim.ui.select, when selecting a session if you press C-t, it crashes neovim

https://github.com/user-attachments/assets/bb3927e0-e41a-464e-b051-78e724d1263f

### Neovim version

Neovim nightly (NVIM v0.11.0-dev-1397+gfd05c7f19d)

### Steps to reproduce

Minimal.lua: 
```lua
-- Clone 'mini.nvim' manually in a way that it gets managed by 'mini.deps'
local path_package = "."
local mini_path = path_package .. "pack/deps/start/mini.nvim"
if not vim.loop.fs_stat(mini_path) then
  vim.cmd('echo "Installing `mini.nvim`" | redraw')
  local clone_cmd = {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/echasnovski/mini.nvim",
    mini_path,
  }
  vim.fn.system(clone_cmd)
  vim.cmd("packadd mini.nvim | helptags ALL")
  vim.cmd('echo "Installed `mini.nvim`" | redraw')
end

-- Set up 'mini.deps' (customize to your liking)
require("mini.deps").setup({ path = { package = path_package } })

require("mini.pick").setup()
require("mini.sessions").setup()
vim.ui.select = MiniPick.ui_select
```

1. `nvim -nu minimal.lua`
2. :lua MiniSessions.write("random")
3. :lua MiniSessions.select()
4. press <C-t> 

### Expected behavior

idk probably it should do nothing, opening a new session in a tab doesnt make sense

### Actual behavior

pressing <C-t> crashes neovim

**Comment by echasnovski** [comment]
Thanks for the issue!

This appeared to be an upstream Neovim issue: neovim/neovim#31680. It manifested itself because `vim.ui.select()` from 'mini.pick' executes its callback with floating window being current *and* `MiniSessions.read()` executes `:%bwipeout!` to have clean session loading.

As this is indeed not really a common case to do (specifically executing "read session" in combination with "execute in new tabpage"), I am going to close this as "not the issue with 'mini.nvim' and more of upstream Neovim issue".
