### ISSUE TITLE
mini.files support preview image

### ISSUE THREAD

**Issue by zqqqqz2000** [echasnovski/mini.nvim#1423]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Now the preview of mini.file does not support previewing images. Whether to add image preview support (if the terminal allows it) and related options.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is not planned at the moment due to either high complexity or needing to introduce third party dependency. Plus, it doesn't really fit the [decision of not trying to be a full file explorer](https://github.com/echasnovski/mini.nvim/blob/4228f166ee9db3e910eea1915e2d3683028add47/doc/mini-files.txt#L26-L28): as it is not reasonable to expect images to be edited, having they anything extra is (currently) out of scope.

Closing as "currently it is too complex to support; once there is built-in tools in Neovim itself for that (see neovim/neovim#30889), this can be revisited".
