### ISSUE TITLE
Allow specifying `--git-dir` argument

### ISSUE THREAD

**Issue by ccjmne** [echasnovski/mini.nvim#1430]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.diff

### Description

Hello,

I'm managing my dotfiles using a bare repo at `~/.dotfiles`, with its work tree at `~`. Therefore, I'm never really "inside a Git repository", unless I specify `--git-dir=~/.dotfiles`.

I see that `mini.diff` already appears to query Git in order to determine where my repository is.
Would it be possible to optionally supply `gen_source.git` with a parameter that would specify which Git repository I mean to be using?

Since the answer to the above question is "yes", I suppose what I really mean to ask is: would you be open to accepting a Pull Request that makes this happen? :)

I don't really want to resort to using the GIT_DIR environment variable, as I will browse different directories within the same Vim instance.

Thank you, and Merry Christmas!

**Comment by echasnovski** [comment]
Thanks for the suggestion!

At glance, this is not so simple. There are the following issues:
- The `gen_source.git` returns a single source which then for each buffer does its job: attach, update reference text, detach, apply. So in order for this use case to work, there should be `gen_source.git(opts)` with `opts.compute_git_dir = function(buf_id) ... end` which dynamically computes the location of '.git' directory. Not sure that all this complexity is worth for a rather not-so-common use case.
- As far as I understand, the information about the '.git' directory should be propagated to *all* instances of using Git CLI. That is during: attaching, getting reference text, applying hunks. Which is a bit painful to do.

Too bad that dynamically setting environment variable (like, on `BufEnter` or `DirChanged` events) doesn't seem like a robust solution, because reference text computation should be able to be computed at any time (for example, if Git index has changed).

I'll think about it a bit more, but I'd personally much rather find some Git-native solution to this problem. Maybe there is a way of setting `GIT_DIR` like information per working directory (instead of a single environment variable)?

**Comment by echasnovski** [comment]
> I'll think about it a bit more, but I'd personally much rather find some Git-native solution to this problem. Maybe there is a way of setting `GIT_DIR` like information per working directory (instead of a single environment variable)?

Sure enough, there is. There can be '.git' *file* at the root of the working tree ('~' in your case) with the following content:
```
gitdir: dotfiles
```

This should treat '~' as a repository with '~/dotfiles' as its '.git' repo.

However, every call to `git` must also contain `--work-tree` information with location of work tree. Which I am not sure how to work around both concisely and user-friendly.

If you have any actionable ideas, please feel free to share them here as comment (a bit too soon for the PR, I think).

**Comment by echasnovski** [comment]
What I found is that [this answer](https://stackoverflow.com/a/11856892) seems to make it work with the "separate Git directory for dotfiles" kind of use case. It won't make use of bare repo, but seems a bit more straightforward to me:

In particular, I managed it to work with the following setup:

```bash
mkdir tmp-home && cd tmp-home
git init --separate-git-dir=dotfiles
echo 'dotfiles' > .gitignore

git add .
git commit -m "Initial commit"
```

After that, any "normal" workflow works as expected: both 'mini.diff' and 'mini.git'. Maybe this can be a solution to the use case?

**Comment by ccjmne** [comment]
Wow!
Live and learn... every day?! I had *no idea* that the `.git` directory could be a *file* containing a `key: value` pair (which isn't even the syntax for `.gitconfig`) that specifies where the Git dir is.
Thank you, I'll check this out later today.

I suspect it won't be most ideal for me, because I don't like the idea of always being inside a Git repo, with my shell prompt telling me what branch I'm on... But that's a solution. Although at this point, I might as well just have a regular Git directory at `$HOME` ;) Or am I missing something?

Regarding the usage of `gen_source.git` I was envisioning, I figured I'd manually instruct `mini.diff` to switch sources when I want to, just like you could choose to go from Git to "last saved version". And yeah, I did think maybe some smart-ish hand-rolled AutoCmd switch might be helpful, but that just isn't generic/flexible enough to land in tool used by the community rather than just by me. Also, it gets wonky: what if we have two buffers, one to a "regular Git" file, and one to a "global dotfile Git" file?

In the end, do I really dislike knowing that I am inside a Git work tree all the time? Anyhow, thank you again for your investigation, I've got some thinking to do.

Cheers!

**Comment by echasnovski** [comment]
> Live and learn... every day?! I had _no idea_ that the `.git` directory could be a _file_ containing a `key: value` pair (which isn't even the syntax for `.gitconfig`) that specifies where the Git dir is.
> Thank you, I'll check this out later today.

I suspect it won't work 100% (I tried): 'mini.diff' will recognize that it is "inside" git repository, but getting reference text would fail as it requires also having the `--work-tree` parameter. And that is the problem because I am not sure about the proper way of getting it automatically with the bare repo case. Because (as far as I understood) that's the point of bare repo: it just contains Git information which is not tied to the work tree (thus requiring user to explicitly say where the work-tree is).

The `--separate-git-dir` works as expected, though. This automatically creates '.git' file and sets `core.worktree` in the repo config to a proper path (expanded '~' in this case).

> Although at this point, I might as well just have a regular Git directory at `$HOME` ;) Or am I missing something?

Hmm... That's a great point actually. The only benefit of `--separate-git-dir` is to have '.git' directory outside of work tree directory (for some reason).

------

All that leads me to believe that having 'mini.diff' (and 'mini.git', for that matter) work with bare repos is a challenge that needs a *very* compelling reason or a *concise* eventual solution. If you or anybody else figure out either one (preferably the concise solution), please leave a comment here. I'll close this for now.
