### ISSUE TITLE
MiniPick.set_picker_opts can't add or rewrite custom action

### ISSUE THREAD

**Issue by aShabat** [echasnovski/mini.nvim#1435]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

I'm trying to write picker that can switch between searching for files and searching for directories to then open them in mini.files. I've written custom action 'toggle' that uploads directories from fd and should redefine 'toggle' to load file items from fd. But the action is not redefined

### Neovim version

0.10.3

### Steps to reproduce

1. write code
```
M.pick_dirs_action = function ()
    local opts = {
        mappings = {
            toggle = {
                char = '<c-f>',
                func = M.pick_files_action,
            },
        },
    }
    MiniPick.set_picker_opts(opts)
    MiniPick.set_picker_items_from_cli{ 'fd', '--type=d', '--no-follow', '--color=never' }
end
M.pick_files_action = function ()
    local opts = {
        mappings = {
            toggle = {
                char = '<c-f>',
                func = M.pik_dirs_action,
            },
        },
    }
    MiniPick.set_picker_opts(opts)
    MiniPick.set_picker_items_from_cli{ 'fd', '--type=f', '--no-follow', '--color=never' }
end

M.pick_files = function (local_opts, opts)
    opts = vim.tbl_deep_extend(
        'force',
        {
            mappings = {
                toggle = {
                    char = '<c-f>',
                    func = M.pick_dirs_action,
                },
            },
        },
        opts or {}
    )
    MiniPick.builtin.files(local_opts, opts)
end
vim.keymap.set('n', '<leader>fd', M.pick_files)

```
 
3. press '<leader>fd' then <c-f><c-f>

### Expected behavior

After first <c-f> items change to directories. After second they should change back

### Actual behavior

Items stay as directories

**Comment by echasnovski** [comment]
Thanks for the issue!

This indeed was the case because those mappings were cached once after picker started and not updated with `set_picker_opts()`. This use case also showed some minor issue with `set_picker_items()` (which is used by `set_picker_items_from_cli()`) about not properly updating actually shown items. Should be fixed now.

The code snippet from the issue should now work after a reasonable tweaking:
- Fix typo in `func = M.pik_dirs_action,` -> `func = M.pick_dirs_action,`
- Unset `scroll_down` built-in action which is `<C-f>` by default. For this, add `scroll_down = ''` in initial `config.mappings`. Or better yet, use some other not used or less significant key (like `<C-d>` or `<C-t>`, for example).

**Comment by aShabat** [comment]
Thank you!

**Comment by aShabat** [comment]
Before the issue is closed, another small question. I'm having troubles opening mini.files from mini.pick. When I add to my previous code snippet 
```
...
source = {
    choose = function(item)
        MiniFiles.open(MiniPick.get_picker_opts().source.cwd .. '/' .. item, false)
    end,
},
...
```
in table inside `M.pick_dirs_action`, choosing the directory opens file explorer but then closes it after 1 second. I assume it's because of how picker is closed. Is there some workaround?

**Comment by echasnovski** [comment]
> choosing the directory opens file explorer but then closes it after 1 second. I assume it's because of how picker is closed. Is there some workaround?

Not really because of how picker is closed, but how 'mini.files' is opened. 

'mini.pick' automatically returns focus to its target window (as mentioned [here](https://github.com/echasnovski/mini.nvim/blob/2faada1cffce5609d78ac5e81eaf3754e0476758/doc/mini-pick.txt#L836-L837)) but not immediately (for various reasons). In turn, 'mini.files' is autoclosed if it is not in focus (which is checked periodically every second). So it autocloses once it understands that it is not in focus.

Using `vim.schedule(function() MiniFiles.open(MiniPick.get_picker_opts().source.cwd .. '/' .. item, false) end)` should work here.

**Comment by aShabat** [comment]
I see. Thank you again!
