### ISSUE TITLE
Underline indicator for Tabline

### ISSUE THREAD

**Issue by bangedorrunt** [echasnovski/mini.nvim#152]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tabline

### Description

I'd like to see underline indicator for current active buffer as following

<img width="481" alt="Screen Shot 2022-11-06 at 11 26 31 am" src="https://user-images.githubusercontent.com/1514823/200148446-d06c8e78-62fe-48be-9dc4-db63a433b05f.png">

At the moment, I'm using akinsho/bufferline.nvim with custom `TablineSel` highlight group to get the above look. To be honest, I prefer your plugin because `bufferline.nvim` is more feature-bloated, and I don't use all of them.

Thank you for great plugin!

**Comment by echasnovski** [comment]
I am glad that documentation is not *that* obscure :)

You might also want to tweak `MiniTablineModifiedCurrent`.

**Comment by echasnovski** [comment]
> Also if you don't mind giving me an advice how to get color for tabline icons. Not sure if it's worth a new feature request :)

Unfortunately, this is not currently possible by design. Mostly because initially there were no icons at all to fit more tabs, but they proved to be useful, so I added them. Having it the same color as text makes a more coherent look with 'mini.statusline'.

If this is crucial for you, feel free to open an issue about it. But even if implemented, it would use highlighting from 'nvim-web-devicons'.
