### ISSUE TITLE
Transparency and Dim Inactive support for mini colorscheme

### ISSUE THREAD

**Issue by vihu** [echasnovski/mini.nvim#162]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.base16

### Description

Thank you for your excellent plugin suite. I was wondering if you could add two extra config parameters for `mini.base16`, specifically:

- transparent_mode (bool): Support transparency if specified by the terminal emulator (kitty/wezterm for example)
- dim_inactive (bool): Support dimming inactive buffer splits

For reference, I added the two options for gruvbox [here](https://github.com/ellisonleao/gruvbox.nvim/pull/149), it would be really nice to support these for mini colorscheme as well :)

**Comment by echasnovski** [comment]
Thanks for suggestion!
It seems like a small but valuable change. I'll think it through and test it for some time. Your reference PR is very handy, thanks!

**Comment by echasnovski** [comment]
I have two thoughts about this right now:
- Unfortunately, the simple dimming of inactive windows (set slightly darker background) seems impossible under Base16 because background is already the darkest color (in dark color scheme).
- If making transparent background is as much as disabling `Normal` highlight group, I am leaning towards adding `hi Normal guifg=NONE guibg=NONE` to documentation for that. Either as a separate call or inside autocommand for `ColorSchemePre` event.

Am I missing something here?

**Comment by echasnovski** [comment]
I've given this some thought and I think it is better to not include both dimming and transparency in the 'mini.base16' config.

The reason for dimming is as stated earlier: there is no color in base16 palette that can be used for dimmed background.

The reason for transparency is that it indeed seems to be a case of "disabling" `Normal` highlight group. Thus can be done with a described `highlight` call (possibly inside autocommand).

Thank you for taking interest in improving 'mini.base16'.

**Comment by Mateiadrielrafael** [comment]
Hi @echasnovski !

Disabling the normal group does not seem to be enough. Example screenshot:
![image](https://github.com/echasnovski/mini.nvim/assets/39400800/9d210782-1c07-498a-ab47-13dc38d77e6d)

Here's the same screenshot with the dedicated catppuccin theme:
![image](https://github.com/echasnovski/mini.nvim/assets/39400800/9da3b80c-4fe2-41bc-8c92-008835d27749)

**Comment by echasnovski** [comment]
> Disabling the normal group does not seem to be enough. Example screenshot:

Yes, indeed it is not quite enough to achieve 100% transparency, but it is close. Since this issue was closed I've added ['mini.colors'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-colors.md) which has the ability to [add transparency](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-colors.txt#L409) to any color scheme. So I'd suggest either use it directly (in a form of creating and managing your own color scheme file) or clear highlight groups which bother with not being transparent ([here is a list](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/lua/mini/colors.lua#L1244-L1267) from 'mini.colors' implementation).

**Comment by Mateiadrielrafael** [comment]
Hi again!

I was able to use `mini.colors`, although it's still missing a few areas
![image](https://github.com/echasnovski/mini.nvim/assets/39400800/d85af25a-f5dd-4a03-9c8f-72d0d01c023c)

(in this instance, telescope and the gitsigns column thingy)

I'm not sure how I'd even go about finding what the names of those highlight groups is. I'm also not sure how I'd go about fixing bad contrast areas like this one in the mini statusbar:
![image](https://github.com/echasnovski/mini.nvim/assets/39400800/106ed184-ecf1-41dc-b819-d25bf7ffd16c)

Who knows, perhaps generic generated colorschemes can't look quite as good as handmade ones, although that's a bit sad.

If it helps in any way, here's my current colorscheme file:
```lua
local base16 = require("mini.base16")
local colors = require("mini.colors")

base16.setup({ palette = ... })

colors
  .get_colorscheme()
  :add_transparency({
    general = true,
    float = true,
    statuscolumn = true,
    statusline = true,
    tabline = true,
    winbar = true,
  })
  :apply()

vim.cmd([[highlight FloatBorder blend=0 guibg=NONE]])
vim.cmd([[highlight MiniStatuslineFilename blend=0 guibg=NONE]])
vim.cmd([[highlight Statusline blend=0 guibg=NONE]])
vim.cmd([[highlight StatuslineNC blend=0 guibg=NONE]])

```

The last 4 cmds were there from my time using the actual catppuccin theme, so I'm not 100% they are still needed.

**Comment by Mateiadrielrafael** [comment]
Looking at `/etc/stylix/palette.html` (which is a html preview of my current base16 theme), it does look like the backgrounds 03 and 04 have bad contrast with the text:
![image](https://github.com/echasnovski/mini.nvim/assets/39400800/d54b8193-2129-44b7-a611-d1d1e90212ea)

Is this something normal, or is it an issue with the base16 theme itself?
