### ISSUE TITLE
Stay at the original char after operation on surroundings

### ISSUE THREAD

**Issue by fjchen7** [echasnovski/mini.nvim#191]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Currently, the cursor will move to opening bracket after the operation on the surrounding. I think this is a bit counterintuitive and most time I have to move back to the original char.

Illustration (`*` is cursor)

| Key  | Line            | Delete        | Replace         |
| ---- | --------------- | ------------- | --------------- |
| `)`  | `!( *a (bb) )!` | `! *a (bb) !` | `(( *a (bb) ))` |

The cases about cross lines and the original position on bracket may need to be handled specially.

**Comment by echasnovski** [comment]
Thanks for suggestion!

I've thought about it several times already. There are two main reasons for this behavior:
- "Preserving" cursor usually means additional (not trivial) computations because text usually changes.
- It is a default Neovim behavior for operators. See [docs about operators](https://neovim.io/doc/user/motion.html#operator): "After applying the operator the cursor is mostly left at the start of the text that was operated upon.".

Let this be open for a while, but I doubt this will change.

**Comment by echasnovski** [comment]
I think I am going to close this because the current behavior is more in line with Neovim's behavior for operators. And it is a good thing.

Thanks again for suggestion!

**Comment by azmr** [comment]
> * "Preserving" cursor usually means additional (not trivial) computations because text usually changes.
> * It is a default Neovim behavior for operators. See [docs about operators](https://neovim.io/doc/user/motion.html#operator): "After applying the operator the cursor is mostly left at the start of the text that was operated upon.".

(I thought this seemed better here given context, but I can start a new issue if preferred.)

Hey, thanks for your work on all the `mini.nvim` plugins.

Would it be possible to (have an option to) have the final position for cursor be the start of the left-hand surround text.

Current behaviour:
```
Before:
some_statement
  ^
After saiw:
(some_statement)
 ^
```

My preferred behaviour:
```
Before:
some_statement
  ^
After saiw:
(some_statement)
^
```

Some justification:
- This was the default behaviour with `tpope/vim-surround`
- It's particularly useful because the typical case is to have an expression, wrap it in parens, then insert `if` or `function_call` etc before the first paren. The current behaviour requires extra movement before doing so.
- It's reasonable to include the added surrounds within the definition of "the text that was operated upon", at which point my suggested behaviour is the natural consequence.

Thanks,
Andrew

**Comment by echasnovski** [comment]
Thanks for kind words!

> Current behaviour:
> 
> ```
> Before:
> some_statement
>   ^
> After saiw:
> (some_statement)
>  ^
> ```

The current behavior is most certainly the preferred way because it enables dot-repeat on the same textobject.

Although the suggested behavior is useful for adding `if` before it, there are other use cases which benefit from current behavior. For example, wrapping in function call with `saiwf` and then prepend arguments inside the parenthesis.

> * It's reasonable to include the added surrounds within the definition of "the text that was operated upon", at which point my suggested behaviour is the natural consequence.

I don't think it is reasonable to include added surrounds, as they are the result of operation on the text that was operated upon.
