### ISSUE TITLE
'mini.pairs' lag on large files

### ISSUE THREAD

**Issue by barrett-ruth** [echasnovski/mini.nvim#196]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pairs

### Description

Slightly laggy pairing on large files

### Neovim version

NVIM v0.9.0-dev-626+g42afa0369

### Steps to reproduce

minimal.lua:
```lua
require('mini.pairs').setup {}
```

1. `nvim -nu minimal.lua`
2. Open up a large file, like [this one](https://git.suckless.org/dwm/file/dwm.c.html)
3. Go to a random line
4. Begin typing pairs

### Expected behavior

Instantaneous pairing

### Actual behavior

First off, I love your plugins. Your work is great.

Now I hate to make comparisons, but in my experience [nvim-autopairs](https://github.com/windwp/nvim-autopairs) just has mini.pairs beat in this regard. While I really want to use mini.pairs as I adore the minimal, non-bloated design of your plugins, there is a *slight* lag on large files that I just can't ignore. 

On small files mini.pairs works instantaneously, but what I need from a pairing plugin is for it to do that all the time, no matter what.

Then again, it is definitely possible I'm missing something. Let me know if you can replicate the issue.

**Comment by echasnovski** [comment]
I *think* I can't reproduce. This is how I have it on your large file (and even larger):

https://user-images.githubusercontent.com/24854248/212401246-ea6f0661-1c22-4ac3-95be-294591606388.mp4

Do you experience lag on all or only some pairs? The usual reason for any kind of lag when dealing with mappings is that there is some other one which "extends" the trouble one. In that case (Neo)vim should wait for some time (`:h 'timeoutlen'`) because it is unsure if user is going to add another keys.

Try executing `:imap (` (and other troubled keys) and seeing if there is anything else.

**Comment by barrett-ruth** [comment]
It is not the timeoutlen issue. I will try to debug literally every plugin I have in my config (a fun process).

Thanks for the quick response.

**Comment by echasnovski** [comment]
> It is not the timeoutlen issue. I will try to debug literally every plugin I have in my config (a fun process).
> 
> Thanks for the quick response.

Do you experience bigger lag than what I've posted? If you can, could you show how yours look?

**Comment by barrett-ruth** [comment]
I do (and once again "lag" is like a hundredth of a second, just enough to notice/bother me). You can notice the cursor flicker from the left to the right pair as it is inserted.

However, I removed all my plugins except for mini.pairs from my config and the lag was gone. So I guess I'll report back after further investigation.

**Comment by echasnovski** [comment]
> I do (and once again "lag" is like a hundredth of a second, just enough to notice/bother me). You can notice the cursor flicker from the left to the right pair as it is inserted.
> 
> However, I removed all my plugins except for mini.pairs from my config and the lag was gone. So I guess I'll report back after further investigation.

Well, that is good.

My first guess was (is) conflicting mappings, because that cursor lag sound kind of like it. The second one is tree-sitter highlighting, diagnostic, or formatting. The third - some other plugin that might affect Insert mode (completion, etc.).

> BTW, what software do you use to record videos? Thanks.

SimpleScreenRecorder for video and ScreenKey for key captures.

**Comment by barrett-ruth** [comment]
It seems it is due to a combination of nvim-cmp and tree-sitter. Nothing really to be done about it. I suppose I'll continue with mini.pairs because it really does function perfectly well in every other way. Thanks!

**Comment by echasnovski** [comment]
Thanks for the follow-up!
