### ISSUE TITLE
Make `todo-comments` snippets with `mini.comment`

### ISSUE THREAD

**Issue by bangedorrunt** [echasnovski/mini.nvim#213]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

Hi @echasnovski I'm wondering if you can convert the following using `mini.comment` coz I'd prefer using your plugin to `Comment.nvim` 
https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#all---todo-commentsnvim-snippets

**Comment by echasnovski** [comment]
I believe that the only piece of code depending on `Comment.nvim` here is the [`get_cstring()`](https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#finding-the-comment-string) function? If yes, does the following snippet work for you?

```lua
local get_cstring = function()
  local left, right = unpack(vim.fn.split(vim.bo.commentstring, '%s'))
  return { left or '', right or '' }
end
```

The 'mini.comment' module works only with whole line commenting, so no need to do anything with block comments.

**Comment by echasnovski** [comment]
> @echasnovski I'm not sure if it is expected behavior,

It says that `get_cstring()` doesn't expect arguments, which is true, because it works only for line commenting. No need for `opts.ctype`.

> Also this doesn't seem to work with treesitter commentstring, ex, I set nix ft comment to "# %s", but Luasnip automatically insert /* %s*/. Hope you might have better solution. 

It uses `vim.bo.commentstring` to compute parts. Make sure it is set to an appropriate one.

If you use 'JoosepAlviste/nvim-ts-context-commentstring', then make sure to execute `require("ts_context_commentstring.internal").update_commentstring({})` prior. Maybe something like this:

```lua
local get_cstring = function()
  require("ts_context_commentstring.internal").update_commentstring({})
  local left, right = unpack(vim.fn.split(vim.bo.commentstring, '%s'))
  return { left or '', right or '' }
end
```

> I will reopen the issue, but feel free to close it if you think it's not worth it. Many thanks for your time and effort!

Yes, I think I am going to close this, as it really has nothing to do with 'mini.comment'.
