### ISSUE TITLE
[mini.trailspace] cannot disable highlighting in LsaSaga's finder window

### ISSUE THREAD

**Issue by farzadmf** [echasnovski/mini.nvim#221]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.trailspace

### Description

I want to disable trailing space highlighting in [lspsaga](https://github.com/glepnir/lspsaga.nvim)'s finder window (`LspSaga lsp_finder` command)

![image](https://user-images.githubusercontent.com/5768792/217278750-cc2011e9-e22f-4115-8daf-478654e5c26a.png)

What I have in my config (using `lazy.nvim`):
```lua
{
  'echasnovski/mini.trailspace',
  event = 'BufReadPost',
  opts = {
    blacklist = {
      'lspsagafinder',
    },
  },
  config = function(_, opts)
    vim.api.nvim_create_autocmd('FileType', {
      pattern = opts.blacklist,
      callback = function()
        vim.b.minitrailspace_disable = true
        MiniTrailspace.unhighlight() -- force an update?
      end,
    })

    require('mini.trailspace').setup()
  end,
}
```

If I manually call `:lua MiniTrailspace.unhighlight()`, the whitespace highlighting will be disabled

### Neovim version

0.8.3

### Steps to reproduce

Sorry, since my issue requires LSP and other stuff, I didn't create a minimal config. Let me know if that's necessary and I can try creating one

### Expected behavior

I expect the highlighting to be disabled in the `lspsagafinder` file type (when I do `:set ft?` in that window, that's the filetype I get

### Actual behavior

The spaces keep being highlighted

**Comment by echasnovski** [comment]
Everything seems to be OK.

Are you sure that `vim.b.minitrailspace_disable` is actually set to `true` in that buffer? Can you execute `:lua print(vim.b.minitrailspace_disable)` while being inside LSPSaga's buffer? It should print `true`. If it prints `nil`, it wasn't actually set.

**Comment by farzadmf** [comment]
Yup, when I do `:lua print(vim.b.minitrailspace_disable)`, it prints `true` 🙁

**Comment by echasnovski** [comment]
I believe the reason is how 'lspsaga' creates those "lsp_finder" windows. See more in [this comment](https://github.com/glepnir/lspsaga.nvim/issues/844#issuecomment-1421124170). And one more piece to this puzzle: 'mini.trailspace' calls `highlight()` on every `WinEnter` and it *should* unhighlight in target window (as `vim.b.minitrailspace_disable` is indeed set in correct buffer), but the ever giving problem here is that `WinEnter` is not triggered for floating windows.

I managed to workaround this issue by using `vim.schedule(MiniTrailspace.unhighlight)` instead of directly calling `MiniTrailspace.unhighlight()` inside autocommand callback.

Does this solve it for you?

**Comment by farzadmf** [comment]
> I managed to workaround this issue by using `vim.schedule(MiniTrailspace.unhighlight)`

Yes @echasnovski , that does solve the issue it seems

Just wondering: if we do this, do we still need to set `vim.b.minitrailspace_disable` or it doesn't matter anymore?

**Comment by echasnovski** [comment]
> > I managed to workaround this issue by using `vim.schedule(MiniTrailspace.unhighlight)`
> 
> Yes @echasnovski , that does solve the issue it seems
> 
> Just wondering: if we do this, do we still need to set `vim.b.minitrailspace_disable` or it doesn't matter anymore?

If you want to state that this buffer shouldn't highlighted trailing whitespace, you should set it. Otherwise, at least in theory, you can rehighlight. In practice, it probably won't happen, as it seems that [target events](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/trailspace.lua#L69) won't get triggered in that buffer.

Closing this then, as it doesn't seem to really be a 'mini.trailspace' problem (at least for now).

**Comment by farzadmf** [comment]
Thank you @echasnovski for the help, greatly appreciated, it was driving me nuts 😆
