### ISSUE TITLE
Add function to toggle showing/hiding whitespace

### ISSUE THREAD

**Issue by hanschen** [echasnovski/mini.nvim#227]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.trailspace

### Description

Currently there are functions to show or hide trailing whitespace with `mini.trailspace`, but from what I can see no way to toggle showing/hiding whitespace. It would be nice to have such a function that can be bound to a keymap.

**Comment by echasnovski** [comment]
The reason it is not there mostly because there is no "show/hide" functionality. It was designed to be done with `vim.g.minitrailspace_disable` / `vim.b.minitrailspace_disable` possibly followed by call to `MiniTrailspace.highlight()`.

Does adding the next function work for you?

```lua
_G.toggle_trailspace = function()
  vim.b.minitrailspace_disable = not vim.b.minitrailspace_disable
  MiniTrailspace.highlight()
end
```

Use `vim.g` if you want to toggle globally instead of only for current buffer.

**Comment by hanschen** [comment]
Yes that is exactly what I want, thanks for the fast answer! Closing this issue.
