### ISSUE TITLE
mini.align standalone does not work

### ISSUE THREAD

**Issue by jaak-s** [echasnovski/mini.nvim#233]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.align

### Description

I'm using Lazy Nvim package manager with the following setup:
```lua
  {
    "echasnovski/mini.align",
    version = false,
    mappings = {
      start = "ga",
      start_with_preview = "gA",
    },
  },
```

### Neovim version

0.9

### Steps to reproduce

write two lines:
```
a = 10
xy = 20
```

select them with ctrl-V and press `ga` and `=`.

### Expected behavior

Should be aligned by adding space before the first line's `=`.

### Actual behavior

Selecting text and then pressing ga (and delimiter) does not align the text.

**Comment by echasnovski** [comment]
Standalone repository works, same as 'mini.nvim' itself.

You don't have it working is because `require('mini.align').setup()` was not called. You can check it yourself by executing `:lua print(_G.MiniAlign)`: should print message starting with `table: ` and not `nil`.

The reason it doesn't work seems to be because 'lazy.nvim' can't yet autoload plugin if its main file is in Lua submodule (like 'lua/mini/align.lua', for example). It is a good idea to look at how LazyVim handles standalone 'mini.nvim' repositories. For example, [this](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/coding.lua#L86).

Try using this config:
```lua
{
  "echasnovski/mini.align",
  version = false,
  mappings = {
    start = "ga",
    start_with_preview = "gA",
  },
  config = function(_, opts)
    require("mini.align").setup(opts)
  end,
},
```

**Comment by LvanderGoten** [comment]
Wouldn't it be helpful to update the install instruction with this? I guess many users face this when they install a standalone.

**Comment by LvanderGoten** [comment]
You're absolutely right. I think though that it is not entirely clear to beginners how do to the call to `require('mini.align').setup()` and having
```
{
  "echasnovski/mini.align",
  version = false,
  config = function(_, opts)
    require("mini.align").setup(opts)
  end,
}
```
instead of 
```
{ 'echasnovski/mini.align', version = false },
```
in the _Standalone_ section for lazy.nvim would ease the installation process. (P.S. thanks for your great work!)

**Comment by echasnovski** [comment]
> {
>   "echasnovski/mini.align",
>   version = false,
>   config = function(_, opts)
>     require("mini.align").setup(opts)
>   end,
> }

Having to combine `setup()` call with installation using 'folke/lazy.nvim' looks like more about reading 'lazy.nvim' documentation.
