### ISSUE TITLE
Creating highlight groups in `setup()` makes the neovim splashscreen disappear if called after startup

### ISSUE THREAD

**Issue by ibhagwan** [echasnovski/mini.nvim#238]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

https://github.com/echasnovski/mini.nvim/commit/1695f39f8343f1b129464c2811a01ee9aa61e636 - this commit causes the neovim splash screen (`:intro`) to disappear.

### Neovim version

0.8.3 & nightly

### Steps to reproduce

Start neovim with no "dashboard" screen, the neovim splash screen will quickly disappear, this is used to be a common issue with statusline plugins creating highlight groups on init.

### Expected behavior

Expect the splash screen to stay on screen.

### Actual behavior

Splash screen quickly diappears.

**Comment by echasnovski** [comment]
Thanks for the issue.

Couple of clarifications:
- On current commit (c4b6e6e) this seems to only happen if `require('mini.indentscope').setup()` is called after startup (like if lazy-loaded). So `nvim -u init-minimal.lua`:

    - Works fine (has intro splash screen) with the following 'init-minimal.lua':

        ```lua
        -- Register 'mini.nvim' when it is in 'pack/*/opt'
        vim.cmd.packadd('mini.nvim')
        require('mini.indentscope').setup()
        ``` 

    - Removes intro screen with the following 'init-minimal.lua':
    
        ```lua
        vim.schedule(function()
          vim.cmd.packadd('mini')
          require('mini.indentscope').setup()
        end)
        ```
- Same behavior is present before 1695f39 (specifically, on its parent 124b182): screen is removed with `schedule()`, present otherwise.
- If indeed [lines for highlight group creation](https://github.com/echasnovski/mini.nvim/blob/c4b6e6ede40578d5b94b557d62b6caf15d268dbf/lua/mini/indentscope.lua#L146-L150) are removed, intro screen is intact even with `schedule()`.

As far as I can tell, the core problem here is that creating highlight group (either with `:hi` or with `vim.api.nvim_set_hl()`) causes screen redraw. As said in [this 6 year old comment](https://github.com/neovim/neovim/issues/5881#issuecomment-270635733), that intro message is not a part of screen, so on any redraw event it gets removed. So this is not a problem of 'mini.indentscope' per se, but any module which creates highlight groups (like 'mini.jump' has this problem, but 'mini.bracketed' does not).

So I am not sure what can be done here. Highlight groups *should* be created for plugin to operate properly. They can all be created during startup, but that would affect its time and contradict with lazy loading of any module.

**Comment by ibhagwan** [comment]
Thank you for the detailed answer @echasnovski!

I use lazy.nvim (not packer) but the same applies, can’t lazy load mini anymore, once I change `lazy = false` the splash screen remains intact.

> So I am not sure what can be done here. Highlight groups should be created for plugin to operate properly. They can all be created during startup, but that would affect its time and contradict with lazy loading of any module.

I’m not sure either, but disabling lazy loading is a sufficient fix IMHO.

Ty again for all your amazing work, this plug-in has become a staple in any neovim installation, you should be nominated  for the “tpope of neovim” 😄

**Comment by echasnovski** [comment]
> Ty again for all your amazing work, this plug-in has become a staple in any neovim installation, you should be nominated for the “tpope of neovim” :smile:

Too high praise :)

Thank you!
