### ISSUE TITLE
mini.indentscope highlights on multiple windows

### ISSUE THREAD

**Issue by briandipalma** [echasnovski/mini.nvim#250]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

If you open two windows on the same buffer indentscope highlights on both as you move around. I'm using LazyVim.

https://user-images.githubusercontent.com/1597820/222766656-d58e3140-876a-4636-ab95-7969f7196582.mp4

### Neovim version

0.8.3

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Expected behavior

Only highlight the active window?

### Actual behavior

Highlighting every window with the same buffer.

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, this is impossible with current Neovim capabilities. The reason is that highlighting functionality (as is designed) is done with extended marks (a.k.a extmarks, see `:h extmark`). They are tied to the buffer and there is (currently at least) no way to show them only in some windows. And there seems to be no interest to implement it right now.

Closing this as there is nothing can be done here before new functionality is added to Neovim.
