### ISSUE TITLE
[mini.ai] Implementation of builtin text objects `w`, `W`, `p`

### ISSUE THREAD

**Issue by Gazareth** [echasnovski/mini.nvim#261]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

Hi there, thanks for the amazing plugins! I've recently been looking into using mini.ai's textobject search to automatically generate targets for [leap-spooky](https://github.com/ggandor/leap-spooky.nvim). However I've noticed that some text objects I was expecting to be there do not exist.

Here is the full list of 'builtin' ones according to the source I have:
![image](https://user-images.githubusercontent.com/11911259/224137247-6217db71-2463-4f0e-bac3-441db1a4abb1.png)

I was just wondering what the reason is for the ommission of `w` (word), `W` (WORD) and `p` (paragraph)? And if it makes sense to add them in?

**Comment by echasnovski** [comment]
Hi!

Well, mostly because they are pretty good in their built-in implementation. That said, I miss sometimes the possibility to change the next word with `cinw`.

Implementing `iW` and `aW` should be pretty straightforward as there are `%S` and `%s` in Lua patterns for non-blank and blank characters.

Implementing `iw` and `aw` seems to be many times harder as Lua patterns recognize alphanumeric only for Latin alphabet. There is also an issue of respecting user settings like 'iskeyword'.

Making `ip` and `ap` is also possible, but not with Lua patterns.

I'll consider it, but don't think it will be added in 'mini.ai' builtin textobjects.

**Comment by Gazareth** [comment]
I see. Thanks for the info and quick response. I'll try and implement them as custom text objects on my side for now.
