### ISSUE TITLE
[mini.animate] cmdheight becomes 1 after window resize animation

### ISSUE THREAD

**Issue by nikolasetiawan** [echasnovski/mini.nvim#270]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

This plugin is really cool. I was amazed that when my tmux window is resized, there's an animation for it.

But for some reason, when I drag my tmux window to become larger, the animation plays and then my cmdheight option becomes 1 (I default to 0)

I'm not sure where it went wrong. I'm using AtroNvim community setting: https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/scrolling/mini-animate

### Neovim version

0.8.3

### Steps to reproduce

1. open nvim
2. open neo-tree
3. enlarge nvim window
4. let animation happen
5. cmdheight is now 1

### Expected behavior

cmdheight stays 0

### Actual behavior

cmdheight becomes 1

**Comment by echasnovski** [comment]
Thanks!

Yes, I can reproduce it if terminal window is resized vertically quickly. If height changes slowly, it is still zero `cmdheight`.

Something tells me that it might stay that way, but I'll look into it.

**Comment by echasnovski** [comment]
Should be fixed in latest `main`.

I could reproduce this manually, but was not able to create a test for this. Still, applied solution (cache and restore value of `cmdheight` during resize animation) should be enough.

**Comment by echasnovski** [comment]
Unfortunately, the solution for this problem was conflicting with a more Neovim centered problem described in #2368 (resizing Neovim window when it is done by adjusting 'cmdheight'). At the moment I don't see a concise and robust solution that could satisfy both use cases, so this one has to be accepted as a known limitation. Or my honest suggestion would be to not use animations that have side effects (i.e. "scroll" and "resize"), as they are quite problematic.
