### ISSUE TITLE
[mini-surround] Can the surrounding be highlighted automatically when matching?

### ISSUE THREAD

**Issue by MasouShizuka** [echasnovski/mini.nvim#278]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-surround

### Description

Hello.

Can the surrounding be highlighted automatically when matching?

For example, the text is:
```
"te_st text"
```
And cursor is on `_`.
If `sr"` is pressed, the plugin will highlight the `"` on both sides.
And if `saiw` is pressed, the plugin will highlight `test`.

Well, it's just like [nvim-surround](https://github.com/kylechui/nvim-surround).
I know this plugin can highlight surrounding with sh, but it needs to be pressed separately, and it can't highlight text object.

**Comment by echasnovski** [comment]
Hi!

Sorry, no, this is by design. Surrounding highlighting is expected to be done on demand while highlighting textobject seems a bit excessive. And it usually adds visual noise in case user already wants what is going to be replaced/surrounded. So this original feature from [machakann/vim-sandwich](https://github.com/machakann/vim-sandwich) will not be supported.

**Comment by echasnovski** [comment]
> Is it possible to call the surrounding highlight function when `sr<char>` is pressed, just like `sh<char>`.

No, I don't that under current implementation it is possible.
