### ISSUE TITLE
Starter hides tabline

### ISSUE THREAD

**Issue by fazibear** [echasnovski/mini.nvim#281]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

starter

### Description

Opening when mini.starter is opened the tabline is hiddent. Is there a way to show tabline always?

### Neovim version

0.8.3

### Steps to reproduce

Configure starter and tabline
1. `nvim`
2. what do you see? Tabline is hidden!

### Expected behavior

Tabline should be  visible after starter open.

### Actual behavior

Tabline is hidden just after starter open.

**Comment by echasnovski** [comment]
Not showing tabline and showing statusline is by design. This (subjectively) looks better.

There is a [`MiniStarterOpened` event](https://github.com/echasnovski/mini.nvim/blob/63b26037fdf98e0cb72c7f089df18599e6cc79c6/doc/mini-starter.txt#L267-L269) which you can use to reshow tabline. Try adding this after `require('mini.starter').setup()` call:
```lua
vim.cmd('autocmd User MiniStarterOpened set showtabline=2')
```

Does this solve your issue?

**Comment by fazibear** [comment]
It works! Thanks! This is what I need!
