### ISSUE TITLE
Invert/Toggle comment on multiple lines

### ISSUE THREAD

**Issue by melhindi** [echasnovski/mini.nvim#283]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

I often want to toggle/invert comments in two lines of code, e.g., convert this:
```
// threshold = 10
threshold = 100
``` 
to this:
```
threshold = 10
// threshold = 100
```

Previously, I used to do this with nerdcommenter by selecting both lines and using `NERDCommenterInvert`.

I am not sure, but I think this missing feature is referred to in the help file as "Block and sub-line comments.
I would love to see this feature also for mini.comment - or is it already possible to do this?

**Comment by melhindi** [comment]
one workaround for visual mode would be using `'<,'>normal gcc<CR>`
as suggested here: https://github.com/numToStr/Comment.nvim/issues/17#issuecomment-939410954

**Comment by echasnovski** [comment]
Thanks for suggestion!

> one workaround for visual mode would be using `'<,'>normal gcc<CR>` as suggested here: [numToStr/Comment.nvim#17 (comment)](https://github.com/numToStr/Comment.nvim/issues/17#issuecomment-939410954)

Yes, this was something along the line I was going to suggest using. You possibly might also want to use `config.options.ignore_blank_line = true` to allow this action over blank lines.

I'll think about if it can be added naturally to 'mini.comment', but at the moment I think the `'<,'>normal gcc<CR>` is the way to go.

**Comment by melhindi** [comment]
thanks for your comment and the hint about the blank lines.
the next step would be to use a mapping as suggested in the above link
integrating it into the mini.comment would, however, safe even more keystrokes ;)
looking forward to hear what you think about the feature

**Comment by echasnovski** [comment]
Using `'<,'>normal gcc<CR>` in mapping like `vim.keymap.set('x', 'gi', ':normal gcc<CR>')` does seem like the best approach here. It is not perfect with default options (like blank lines will be commented), but it seems to do a decent job.

Unfortunately, I can't see how this can organically fit into current design. It will be either a virtually reimplementation of `normal gcc` in a not very optimized way or a complete rewrite of 'mini.comment'. Mostly because current design (for speed reasons) pre-computes action function (whether comment with certain indent or uncomment) and applies it to the whole region.

Closing as not planned.
