### ISSUE TITLE
Inline comments not working

### ISSUE THREAD

**Issue by RobertBeilich** [echasnovski/mini.nvim#300]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

I tried to comment out parts of a line, but it only ever comments out the whole line.

### Neovim version

v0.10.0-dev-74+gae9654dd73

### Steps to reproduce

1. `nvim -nu minimal.lua foo.js`
2. Have the cursor on `bar`, hit `gci(` (or make a visual selection of anything and hit `gc`)

minimal.lua:
```lua
local lazydatapath = "/tmp/minimal/lazy"
local lazypath = lazydatapath .. "/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  root = lazydatapath,
  spec = {
    "echasnovski/mini.comment",
    config = function()
      require("mini.comment").setup()
    end,
  },
})
```

foo.js:
```js
const foo = (bar) => {
}
```

### Expected behavior

```js
const foo = (/* bar */) => {
}
```

### Actual behavior

```js
// const foo = (bar) => {
}
```

**Comment by RobertBeilich** [comment]
Ok, nvm, had a look in the source and found:
https://github.com/echasnovski/mini.comment/blob/9ead47cef4266efa5145808b838762c658b74f74/lua/mini/comment.lua#L17-L18
--- What it doesn't do:
--- - Block and sub-line comments. This will only support per-line commenting.

That should definitely be part of the README. Or rather: why is this out of scope?

**Comment by echasnovski** [comment]
This is in README in title: "Comment lines". And no need to look at source code, as this information is also in [the top of help file](https://github.com/echasnovski/mini.nvim/blob/4716f26d7288e5f6de902480b3f3d045e3dd3f42/doc/mini-comment.txt#L17-L18) and there is a link to help file in the top of README. I'll think about adding more explicit wording in README.

The main reason this is out of scope is because there is no reliable built-in way to get information about how language is expected to do inline comment. For per-line commenting there is 'commentstring' option (which is mentioned in README), but for inline comments one should have to manually keep this information inside module. As dealing with language specific configurations is out of scope for 'mini.nvim' in general, this is also out of scope for 'mini.comment'.

Closing as it will change.
