### ISSUE TITLE
'mini.ai' doesn't work in Visual mode with 'which-key.nvim'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#316]
After 37837ff commit (which started to use Lua callbacks as right hand side of mappings where reasonable), 'mini.ai' doesn't work in Visual mode with 'which-key.nvim'.

Symptoms:
- 'mini.ai' works in Operator-pending mode, but not in Visual. For example: `daf` works, but `vaf` does not.
- Works without 'which-key.nvim', but does not work with it.

The core reason seems to be an upstream issue: folke/which-key.nvim#449.

Here are the ways to make it work:
- Add `triggers_blacklist = { v = { 'a', 'i' } }` to `require('which-key').setup()` call.
- Run `require('which-key').setup()` *before* `require('mini.ai').setup()` (so that 'mini.ai' has precedence in defining mappings).

**Comment by echasnovski** [comment]
This issue is mostly for future possible linking purpose, as it does seem to be a problem on 'which-key.nvim' side.

**Comment by garrett-hopper** [comment]
In case anyone runs into this in the future, I've noticed that which-key will not display text objects if `i`/`a` are pressed before `timeoutlen` in visual mode. (Instead showing the `Enter ... textobject identifier (single character)` message) I believe this is due to the `vi`/`va` (or `V`/`C-v`) being read together and `getcharstr` being called which blocks, causing which-key to not display anything.

I've worked around this by setting `timeoutlen` lower than the default `1000` to avoid the issue.

This also required me to use [better-escape.nvim](https://github.com/max397574/better-escape.nvim) to keep my "jj" binding working.

**Comment by echasnovski** [comment]
> ... (Instead showing the `Enter ... textobject identifier (single character)` ...

This come from 'mini.ai' one second after user pressed `a` or `i`, not 'which-key.nvim'.

> This also required me to use [better-escape.nvim](https://github.com/max397574/better-escape.nvim) to keep my "jj" binding working.

There is now similar functionality in 'mini.nvim', if you are interested: [`map_combo()`](https://github.com/echasnovski/mini.nvim/blob/473cdbff498ed120f1768c75ef65fa42859aa14f/doc/mini-keymap.txt#L140-L146) from 'mini.keymap'.

**Comment by garrett-hopper** [comment]
Thanks! `mini.keymap`'s `map_combo` works perfectly. 🙂

Also switched to `mini.surround` with these keybindings. Ended up with `timeoutlen` set to `200`, which is required to make the `ys`, `ds`, and `cs` bindings works. (Otherwise operating-pending mode will be entered and the `s` key will use the binding from that instead of running `mini.surround` 2 character binding.)

Appreciate all of your hard work on these, @echasnovski!

```lua
    require("mini.surround").setup({
      mappings = {
        add = "ys",
        delete = "ds",
        replace = "cs",
        find = "gzf",
        find_left = "gzF",
        highlight = "gzh",
        update_n_lines = "gzn",
        suffix_last = "l",
        suffix_next = "n",
      },
      respect_selection_type = true,
    })
```
