### ISSUE TITLE
 mini.cursorword unhighlight when the cursor is not on the buffer.

### ISSUE THREAD

**Issue by Weissle** [echasnovski/mini.nvim#318]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

 mini.cursorword

### Description

mini.cursorword highlights the word under the cursor. However, even if we switch the window, the highlight still exists. Could we unhighlight before we leave a window?

**Comment by echasnovski** [comment]
Thanks for suggestion!

I remember making conscious decision about this and ruled in favor of current behavior. I believe this is because I found it useful to have those highlights as reference when navigating in different window.

I'll take another look.

**Comment by echasnovski** [comment]
Yes, this behavior is intentional for two reasons:
- It is indeed proved useful for reference during quick edit of another window. Just used this today.
- Technically, any window always has "cursor" tracked, even if it is not active. So there is still cursor when you leave window.

Sorry, I don't see this changed in the near future.

**Comment by Weissle** [comment]
sure. Thanks.
