### ISSUE TITLE
[surround] How to surround a line with empty lines?

### ISSUE THREAD

**Issue by lfilho** [echasnovski/mini.nvim#321]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Surround

### Description

Basically what i wanted is:

With the cursor anywhere on line two:
```
one
two
thre
```

get the following result:

```
one

two

three
```

I tried `sa_<enter>`, but then it just surrounds that line with enter's code `^M`, which i hardly think will be useful to anyone. Could we maybe intercept that `^M` and actually surround the line with new lines? Or maybe there's already a way to achieve that that i'm missing?

Thanks a lot for your great work

**Comment by echasnovski** [comment]
Thanks for suggestion!

I don't think it is possible under current design. The closest you can get is via setting `respect_selection_type = true` and then using interactive surrounding `?` like `sa_?<CR><CR>`. But this will indent current selection.

There are alternatives:
- Use custom mappings. Like so:
```lua
vim.keymap.set('n', '<M-m>', [[<Cmd>call append(line('.'), '') | call append(line('.')-1, '')<CR>]])
vim.keymap.set('x', '<M-m>', [[:<C-u>call append(line("'>"), '') | call append(line("'<")-1, '')<CR>]])
```
- Use 'mini.basics' and its `go`/`gO` to insert blank line after/before current line.

I'll think about if there is a relatively simple way to add this to 'mini.surround'.

**Comment by echasnovski** [comment]
I've made several attempts to make it possible to write custom surrounding that would support this fully, but I don't think it is possible without changing 'mini.surround' code. The main problem is that for linewise selection left surrounding is applied to the [first non-blank character](https://github.com/echasnovski/mini.nvim/blob/a4241b6f51393d5e4d91a12d94e386bae287dae5/lua/mini/surround.lua#L1765-L1767). If it wasn't the case, then the following would work:

```lua
require('mini.surround').setup({
  custom_surroundings = {
    -- Use `<CR>` as surrounding identifier
    ['\r'] = { output = { left = '\n', right = '\n' } },
  },
})
```

Currently, it will affect the indentation of first selected line.

As present behavior of special handling of indent in linewise selection seems to be more universally applicable, I don't think this will be possible in 'mini.surround'. I'd suggest using my previous advice on custom mapping or combination of `go`/`gO` from 'mini.basics'.

**Comment by echasnovski** [comment]
One thing I noticed while revisiting adjacent functionality (in particular, #841 for 'mini.ai'), is that it is possible to do with `<C-j>` key which *indeed* represents new line character instead of `<CR>` / `'\r'` which is a carriage return. But that still won't have good support for indentation.

**Comment by palb91** [comment]
After looking at the source (thanks for your well written code!), I found a partial solution/workaround:

```lua
require('mini.surround').setup({
  custom_surroundings = {
    ['\r'] = {
      output = function()
        local indent = vim.api.nvim_get_current_line():match('^(%s*)')
        return { left = '\n' .. indent, right = '\n' }
      end
    },
  },
})
```

Surrounding a whole line with `<CR>` will work fine (and it's my only use-case).

However, the line before will always have the indentation, and I don't know if I can get rid of this with the current settings. I tried to replace the whole line with the same without indent, before returning `{ left, right }`, and it does funny but irrelevant things.

So, with '·' representing the space indentation, the following line:

```
····Hello world!
```

would become
```
····                <- Indentation only
····Hello world!    <- Text keeping its indentation
                    <- Empty line
```

**Comment by echasnovski** [comment]
> However, the line before will always have the indentation, and I don't know if I can get rid of this with the current settings. I tried to replace the whole line with the same without indent, before returning `{ left, right }`, and it does funny but irrelevant things.

Yes, indeed, modifying the text inside those functions is not something with a guarantee to work with 'mini.surround'. The behavior of ignoring leading/trailing whitespace of a linewise selection is (I think) a more common outcome than always putting on the first/last column.

What I [recently realized](https://github.com/echasnovski/mini.nvim/issues/1898#issuecomment-3089276534) is that the best way to have this working is probably to force charwise selection instead of linewise. So for example to surrounding current line with empty lines: `0v$` - `sa` - `<C-j>`. If this is a common occurrence, creating custom charwise textobjects might be a worthwhile.

---

That said, I now wonder if it might be better to drop this whitespace adjustment for the surrounding that contains/starts/ends with a newline. Specifically for these multiline surrounding cases. I'll think about it.

**Comment by palb91** [comment]
> What I [recently realized](https://github.com/echasnovski/mini.nvim/issues/1898#issuecomment-3089276534) is that the best way to have this working is probably to force charwise selection instead of linewise. So for example to surrounding current line with empty lines: `0v$` - `sa` - `<C-j>`. If this is a common occurrence, creating custom charwise textobjects might be a worthwhile.

At first I was replying to this more recent issue, but it was for a specific markdown use case, I thought my answer would better fit here.

That said, I'm glad I did it because you explained what you said in the other thread a bit differently and I understand it now ^^

I had a keymap `ss` to `sa_`, and now I see the main difference with your example, `sa_` takes the line from the first non-space character.

Rebinding `ss` to your suggestion `0v$sa` works perfectly, and I kept `['\r'] = { output = { left = '\n', right = '\n' } }` to use `Return` intsead of `C-j` which is… less natural.
