### ISSUE TITLE
[mini.animate] it prevents to scroll (focused) window with mouse

### ISSUE THREAD

**Issue by JonatasAmaral** [echasnovski/mini.nvim#334]
Hey, that is best neovim plugin i've found to animate scrolling (i'm using it standalone).
Works out-of-the-box, including to "gg" long file, without taking "capturing" nvim for minutes.

But it prevents me from scrolling the focused window with the mouse.
Moving cursor just a bit if scrolling in really small steps.
If the window if not focused, it scrolls normally.

I've tested that disabling "scroll" on config allow scroll with mouse, no other option (cursor, resize, etc) seems to interfere with that.

Trying remap scrolls to movements, is kind of better than nothing, but not as responsive as the default scroll behavior (and can go strange on non-text buffers, like tree view and terminal):
`3<C-e>` / `3<C-y>` - looks to be the spectated behavior of the scroll, but ends behaving the same as the plugin
`j` / `k` - scrolls smoothly on normal mode, but may mess up with other, like registers

---
_sidenote:
ok, i know, [n]vim -> "mouse less"
But using a laptop, slid thumbs has sometimes a better ratio of speed/precision.
So not a habit i willing to drop just yet_

**Comment by echasnovski** [comment]
Thanks for the issue.

> But it prevents me from scrolling the focused window with the mouse.

Could you, please, elaborate on this? Due to how Neovim works, every mouse wheel turn is a separate animation. So if you turn wheel to frequently, it tries to initiate animation every time which might contradict each other. Here is [the relevant part in help](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-animate.txt#L275).

[Here](https://github.com/echasnovski/mini.nvim/issues/177#issuecomment-1363816701) are some more insight from my point of view and [here](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/ui/mini-animate.lua#L6) is how Folke resolves this. I personally set `vim.o.mousescroll  = 'ver:25,hor:6'` and prefer to turn mouse wheel one at a time.

**Comment by echasnovski** [comment]
@JonatasAmaral, have you tried suggested solutions?

**Comment by JonatasAmaral** [comment]
> @JonatasAmaral, have you tried suggested solutions?

Sorry, i've missed your answer (that one was fast), Github just notified me about this second.

So i've tested LazyVim (tanks to `$NVIM_APPNAME`), and that works really well, just as i was expecting.
So made some minor adaptations to work for mine (still using Packer on main config), and now it's going great.

I didn't even tried out setting `vim.o.mousescroll`, as i thing would mess with the current experience anyways, and as that LazyVim's config worked just fine, didn't need to.


thanks for your help @echasnovski !

**Comment by echasnovski** [comment]
Great! Closing then.
