### ISSUE TITLE
Configuration breaks MiniJump2d.builtin_opts.single_char

### ISSUE THREAD

**Issue by tssm** [echasnovski/mini.nvim#354]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Jump2d

### Description

Hey, I'm trying to create custom mappings for `MiniJump2d.built_opts.single_character` but as soon as I change some options, it starts to behave weirdly: either it doesn't find spots, or it finds the wrong ones.

### Neovim version

0.9.1

### Steps to reproduce

1. `nvim -u NONE` 
2. `:lua require('mini.jump').setup()`
3. `:lua MiniJump2d.start(vim.tbl_deep_extend("force", MiniJump2d.builtin_opts.single_char, {allowed_lines = {cursor_before = false}}))`
4. Type a character

### Actual behavior

If you try it a couple of times, it will stop finding the right character, or the message "(mini.jump2d) No spots to show" will appear. Note that both `word_start` and `line_start` work as expected.

I'm using the `main` branch, BTW

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, at the moment `builtin_opts.single_character` depends on being the same table. It is because internally it operates by [using `hooks.before_start`](https://github.com/echasnovski/mini.nvim/blob/b1a6d9692e2f67ee35f77792b61eb7d44651c535/lua/mini/jump2d.lua#L543-L553) to define its `spotter` and definition is done in that **exact** table.

There are two solutions to this problem:
- If you intend to use `single_character` only with one set of settings, you can override it like so:
    ```lua
    _G.jump2d_single_char = require('mini.jump2d').builtin_opts.single_character
    _G.jump2d_single_char.allowed_lines.cursor_before = false
    ```
    And then use it as `:lua MiniJump2d.start(_G.jump2d_single_char)`.
- Implement it explicitly (albeit losing some notification functionality):

   ```lua
    _G.my_jump2d_single_char = {
      spotter = function() return {} end,
      allowed_lines = { blank = false, fold = false, cursor_before = false },
    }
    _G.my_jump2d_single_char.hooks = {
      before_start = function()
        local pattern = vim.pesc(vim.fn.getcharstr())
        _G.my_jump2d_single_char.spotter = MiniJump2d.gen_pattern_spotter(pattern)
      end,
    }
   ```

   And then use it as `:lua MiniJump2d.start(_G.my_jump2d_single_char)`.

To fully allow that, every element of `builtin_opts` should be configurable, but I don't I will happen as it will be a breaking change.

I might consider moving everything to a callable `gen_opts` to be more aligned with other modules, though.

**Comment by echasnovski** [comment]
I've created #355 to track this, but it is not high on my priority list right now. Maybe slightly after next version release.

**Comment by tssm** [comment]
No problem! Thanks for considering it anyway 🙂 I'll follow one of your suggestions to implement what I want, neither seems too complicated
