### ISSUE TITLE
mini.notify: module to display lsp (and other) messages, etc.

### ISSUE THREAD

**Issue by gegoune** [echasnovski/mini.nvim#359]
Did you consider such module? Would be even better if it provided very minimal version of noice to get rid of Press enter to continue messages. :)

**Comment by echasnovski** [comment]
Yes, I have considered it. It is vaguely planned, but not in the near future. Mostly because there still seems to be many hacks needed for this to comfortably work.

**Comment by clason** [comment]
To be clear: LSP progress messages should be fine; the API for that is now official and documented. What's not fine is general notifications, since Neovim lacks the possibility of annotating messages so you have to rely on heuristics or extensive user configuration to decide what should be shown as a transient notification and what should be a persistent message. (Also vaguely planned, but not in the near future.)

I personally would be interested in a progress notifier alone; but I'm not sure whether you wouldn't consider this too niche to warrant a mini.plugin.

**Comment by gegoune** [comment]
I did mainly mean notification module indeed. 

No more prompt is a pipe dream for now. :)

**Comment by leaxoy** [comment]
Is there a way to place popup window in the center of editor? Placed in the four corners on a big screen would be a distraction.

**Comment by echasnovski** [comment]
There is now (finally) a 'mini.notify' module released. Thanks for the idea, @gegoune! And specially for you, @clason, it includes LSP progress which is set up by default.

Closing this issue in favor of #640.
