### ISSUE TITLE
mini.comment: support for block comments

### ISSUE THREAD

**Issue by msva** [echasnovski/mini.nvim#363]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

Hi there! Would it be possible to implement block commenting, please?
I mean, for now, when you select some lines in visual mode, and press `gc`, all of them goes sommented by single line commentstring on each of that line.

But, for example, in https://github.com/numToStr/Comment.nvim you can type `gb` and comment the whole block with block comments, if it is supported (say, `--[[...]]` for Lua, and `/*...*/` for C++, and so on).

// By the way, interesting thing: I tried to look in `commentstring` and `comments` while tested both `mini.commentstring` and `Comment` on Lua files, and there was only `--` mentioned there, but somehow it anyway supports block commentaries syntax :shrug:

**Comment by echasnovski** [comment]
> Hi there!

Hello! Thanks for your interest in 'mini.comment'!

> Would it be possible to implement block commenting, please? I mean, for now, when you select some lines in visual mode, and press `gc`, all of them goes sommented by single line commentstring on each of that line.
> 
> But, for example, in https://github.com/numToStr/Comment.nvim you can type `gb` and comment the whole block with block comments, if it is supported (say, `--[[...]]` for Lua, and `/*...*/` for C++, and so on).

Sorry, no. For at least these reasons:
- There is no Neovim's built-in option which would provide information about appropriate block comment structure. Like 'commentstring' is for per-line comments.
- Whole code base of 'mini.comment' is designed for per-line commenting. Adding block comment would mean its complete rewrite, which I don't find necessary yet.

> // By the way, interesting thing: I tried to look in `commentstring` and `comments` while tested both `mini.commentstring` and `Comment` on Lua files, and there was only `--` mentioned there, but somehow it anyway supports block commentaries syntax shrug

This is because 'numToStr/Comment.nvim' [manually stores comment structure for supported filetypes](https://github.com/numToStr/Comment.nvim/blob/c8043290f2d77f61025494d839d88e414608c460/lua/Comment/ft.lua#L16) and *exactly* what is out of scope for 'mini.comment'.

**Comment by msva** [comment]
Thanks for reply, but:

> There is no Neovim's built-in option which would provide information about appropriate block comment structure. Like 'commentstring' is for per-line comments.

Isn't https://neovim.io/doc/user/options.html#'comments' is a thing for providing such info?
Although, I'm not sure what mechanisms are filling it :shrug:

**Comment by echasnovski** [comment]
> Isn't https://neovim.io/doc/user/options.html#'comments' is a thing for providing such info?
> Although, I'm not sure what mechanisms are filling it shrug

Not exactly. 'comments' is not a definitive source of block comment format, more like a collection of line parts that need to adjust formatting in already present comments. Besides, it doesn't always provide single multiline format, which might be confusing.
