### ISSUE TITLE
mini.bufremove Set dummy file type

### ISSUE THREAD

**Issue by franroa** [echasnovski/mini.nvim#372]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bufremove

### Description

Hi, it would be nice to be able to add autocomands on the bufremove created buffers.
As for now, when I try to add some functions in an empty filetype, it has an impact on other parts of neovim, so it would really nice to explicitly set a pattern on this file.

Thank you!

**Comment by echasnovski** [comment]
Hello!

Sorry, but I completely don't understand what you are asking for.

'mini.bufremove' doesn't create any buffers. Quite the opposite.

Which "file" do you mean in "...it would really nice to explicitly set a pattern on this file"?

**Comment by franroa** [comment]
Hi! Thank you for the quick answer.
I was thinking if it would be possible to access the winbar remaining after having removed the buffers. In that sense, I was thinking about an option of creating a dummy file when no more buffers are left on my window layout.

What I was trying to achieve is to customize the window bar after all buffers are removed. I would need a way of explicitly get an event on winenter/bufenter when all the buffers are removed, a way of setting a pattern on that event for that concrete window

Thank you!

**Comment by echasnovski** [comment]
> I was thinking if it would be possible to access the winbar remaining after having removed the buffers. In that sense, I was thinking about an option of creating a dummy file when no more buffers are left on my window layout.

There is always some buffer present as long as Neovim is showing some window. As `:h windows-intro` says: "A window is a viewport on a buffer.". So as long as there is window ('winbar' of which you want to customize), there is a buffer.

So yes, I stand corrected that 'mini.bufremove' does create a buffer if user wants to unshow the last buffer.
I don't think adding some special filetype to it is a good design, because the whole idea behind that buffer is to be a generic scratch buffer.

> What I was trying to achieve is to customize the window bar after all buffers are removed. I would need a way of explicitly get an event on winenter/bufenter when all the buffers are removed, a way of setting a pattern on that event for that concrete window

I would suggest one of at least these choices:
- Make your 'winbar' work on scratch buffers (ones with `vim.bo.buftype` equal to `'nofile'`).
- Make your 'winbar' explicitly count number of open (and possibly listed) buffers. See `:h nvim_list_bufs()` and `:h buflisted()`.
- Use `BufEnter` or `BufWinEnter` event to compute that number of buffers.

So with this in mind, unfortunately I don't think this suggestion will end up in 'mini.bufremove'.

**Comment by franroa** [comment]
Hi, thanks for the info. I will try your suggestions.

My problem with nofile is that it matches other things, but I haven't tried the other things.

Thank you so much!
