### ISSUE TITLE
mini.surround: proper vim grammar semantics for specifying count

### ISSUE THREAD

**Issue by mehalter** [echasnovski/mini.nvim#376]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

I have really wanted to move to `mini.surround` for a while especially to have a solidly built, Lua based surround plugin. The only thing missing that is keeping me back from switching over is a proper implementation of the semantics surround count as it pertains to the vim grammar.

In the grammar of a vim command you have `[count1][operator][count2][object]` as the basic structure and `count1` and `count2` are not necessarily equal. As  in, there is a difference semantically between `3dw` and `d3w`. The first says "3 times, delete 1 word" and the second says "1 time, delete 3 words". So if you combine them `3d3w` is saying "3 times delete 3 words" which in a lot of cases like deleting is equivalent to `9dw` or `d9w`, but semantically they are different operations and are handled inside of vim in a different way.

When it comes to doing surround operations `count1` should apply to the `operator` and `count2` should apply to the `object`. This is not how it's currently implemented in `mini.surround` where `2saw(` converts `foo bar` to `(foo bar)` so it is applying the 2 to the text object and not the operator. In the vim grammar this is actually saying "2 times, add a surround around 1 word", so it should be `2saw((` and convert `foo bar` to `((foo)) bar`.

With this structure you also are able to express stuff much more complicated something like `3sa2w([{` would convert `foo bar` to `{[(foo bar)]}`.

This would be a super killer feature and would make `mini.surround` the first Lua based surround plugin to implement the semantics of their commands in proper alignment with vim methodology.

**References**

- `vim-sandwich` documentation on how count works in their operators: https://github.com/machakann/vim-sandwich/blob/master/doc/operator-sandwich.txt#L142-L164
- Very good blog post covering Vim Grammar and the structuring of commands with operations/motions/objects and also covers how counts work with these: https://takac.github.io/2013/01/30/vim-grammar/

**Comment by echasnovski** [comment]
Thanks for such a detailed feature request!

I remember trying to make it work this way but got nowhere because of some technical limitation of how `count` information is provided (for example, `vim.v.count1` only provides multiplication of those two counts, as per `:h v:count`). But if 'vim-sandwich' has it working, I'll look into that.

------

> With this structure you also are able to express stuff much more complicated something like `3sa2w([{` would convert `foo bar` to `{[(foo bar)]}`.

This, almost certainly, won't be the case. It *will* require much refactoring for only a slight gain of functionality. This particular use case is better resolved with "user prompt" `?` surrounding: `sa2w?` followed by `([{<CR>}])<CR>`.

**Comment by mehalter** [comment]
This is incredible, thank you so much @echasnovski !

**Comment by echasnovski** [comment]
Soo...

I did try to add support for this and almost gave up. Mostly because the following is not the case:

> So if you combine them 3d3w is saying "3 times delete 3 words" which in a lot of cases like deleting is equivalent to 9dw or d9w, but semantically they are different operations and are handled inside of vim in a different way.

I knew that from plugin author point of view they are the same because `:h v:count` says so. But after discovering `:h motion-count-multiplied`, it seems that `3d3w` **is** the same as `9dw` or `d9w`.

The main problem was that I couldn't find a way to "reset" `v:count` after obtaining `[count1]` in `[count1][operator][count2][textobject/motion]` which matters because Neovim has to place marks according to `[count2]` and not `[count1] * [count2]`. This is where I started writing why this won't be supported, but decided to give it one last go.

And it was successful. `v:count` is reset if another command is executed which is a problem in itself, because this is not exactly allowed in Operator-pending mode (where it is needed here). So I came up with [this black magic hackery](https://github.com/echasnovski/mini.nvim/blob/a2bafb341894044e887e209fc013bf955371f9ae/lua/mini/surround.lua#L1224) which almost didn't break anything. There were slight hiccups afterwards (proper clearing cache and dot-repeat support), but seems to work nicely. Not sure if flawlessly, but nicely.

@mehalter, thanks for the push and interesting hacking problem! If you find anything which don't work in this use case, let me know.

(Side note: looking at 'vim-sandwich' code did nothing for me, as it seems to handle `[count]` completely by itself without relying on Vim's built-in ways)
