### ISSUE TITLE
mini.files: custom delete command

### ISSUE THREAD

**Issue by nat-418** [echasnovski/mini.nvim#431]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I would like to be able to set an option like this:

```lua
options = {
  delete_command = "trash"
}
```

So that I can use `trash` to send files to my system trashcan.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

'mini.files' has its own way of "move to trash" instead of "permanent delete". Set `config.options.permanent_delete = false` and it will move files to a special directory (not trash). See [here](https://github.com/echasnovski/mini.nvim/blob/ddb435633319d06a466c74833ef340839b931bfe/doc/mini-files.txt#L593-L597) for more details.

The reasoning for not supporting trash is outlined in #390. Basically: too complex to do it right and cross-platform.
