### ISSUE TITLE
Mini.animate prevent showing next diagnostic 

### ISSUE THREAD

**Issue by XXiaoA** [echasnovski/mini.nvim#438]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

when we use `:lua vim.diagnostic.goto_next()` to show the details of next diagnostic which is far from the cursor,  we have possibility to miss the show of it.

### Neovim version

nightly

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. run `:lua vim.diagnostic.goto_next()` move to a diagnostic in a distance

### Expected behavior

move cursor then show details of diagnostic 

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/62557596/c9338826-0b3e-40f3-bc93-29123a841f50

**Comment by echasnovski** [comment]
Thanks for the issue.

This is [kind of expected](https://github.com/echasnovski/mini.nvim/blob/654c723046d8f06151c7e940819c66030df011e7/doc/mini-animate.txt#L38-L43) since 'scroll' animation directly affects Neovim state (window view in this case). So what actually happens is that `vim.diagnostic.goto_next()` is executed and window is shown (or scheduled to be shown, not sure) but 'mini.animate' moves view back to the beginning and starts animation. The latter closes diagnostic window and it is not opened again.

The [suggested approach](https://github.com/echasnovski/mini.nvim/blob/654c723046d8f06151c7e940819c66030df011e7/doc/mini-animate.txt#L285-L291) to mitigate this is to use [`execute_after()`](https://github.com/echasnovski/mini.nvim/blob/654c723046d8f06151c7e940819c66030df011e7/doc/mini-animate.txt#L456). Something like this:
```lua
_G.diagnostic_goto = function(direction)
  vim.diagnostic['goto_' .. direction]()
  MiniAnimate.execute_after('scroll', function() vim.defer_fn(vim.diagnostic.open_float, 5) end)
end
```
Then execute like `lua _G.diagnostic_goto('next')`.

Closing as a documented issue with workaround.
