### ISSUE TITLE
Smart diagnostic levels

### ISSUE THREAD

**Issue by premell** [echasnovski/mini.nvim#459]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Bracketed

### Description

Right now you can just use descrete diagnostic levels like 'warning' or 'error'. It would be great to have a smart option that prioritized errors, then if the file doesnt contain any errors goes for warnings. 

Whenever i use goto diagnostics in a file with an error i have to go through many warnings until i get there. However if I set the severity level to "Error", I can no longer go to warnings. I think this smart option to prioritize errors would be a great middle ground

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think this is a good fit for 'mini.bracketed' mostly because it goes against how diagnostic navigation is done in built-in `vim.diagnostic.goto_{next,prev}()`. The `vim.diagnostic.goto_{next,prev}_pos()` functions are used directly in `diagnostic` target. Implementing custom logic would mean complicating code.

In this situation I would suggest to make different extra mappings to jump to a specific level entry. Maybe something like `]e` to jump to next error, etc.

Closing as not planned.
