### ISSUE TITLE
 Beta-testing 'mini.indentscope'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#46]
Please leave your feedback about new 'mini.doc' module here. Feel free to either add new comment or positively upvote existing one.

Some things that I am interested to find out (obviously, besides bugs):
- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation clear enough?

**Comment by xigoi** [comment]
Beautiful! I've wanted something like this!

I don't like that it's animated by default. IMO, it goes against the spirit of Vim where everything happens as fast as possible. But it's easy to turn off the animation, so it's not that much of a problem.

**Comment by echasnovski** [comment]
Yeah, I've had this exact thought today just before the release. I just really like the animation outcome and how I got there implementation-wise. And technically, it does happen as fast as possible, because it is non-blocking :)

**Comment by hunleyd** [comment]
this looks really cool. when's the next release? :)

**Comment by levouh** [comment]
Turning this into a toggle-able command would not be super useful, right? Its basically the same thing as `:set cursorline` at that point, with some goodies like text objects, cool animations, and whatnot.

**Comment by echasnovski** [comment]
> Turning this into a toggle-able command would not be super useful, right? Its basically the same thing as `:set cursorline` at that point, with some goodies like text objects, cool animations, and whatnot.

Not sure, what exactly you mean here.

Some possibilities:
- There are `vim.{g,b}.miniindentscope_disable` to enable/disable/toggle automated visualization. Toggle here is done with `:lua vim.g.miniindentscope_disable = not vim.g.miniindentscope_disable`.
- There are `MiniIndentscope.draw()` and `MiniIndentscope.undraw()` for manual drawing and undrawing of visual indicator. There is no `draw_toggle()` or exported indicator of drawing status to manually implement "perfect" `draw_toggle()`, but it might be done using variables from previous bullet and/or setting `draw.delay` to a very large value. Didn't do it, because it wasn't the main point of this module, but not opposed to it. If you describe your intended usage, we can work something out.

**Comment by HighRune** [comment]
The combination of text-object + vizualisation is perfect and allowed me to ditch indent-blankline, vim-indent-object and vim-indentwise since I don't use all their features.

**Comment by lcrockett** [comment]
A few ideas:

1) A toggle (to ensure opt-in) to show either the current indent, or, the current indent and all 'upstream | higher' indents up until the first one
2) Ensuring the current toggling of this module `vim.{g,b}.miniindentscope_disable` would actually render instantly instead of rendering only when the cursor is moved. This will ensure `autocommands` that use `BufLeave,FocusLost,WinLeave`, or `Bufenter,FocusGained,WinEnter` will work as expected
3) Using `Yggdroot/indentLine` in combination with this module seems to have this module overlay lines over Yggdroot's lines. It would be nice if the two could be combined, however not sure if this is possible as I didn't come across any sign of using `extmark` in `Yggdroot/indentLine`, so a priority change would not easily fix this. Might be redundant if point 1 is taken into consideration

Seems to work well so far, cheers !

**Comment by echasnovski** [comment]
Thank you all for beta-testing 'mini.indentscope'! I made new release (hey, @hunleyd), so it is now not in beta any more.
