### ISSUE TITLE
mini.ai: tag selection breaks when tag contains an underscore

### ISSUE THREAD

**Issue by abeldekat** [echasnovski/mini.nvim#474]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

When the tags in an xml file contain underscores, the selection is not correct.

### Neovim version

0.9.2

### Steps to reproduce

1. Open an xml file, containing the following line: `<first_name>First Name</first_name>`
2. Move the cursor to any position inside the `<first_name>` tag 
3. Press `vit`

### Expected behavior

The text between the pair of tags gets selected: `First Name`

### Actual behavior

Error message:
`(mini.ai) No textobject "it" found covering region within 500 lines and `search_method = 'cover_or_next'`.`

**Comment by echasnovski** [comment]
Thanks for the issue!

Tag textobject has obvious limitations in 'mini.ai' due to it using Lua pattern matching by default. The current implementation [does recognize only alphanumeric characters in tag name](https://github.com/echasnovski/mini.nvim/blob/f158f1905286e023d5848ab0b335a1cf5b8c692a/lua/mini/ai.lua#L1082). You can modify in `setup()` call as [it is suggested in this comment](https://github.com/echasnovski/mini.nvim/issues/314#issuecomment-1529097699) (it will recognize alphanumeric and punctuation as tag name):

```lua
require('mini.ai').setup({
  custom_textobjects = {
    t = { '<([%p%w]-)%f[^<%w][^<>]->.-</%1>', '^<.->().*()</[^/]->$' }
  }
})
```

------

However, specifically for tags a more sustainable and robust approach would be to use tree-sitter parsing and textobjects based on queries from 'nvim-treesitter-textobject': create 'after/ftplugin/html.lua' file and define `vim.b.miniai_config` buffer local variable there:

```lua
local spec_treesitter = require('mini.ai').gen_spec.treesitter
vim.b.miniai_config = {
  custom_textobjects = {
    t = spec_treesitter({ a = '@function.outer', i = '@function.inner' }),
  },
}
```

It will be more accurate but won't work inside comments and strings, though.

**Comment by abeldekat** [comment]
Hello @echasnovski,

Thanks for the feedback!
I tried your second suggestion, using spec_treesitter. However, mini.ai still reports the error, and I cannot figure out why.

A minimal config to reproduce can be found [here](https://github.com/abeldekat/test_mini_ai).
It includes file `test_failed.xml`.

**Comment by echasnovski** [comment]
> Hello @echasnovski,
> 
> Thanks for the feedback! I tried your second suggestion, using spec_treesitter. However, mini.ai still reports the error, and I cannot figure out why.
> 
> A minimal config to reproduce can be found [here](https://github.com/abeldekat/test_mini_ai). It includes file `test_failed.xml`.

I think you are the first one to actually create a minimal repo instead of saying "it doesn't work for me locally". That is a very nice move! As a gratitude for this next-level reproducible example, take a look at abeldekat/test_mini_ai#1.

**Comment by abeldekat** [comment]
Haha! You're welcome, @echasnovski. You are the first one to create an issue in my personal repo. I'll keep it around for a while...)

I was already wondering why in issue [110](https://github.com/echasnovski/mini.nvim/issues/110) the solution was [reported](https://github.com/echasnovski/mini.nvim/issues/110#issuecomment-1212271855) to work for the `html` filetype...

That said, I don't think I am the right person to offer a good PR to the `nvim-treesitter-textobjects` plugin.
I have no in-depth knowledge regarding the plugin and `treesitter`'s query syntax.

If you don't mind, I'll update the corresponding issue in [LazyVim](https://github.com/LazyVim/LazyVim/issues/1413), mentioning the [PR](https://github.com/abeldekat/test_mini_ai/pull/1#issue-1888832212) you created.

**Comment by echasnovski** [comment]
> That said, I don't think I am the right person to offer a good PR to the `nvim-treesitter-textobjects` plugin.
> I have no in-depth knowledge regarding the plugin and `treesitter`'s query syntax.

If you indulge a small inspirational talk, then I'd like to point out that no one has as in-depth knowledge about tree-sitter queries without trying. Most of those queries are results of actual language users being persistent enough to sit and try to "fake it till you make it". Looking at other queries, reading a bit about how they work in general (I started [here](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax)) and playing with them interactively (like with Neovim's built-in `:InspectTree` and `:PreviewQuery` in latest Nightly) goes a long way. Otherwise, if nobody is invested enough, chances are that it won't be done at all.

**Comment by echasnovski** [comment]
> You are the first one to create an issue in my personal repo. I'll keep it around for a while...)

Oh, but I would like to ask for this PR to eventually (not in the far distant future) be either merged or closed. Don't really like having dangling PRs :)

**Comment by abeldekat** [comment]
Thanks for the inspirational talk! I can certainly try.
I closed your PR.

**Comment by abeldekat** [comment]
Hello @echasnovski,

You already wrote that the `tree-sitter` approach does not work inside comments and strings. Up until recently, I did not fully grasp the consequences of this limitation.

As `xml` is quite commonly used in other languages to manipulate data, I don't think this alternative is a solution to the problem.

I hope someone else is able to submit a PR adding the `xml queries` to plugin `nvim-treesitter-textobjects`. 

Thanks for your patience and encouragement in this conversation, and also for all the wonderful plugins you write!
