### ISSUE TITLE
mini.starter: EndOfBuffer highlight differs with some colorscheme.

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#480]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

With certain colorschemes, EndOfBuffer may have a different background highlight compared to starter initial background, which disrupts overall visual consistency. 

### Neovim version

NVIM v0.10.0-dev+1102-geecddd241

### Steps to reproduce

With lazy:

```lua
return {
  [[sainnhe/everforest]],
  init = function()
    vim.g.everforest_background = [[hard]]
    vim.g.everforest_dim_inactive_windows = 1
  end
}
```

### Expected behavior

Preserve current EndOfBuffer background highlight, overwrite it when displaying starter, and revert to its original state when exiting

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/b0bd5389-d5b1-44ef-b191-eef4f45ddbe7)

**Comment by echasnovski** [comment]
I can not reproduce it with neither 'sainnhe/everforest' nor with 'mini.nvim's 'randomhue'. Besides, 'mini.starter' doesn't use `EndOfBuffer` in any way. It has all the signs of being some kind of misconfiguration issue.

**Comment by echasnovski** [comment]
> > @echasnovski Here's a minimal configuration you can reproduce with:
> > [nvim.zip](https://github.com/echasnovski/mini.nvim/files/12641407/nvim.zip)
> 
> @echasnovski In brief, the problem can be summarized as follows: mini.starter does not provide padding below, so if window size exceeds the information displayed by starter, endofbuffer takes over - with most colorschemes, this isn't a problem as they typically ensure that eob shares both foreground and background colors with "Normal" - but there are still some instances where this may not hold true

Yes, this is how 'EndOfBuffer' highlights works. And yes, I can reproduce this with your setup.

The problem here is that [`EndOfBuffer` has no background](https://github.com/sainnhe/everforest/blob/83b666410d7ae0eccf96dbbe3b4b6ac5b8172d38/colors/everforest.vim#L59) for any combination of settings. While in your setup it *has* explicit background. The output of `:hi EndOfBuffer` is `EndOfBuffer    xxx ctermfg=239 ctermbg=233 guifg=#495156 guibg=#1e2326`.

Without 'folke/lazy.nvim' using built-in package manager I can not reproduce this. Here are the steps:
- Put whole [sainnhe/everforest](https://github.com/sainnhe/everforest) and [mini.starter](https://github.com/echasnovski/mini.starter) in 'pack/plugins/opt' directory.
- Create the following 'init.lua':
```lua
vim.o.termguicolors = true

vim.g.everforest_background = [[hard]]
vim.g.everforest_dim_inactive_windows = 1
vim.cmd('packadd everforest')
vim.cmd('color everforest')

vim.cmd('packadd mini.starter')
require('mini.starter').setup()
```
- Open neovim with this config. I tested with `NVIM_APPNAME`.

I am not really sure what is going on here. Maybe 'folke/lazy.nvim' somehow affects the highlight groups, but quick searching its code base didn't reveal anything.
