### ISSUE TITLE
[files.mini]: Alternate modifid style.

### ISSUE THREAD

**Issue by A-Lamia** [echasnovski/mini.nvim#482]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

files.mini

### Description

Hey!,

Love files.mini but i have a small style issue where a personal plugin and a theme function i have is conflicting with the border highlights constantly being set, is it possible to disable that feature or add an alternate like text color difference or an alternate way to visual a changes.

Thank you!

NOTE: and after some though just disabling might be the simplest thing it would be very hard to represent a deleted file.

**Comment by echasnovski** [comment]
Hi! Thanks for the suggestion!

Unfortunately, I don't think adding this kind of customization aligns well with 'mini.files' design.

Closing as not planned.

------

On this note, what kind of issues do you have because of this? Maybe I can you with this?

'mini.files' changes border highlighting via 'winhighlight' window option. It doesn't modify existing highlight groups, so I can't think of a way it might interfere with theming.

**Comment by A-Lamia** [comment]
yeah that was the issue and it's fine, fine, it doesn't overwrite the whole winhighlight just highlights for floats :)
