### ISSUE TITLE
Expose more extmark options in hipatterns

### ISSUE THREAD

**Issue by cnrrobertson** [echasnovski/mini.nvim#504]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.hipatterns

### Description

Currently, there are a few tunable options for the highlights that are passed into the `vim.api.nvim_buf_set_extmarks` function ([here](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/hipatterns.lua#L775), [here](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/hipatterns.lua#L792), and [here](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/hipatterns.lua#L794)). There are actually a lot of possible options that could allow for highlighting the entire line, setting virtual text, or replacing/masking the text (list of options for extmarks [here](https://neovim.io/doc/user/api.html#nvim_buf_set_extmark())).

Would it be possible to expose this `extmark_opts` table to make these options accessible? The `priority` option is already available [here](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-hipatterns.txt#L178), so exposing all the options could be a simple as adding an `extmark_opts` config to `highlighters` with `priority` inside or as a separate table.

Happy to submit a PR if this seems a worthwhile feature.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is doable, of course. I vaguely remember considering it and for some reason decided not to add this. I'll revisit this later and see why this wasn't included in the first place.

**Comment by echasnovski** [comment]
After trying to replace `priority` with fully configurable `extmark_opts`, there are at least two problems with this approach:
- It is not quite "plug and play" in [the current code](https://github.com/echasnovski/mini.nvim/blob/e9a0716013abb8d2d6f8d77331600fb99eb15d51/lua/mini/hipatterns.lua#L775), as it would need `vim.deepcopy()` to be fully operational. Having one copy per highlighter application is not good but tolerable. However, allowing this `extmark_opts` to supply `end_row`, `end_col`, and `hl_group` would mean  to copy it on every pattern match, which is too much.
- Playing around with implementation prototype, I found that in order to be useful, `extmark_opts` computation would need to know at least the matched highlight group, which is known only after computation for every match. Which would mean `extmark_opts` would need to be table or function (similar to `group`) and be called on every match. This is, again, a performance issue.

I was hoping that simply allowing `extmark_opts` would also solve #340, but it doesn't seem like it. Right now I am leaning towards adding certain kind of extmark behaviors on case by case basis: like inline text or sign. @cnrrobertson, what other use cases did you have in mind when opening this?

**Comment by cnrrobertson** [comment]
Thanks for getting to this so quickly. I completely understand the performance concerns. Really my hope was mainly to use `hl_eol` but I could imagine also enjoying `hl_mode`, `virt_lines`, and `sign_text` as I think they fit nicely in the scope of `hipatterns`.

**Comment by echasnovski** [comment]
Oh, after sleeping on it, I decided to try to go through with it. I have a working solution which I'll revise tomorrow. It will have ability to supply both table and function as `extmark_opts`. It is just indeed provides many opportunities with a small change. And judging by the brief tests, performance should not take a huge hit.

I am not sure yet about deprecating `priority`, as it will be a breaking change though.

Do you have a particular use case for using `hl_eol` before I finalize design of `extmark_opts`? Because right now it can be used, but highlighting still starts at the start of the pattern match, so no way to highlight whole line containing some match.

**Comment by cnrrobertson** [comment]
Great! For my purposes, `hl_eol` is perfect as I'm always looking for matches at the start of the line.

Thanks again for putting this in so quickly.

**Comment by echasnovski** [comment]
This is a part of `main` branch.

Here is a dummy example of how to highlight whole line with a match at its start:

```lua
local zero_indent_extmark_opts = function(_, _, data)
  return { hl_group = 'Visual', end_row = data.line, end_col = 0, hl_eol = true, right_gravity = false }
end

require('mini.hipatterns').setup({
  highlighters = {
    zero_indent = { pattern = '^%S', group = '', extmark_opts = zero_indent_extmark_opts },
  }
})
```

Thanks for the push to make this! This ended up a nice increase in functionality.
