### ISSUE TITLE
Mini Pick grep_live hanging after about a Second

### ISSUE THREAD

**Issue by domsch1988** [echasnovski/mini.nvim#522]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini-pick

### Description

I'm trying to use grep_live on a decently sized Repository. 6000 or so files.
It starts off fine, working as intended, but within a few characters neovim entirely "hangs", won't accept input anymore and can only be forcably closed.

### Neovim version

0.9.2

### Steps to reproduce

I'm running a basically "mini only" nvim config. Lazy.nvim is used to pull mini, other than that, it's only settings for tabs, spaces and some indenting.
This is running on Windows 11 natively (no WSL or such). I can't really try to reproduce this on linux, as the Repo is work only and i don't have a work Linux machine kicking around.

### Expected behavior

grep_live should continue working.

### Actual behavior

Neovim entirely locks up and only killing the terminal solves this.

**Comment by echasnovski** [comment]
Thanks for the issue!

I kind of can reproduce this, but not quite. I am using [chromium/chromium](https://github.com/chromium/chromium) to do a `grep_live`. When pressing single `l` it does hang after a while with something like "E41: out of memory" error. And the issue seems to be that Neovim/libuv/'mini.pick' can't easily process the amount of matched lines. So `rg` works as it should and processing its output to stdout results into too big object.

I don't think I can do much here besides limiting the amount of matched items, which I don't really want to do. Instead caution users to not make many matches.

Just to be sure, could you clarify some things:
- Does plain `rg` work for you? Navigate to the repo and run the following command: 
```bash
rg --column --line-number --no-heading --hidden --no-follow --color=never --smart-case -- <enter your pattern>
```
   Does it finish and not get stuck?
- Does typing quickly until you get to a bigger version of a pattern work?

**Comment by Keyhart** [comment]
Since you mentioned that you're on Windows 11 and using WSL. I had a similar issue where typing in `grep_live` would lag or hang Neovim.

WSL has 2 versions. WSL1 and WSL2. WSL2 which I think installs by default on Windows 11 runs in a VM with a full Linux kernel and a network share to access the Windows file system. The downside is it has pretty terrible performance with the file system.
You can read more about it here: [Comparing WSL Versions](https://learn.microsoft.com/en-us/windows/wsl/compare-versions)

What worked for me was switching to WSL1 from WSL2. It improved my overall performance with `rg`, `fzf` and others.

You can see which version you're running in powershell: `wsl --list --verbose`
And to switch WSL versions you do: `wsl --set-version <Name> 1` where the number at the end is the version you want to switch to.

Do note that doing this might break some things within WSL. So far I haven't had any problems other than the system clipboard `clipboard=unnamedplus`. I use `win32yank` so the solution for that was to remove it from within WSL and place it in `$PATH` under Windows.

**Comment by Keyhart** [comment]
Oh my bad... I misread and thought you were on WSL.

**Comment by domsch1988** [comment]
> Does plain rg work for you? Navigate to the repo and run the following command:

Yes. And it does with a high number of matches. Let's say i want to search for "company_apt_cacher" in my repo. git_live usually hangs after "company", which seems like around the time first matches are shown. plain rg in Terminal can find matches for just "company" fine though.
grep_live also works with less common search terms.

Another "Idea": Part of the repo is a git lfs store. So there are some bigger files in there, and some binaries. Maybe those are an issue. I might configure rg to ignore a bunch of folders and filetypes. I never need to match anything in those folders anyways. They are just part of the repo, but not needed for coding.

> Does typing quickly until you get to a bigger version of a pattern work?

No. But it might be that i'm not typing fast enough

For now MiniPicker.builtin.grep() works for me to get my whole searchterm in. As long as it doesn't match a bajillion things, this is fine. Of note though: Putting just "company" into Mini Pick grep() opens the UI but shows no results and also crashes neovim.

**Comment by echasnovski** [comment]
Hmm... I'll think about this, but honestly not sure how to help here. I can reproduce *some* hang, but only on a much bigger repo (400K files against 6K).

Let's try to get some more information (in as much details as you can provide due to privacy stuff):
- How many files are there?
- What is the size of the repo inside which search is done (to get a rough idea of how many lines are being searched)?
- How many matches does plain `rg` in terminal show for the case that breaks `grep_live` (the "company" pattern, I believe)? Please, make sure to use the command from [this comment](https://github.com/echasnovski/mini.nvim/issues/522#issuecomment-1764845220).
- How many matches does the working example have (the "company_apt_cacher" one)?

> Another "Idea": Part of the repo is a git lfs store. So there are some bigger files in there, and some binaries. Maybe those are an issue. I might configure rg to ignore a bunch of folders and filetypes. I never need to match anything in those folders anyways. They are just part of the repo, but not needed for coding.

By default `rg` ignores binary files, though. Maybe they are treated as *very long* string and processing this string leads to memory overuse?

**Comment by domsch1988** [comment]
> How many files are there?

git ls | wc -l shows 4351 files

> What is the size of the repo inside which search is done (to get a rough idea of how many lines are being searched)?

Our gitlab instace claims 6.8 GB Project Storage. du -sh say 7.5 GB

> How many matches does plain rg in terminal show

rg into wc -l says 4184 Matches

> How many matches does the working example have (the "company_apt_cacher" one)?

37

I have noticed a couple of 100MB plus SQL files. Adding a glob option to ripgrep's config to exclude all SQL files ( `--glob=!*.sql` ) seems to have fixed this entirely. I still get 3600 Matches, but everything is working fine for me now. It might be, that trying to preview these large files with maybe extremely long line causes the issue, and not the amount of matches. Excluding those SQL files is completely fine for me, as i never have to search in those.

**Comment by echasnovski** [comment]
Thanks for the detailed info!

Yes, having number of matches in the vicinity of 5000 should be totally fine and not crash. And yes, it does seem that for some reason `rg` tries to search inside those SQL files, finds match, and tries to preview long lines.

I would be really grateful if you could confirm this for sure. Could you add something like `--max-columns=100` to your ripgrep's config and try using `grep_live` with it available? Will it works and show "[Omitted long line with x matches]" instead of long lines? And are those lines indeed form SQL files?

**Comment by domsch1988** [comment]
Alright, can confirm this is the case:
![image](https://github.com/echasnovski/mini.nvim/assets/1961154/c995cf2a-1582-46a2-9303-1e7b9cdd0cac)
Though it seems like 100 isn't as high as would be usable. 100 filters a lot more files than just those SQL Files. I don't really care though, as file-name is good enough in 99.99% of cases for me. I'll leave the max-columns configuration, as it's more universally usable for me.
