### ISSUE TITLE
mini.clue will sometimes not capture postkeys

### ISSUE THREAD

**Issue by llllvvuu** [echasnovski/mini.nvim#571]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

A real-world example is with `dap.continue()`. Suppose we have `<leader>dc` postkeys `<leader>d`. When this command executes for the first time, it opens `vim.ui.select` to select the launch task. Then it types `<leader>d`, which is correct when `vim.ui.select` is not opened but incorrect when `vim.ui.select` is opened. Ideally if the `<leader>d` is not going to be caught by `mini.clue` it should not send it at all. In other words, the `postkeys` should only set the `mini.clue` prefix but not actually send the keys to Neovim.

### Neovim version

nightly a76f5f2ff

### Steps to reproduce

`<leader>12` will produce the issue with the following config (uncomment rtp lines to the appropriate directories):

```lua
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- vim.opt.rtp:prepend(vim.fn.stdpath("data") .. "/lazy/mini.clue")
-- vim.opt.rtp:prepend(vim.fn.stdpath("data") .. "/lazy/dressing.nvim")
require('mini.clue').setup({
  triggers = {
    { mode = 'n', keys = '<leader>' },
    { mode = 'x', keys = '<leader>' },
  },
  clues = {
    { mode = "n", keys = "<leader>12", postkeys = "<leader>1" },
  },
  window = { delay = 0 },
})
vim.keymap.set("n", "<leader>12", function() vim.ui.select({ 'a', 'b' }, {}, function() end) end)
```

### Expected behavior

No "1" inputted

### Actual behavior

"1" inputted

**Comment by echasnovski** [comment]
Thanks for the issue!

That is a tough one. The reason why postkeys are directly emulated as key presses [is because it is hard to force exact order they are executed otherwise](https://github.com/echasnovski/mini.nvim/blob/92e2ae609f612f11f7e8e45d13614fcdff9f89b9/lua/mini/clue.lua#L1414-L1416). I remember trying really hard to make it work so that postkeys are just registered inside 'mini.clue' key query process, but didn't find a way to do that.

The main problem here is `vim.ui.select()` itself. Its implementation usually relies on user sending selection keys to it, but 'mini.clue' itself expects to intercept it in order to advance the key query process. So even if the first `<Space>12` shows select input and `<Space>1` is not sent to the Neovim, the next `2` should be processed by the 'vim.ui.select()` and not 'mini.clue'. Otherwise it will send `<Space>12` to the Neovim while select window is still open (as it didn't receive any keys).

So at the moment I *think* that this use case just doesn't fit in the 'mini.clue' model. I'll revisit this some time later, but there doesn't seem to be a good solution here.

**Comment by echasnovski** [comment]
Yeah, I've thought about it, and it doesn't seem to be a proper solution to this. It is just that 'mini.clue' is not suited for this kind of "submodes".

Closing as not planned (but good to have, just there seems to be no way of doing it properly).
