### ISSUE TITLE
[surround] brackets replacing to change indents

### ISSUE THREAD

**Issue by kaiphat** [echasnovski/mini.nvim#594]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

surround

### Neovim version

0.9.4

### Steps to reproduce

I want to replace `{}` brackets to `[]`
<img width="617" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/53742299/785aad45-ce9e-46b8-b537-a30f93ecf2bd">

When i do replacing i get
<img width="617" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/53742299/c20c1711-5cfb-4e3d-9ae7-5cbe207f6a38">
As you can see bottom brackets and `userId` changed their positions.

### Expected behavior

Brackets shouldn't move when i do replacing

**Comment by echasnovski** [comment]
I presume replacement is done with `sr{]`. In this case it is an expected behavior, because [opening brackets include outer whitespace padding into them](https://github.com/echasnovski/mini.nvim/blob/964fab7fecd14f66a69a96162f8aa816480690fd/doc/mini-surround.txt#L29-L30). Try using `sr}]` to not include whitespace.
