### ISSUE TITLE
mini.surround latex operator?

### ISSUE THREAD

**Issue by lupont** [echasnovski/mini.nvim#6]
Hey! You've created such an awesome plugin, such nice looking code (and there's not that much of it!). It has replaced many of my previous plugins and I am loving it. :) I have a feature request, for the surround module:

Is there a possibility of adding a `latex` "object"? It would be similar to the `special_tag` one, but with `\begin{foo}` and `\end{foo}` as left and right, rather than `<foo>`/`</foo>`.

I would have made this a PR, but I've had such little time lately that I thought I'd ask your opinion first.

Thanks!

**Comment by echasnovski** [comment]
@lupont, @xigoi, sorry for the long delay. Didn't want to implement such big functionality without tests to check if nothing got broken. And in turn writing tests was a daunting task, so it took a while. But almost all modules are now covered with tests, including 'mini.surround'. So I decided to implement it right away.

The approach I decided to use is through [config.custom_surroundings](https://github.com/echasnovski/mini.nvim/blob/297993c40e93bd155d72424e3a1abeefb3be344e/doc/mini.txt#L3784) option. Both of your Latex related requests should be possible with the following setup:
```lua
require('mini.surround').setup({
  custom_surroundings = {
    S = {
      input = { [[\begin{(%w*)}.-\end{%1}]], [[^\begin{.-}().-()\end{.-}$]] },
      output = function()
        local latex_name = MiniSurround.user_input('Latex object name')
        return { left = ([[\begin{%s}]]):format(latex_name), right = ([[\end{%s}]]):format(latex_name) }
      end,
    },
    L = {
      input = { [[\%w+%b{}]], '^.-{().*()}$' },
      output = function()
        local cmd_name = MiniSurround.user_input('Latex command name')
        if cmd_name == nil then return nil end
        return { left = ([[\%s{]]):format(cmd_name), right = '}' }
      end,
    },
  },
})
```

Yes, a little bit complex, but that's the price for customization involving querying user for command name.

**Edit**: The setup was adjusted for `input` values to follow the since changed surrounding specification. The `\begin{}...\end{}` surrounding is also changed from `l` to `S` identifier because it conflicts with default ["find previous"](https://github.com/echasnovski/mini.nvim/blob/4035ef97407a6661ae9ff913ff980e271a658502/doc/mini-surround.txt#L512) suffixed variants (like `sdl`, `srl`, etc.). To use `l` as identifier make sure that `config.mappings.suffix_last` is not `'l'`.

**Comment by lupont** [comment]
Wow, awesome! I will be sure to try it out when I find some time. :) Thanks!

**Comment by benkj** [comment]
Thanks for this, awesome as usual. However I have some problems with both `l` and `L` above. It works flawlessly with `sa`, but not with `sd` or `sr`. Steps to reproduce what I'm saying.
1. Open a random tex file and select some text 
2. use `saLtextbf` to make the selection bold, this basically transforms `TEXT` to `\textbf{TEXT}`
3. move somewhere in `TEXT` and press `sdL` (or `srL`). 

I expected this to back from `\textbf{TEXT}` to `TEXT`, but rather it pops up `(mini.surround) Enter input surrounding identifier`, which is not what I expected, and even if I put something there I don't get the right behavior. Am I doing something wrong?

**Comment by echasnovski** [comment]
> I expected this to back from `\textbf{TEXT}` to `TEXT`, but rather it pops up `(mini.surround) Enter input surrounding identifier`, which is not what I expected, and even if I put something there I don't get the right behavior. Am I doing something wrong?

This looks like a mix of two issues here.

First one is that input surrounding specification has changed since that 3 year old comment. It is now a single [composed pattern](https://github.com/echasnovski/mini.nvim/blob/4035ef97407a6661ae9ff913ff980e271a658502/doc/mini-surround.txt#L253) (which is more powerful and flexible) instead of `find` and `extract` fields. Here is [an example](https://github.com/echasnovski/mini.nvim/blob/4035ef97407a6661ae9ff913ff980e271a658502/doc/mini-surround.txt#L289-L293). 

Second one is that you probably didn't press `<Shift>` and executed `sdl`. This is a ["delete previous"](https://github.com/echasnovski/mini.nvim/blob/4035ef97407a6661ae9ff913ff980e271a658502/doc/mini-surround.txt#L512) action by default which will prompt user to enter surrounding identifier (so that 'mini.surround' can delete the surrounding that is located before cursor and not covering it).

I updated the suggested setup with relevant notes. I seems to work now.

**Comment by benkj** [comment]
Thanks, I confirm that `sd` works now, while `sr` still does not work... it deletes the surround and then asks for `output identifier`. I had no conflict, the "previous" action is set to `p` in my config. 
Another small feature request: is it possible in the `L` example to have the `{}` characters in the word (I guess in %w? I'm not familiar with lua patterns)? I often have to revise documents where people add comments like 
`\textcolor{red}{THEIR PROPOSED CHANGE}` 
and I'd like to easily get rid of the `textcolor{red}` part... No big deal though if it is too complicated, I can run a first `:%s/textcolor{red}/whatever/g` and then `sdL` once I take care of the comment. Currently this doesn't work if I press `sdL` inside `\textcolor{red}{THEIR PROPOSED CHANGE}`

**Comment by echasnovski** [comment]
> Thanks, I confirm that `sd` works now, while `sr` still does not work... it deletes the surround and then asks for `output identifier`. I had no conflict, the "previous" action is set to `p` in my config.

This is how [replace action works](https://github.com/echasnovski/mini.nvim/blob/4035ef97407a6661ae9ff913ff980e271a658502/doc/mini-surround.txt#L77-L78): `sr` + `input identifier to replace` + `output identifier to replace with`. If you want to change the content of `{}`, then it will be something like `srLL` + <new content> + `<CR>`.

> Another small feature request: is it possible in the `L` example to have the `{}` characters in the word (I guess in %w? I'm not familiar with lua patterns)? I often have to revise documents where people add comments like
> `\textcolor{red}{THEIR PROPOSED CHANGE}`
> and I'd like to easily get rid of the `textcolor{red}` part... No big deal though if it is too complicated, I can run a first `:%s/textcolor{red}/whatever/g` and then `sdL` once I take care of the comment. Currently this doesn't work if I press `sdL` inside `\textcolor{red}{THEIR PROPOSED CHANGE}`

Sorry, I do not understand what is the intended outcome here. I only get that `\textcolor{red}{THEIR PROPOSED CHANGE}` is the starting point. Where do you want cursor to be placed and what is the target text you want to achieve?

**Comment by benkj** [comment]
> This is how [replace action works](https://github.com/echasnovski/mini.nvim/blob/4035ef97407a6661ae9ff913ff980e271a658502/doc/mini-surround.txt#L77-L78): `sr` + `input identifier to replace` + `output identifier to replace with`. If you want to change the content of `{}`, then it will be something like `srLL` + + `<CR>`.
> 
I see, this totally makes sense. Thanks!

> Sorry, I do not understand what is the intended outcome here. I only get that `\textcolor{red}{THEIR PROPOSED CHANGE}` is the starting point. Where do you want cursor to be placed and what is the target text you want to achieve?

Like the previous example, but with `textcolor{red}` instead of `textbf`. For example I start with `XXXX` and press `saLtextcolor{red}` to get 
`\textcolor{red}{XXXX}` (basically making a red XXXX). This already works with your code. However, if I put the cursor under a X and press `sdL` I don't go back to `XXXX`

**Comment by echasnovski** [comment]
> Like the previous example, but with `textcolor{red}` instead of `textbf`.

Ah, I see now, my bad. Yes, this should be possible with something like `input = { [[\%S+%b{}]], '^.*{().-()}$' }`. It recognizes any non-whitespace characters before balanced `{}`.

**Comment by benkj** [comment]
Thanks, now it is perfect
