### ISSUE TITLE
MiniPairs.unmap_buf not working

### ISSUE THREAD

**Issue by kflak** [echasnovski/mini.nvim#60]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

pairs

### Description

Hi, and thanks for a great plugin!

I am trying to get pairs to ignore ' for all my lisp-related files, and put this 
```
lua MiniPairs.unmap_buf(0, 'i', "'", "''")

``` 
into `after/ftplugin/sceme.vim`, but I get the error
```
E5108: Error executing lua ...nvim/site/pack/packer/start/mini.nvim/lua/mini/pairs.lua:211: E31: No such mapping
```

My config is very simple:
```        use {
            'echasnovski/mini.nvim',
            branch = 'stable',
            config = function()
                require'mini.pairs'.setup({
                    modes = { insert = true, command = true, terminal = true },
                })
            end
        }
```

It is very possible that I am just making a silly noob lua mistake, obviously, but I can't pinpoint what exactly that could be.

### Neovim version

0.6.1

### Steps to reproduce

1. `nvim -nu minimal.lua test.scm` with `minimal.lua` looking like this:
```
vim.cmd([[
augroup packer_user_config
autocmd!
autocmd BufWritePost plugins.lua source <afile> | PackerCompile
augroup end
]])

vim.cmd [[packadd packer.nvim]]
vim.cmd [[packadd termdebug]]
return require('packer').startup({
    function()
        use {
            'echasnovski/mini.nvim',
            branch = 'stable',
            config = function()
                require'mini.pairs'.setup({
                    modes = { insert = true, command = true, terminal = true },
                })
            end
        }
    end,
})
```
This gives the error described above, and typing ' gives ''

### Expected behavior

No error, typing ' does not trigger ''

### Actual behavior

Typing ' gives ''

**Comment by echasnovski** [comment]
Hi! Not a "silly noob lua mistake" at all. I fell into the same mistake when was writing tests for this module, but forgot to clarify this in documentation.

`MiniPairs.map_buf()` and `MiniPairs.unmap_buf()` are mere wrappers for `vim.api.nvim_buf_set_keymap()` and `vim.api.nvim_buf_del_keymap()` respectively which also unregister pair for `<CR>` and `<BS>` (so that they don't act on that pair). In turn, Neovim's `nvim_buf_del_keymap()` *deletes buffer-local mapping* and not *makes global mapping not work for buffer*. So in this sense, `MiniPairs.unmap_buf()` will delete mapping which was done with `MiniPairs.map_buf()` and not `MiniPairs.map()` (used in `MiniPairs.setup()`).

So in your case there are two solutions:
- *Easy one* is to make `'` work as by default but leave `<BS>` (and possibly `<CR>`) respect `''` pair: `inoremap <buffer> ' '`. So to do this for only Lisp files, add this Lua code: `vim.cmd([[au FileType lisp inoremap <buffer> ' ']])`.
- *Complicated one* is to also make `<BS>` and `<CR>` don't act on `''` pair:
    ```lua
  require('mini.pairs').setup({ modes = { insert = true, command = true, terminal = true } })
  MiniPairs.unmap('i', "'", "''")
  vim.cmd(
    [[au BufEnter * lua MiniPairs.map_buf(0, 'i', "'", { action = 'closeopen', pair = "''", neigh_pattern = '[^%a\\].', register = { cr = false } })]]
  )
  vim.cmd([[au FileType lisp lua MiniPairs.unmap_buf(0, 'i', "'", "''")]])
    ```
    This reverts global mapping from `setup()`, makes autocommands to make *buffer-local* mapping for every buffer and remove it when 'lisp' filetype is set.

**Comment by echasnovski** [comment]
This should be now clarified in help files. Thank for bringing this up!

**Comment by kflak** [comment]
Great, thanks for the quick reply! Going for the easy solution by putting this into my `autocommands.vimrc` which is sourced by `init.lua` (my final, remaining vimlang file...):
```
autocmd FileType lilypond,scheme,lisp inoremap <buffer> ' '
```
