### ISSUE TITLE
Mini.pick can't handle custom window border

### ISSUE THREAD

**Issue by Diablo-D3** [echasnovski/mini.nvim#608]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Pick

### Description

Using...

```lua
require('mini.pick').setup({
  window = {
    config = {
      border = {
        { 'x', 'Red' }, { 'x', 'Red' }, { 'x', 'Red' },
        ' ',
        { 'x', 'Red' }, { 'x', 'Red' }, { 'x', 'Red' },
        ' '
      }
    }
  }
})
```

... causes Pick to show no results and immediately exit on any key press.

### Neovim version

Git

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Setup mini.pick as above
3. `:lua require('mini.pick').builtin.files()`

### Actual behavior

See above

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce it. It is because there is an error during opening 'mini.pick' window and currently no error is shown due to how `getchar()` works (didn't manage to properly make it happen without a flicker).

The error is in how 'mini.pick' tries to be smart and infer bottom border characters. Right now it assumes that `border[6]` is a string, which is not the case in this issue.

I'll fix it (hopefully) shortly.

**Comment by echasnovski** [comment]
This should be fixed on latest `main`.
