### ISSUE TITLE
Custom `Q` mapping does not work

### ISSUE THREAD

**Issue by Mateiadrielrafael** [echasnovski/mini.nvim#619]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

Custom `Q` keymappings get removed by `mini.clue` it seems		

### Neovim version

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1693350652

### Steps to reproduce

- Set custom mapping for `Q` (I have it set to `:wqa<cr>`)
- Call `.setup` on `mini.clue` (you don't have to use any of the generated completions)
- The keybind no longer works

### Expected behavior

The keybind should keep working (I have the default `Q` behaviour bound to something else, as I wasn't using it super often)

### Actual behavior

The keybind does not work

**Comment by Mateiadrielrafael** [comment]
Hmm, I also wonder if there's a way to not close a clue window until `<Esc>` is pressed (this would be super useful for a lot of "submodes")

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, having `Q` mapping to properly mimic its default behavior for replaying last recorded register is the only way to make it work right now. And [it is documented](https://github.com/echasnovski/mini.nvim/blob/333d2d1090c80ac936b960469a6e93982cbaeb21/doc/mini-clue.txt#L93-L94).

I have made a PR to Neovim itself (neovim/neovim#24565) which if merged would allow to skip making those mappings.

Before this happens, my suggestion is to make custom `Q` mapping after calling `require('mini.clue').setup()`.

Closing as it is (currently) an expected behavior.

**Comment by echasnovski** [comment]
@prescientmoon, just FYI: as Neovim PR was not merged as fast as I hoped, I decided to alter the behavior of how 'mini.clue' creates `@` and `Q`. It will now won't create them if the key is already mapped. All other points from previous comment still stand, though.
