### ISSUE TITLE
mini.pairs: python f-strings

### ISSUE THREAD

**Issue by barrett-ruth** [echasnovski/mini.nvim#627]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pairs

### Description

Support auto pairs for quotes ("'", '"') when typing python f-strings.

### Neovim version

0.10.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Edit python file
3. Type the following characters: `print(f'`

### Expected behavior

The quote is autopaired after the f-string.

### Actual behavior

No auto-pairing is done.

**Comment by echasnovski** [comment]
In 'mini.pairs' the [neighborhood pattern](https://github.com/echasnovski/mini.nvim/blob/ea1af8c7d5e72148cae8a04e9887322a53fe66cf/doc/mini-pairs.txt#L137-L139) is responsible to decide when inserted character expands into full pair. By default, `'` [has it such](https://github.com/echasnovski/mini.nvim/blob/ea1af8c7d5e72148cae8a04e9887322a53fe66cf/doc/mini-pairs.txt#L121) that single `'` is inserted after any English letter (to be usable inside plain English text) and `\`. This part won't change.

The most straightforward approach to solve this issue is to update neighborhood pattern for `'` only in Python files. For that, create an 'after/ftplugin/python.lua' file inside your config directory and put there these lines:

```lua
if MiniPairs ~= nil then
  MiniPairs.map_buf(0, 'i', "'", { action = 'closeopen', pair = "''", neigh_pattern = '[^\\].' })
end
```

This will create only a buffer-local mapping which will insert single `'` only after `\`. The downside is that it will insert double `''` after any letter also.

Closing as not planned.

**Comment by barrett-ruth** [comment]
Thank you for the quick response. I'm assuming I'm able to alter the regex to ignore solely `f`?

**Comment by barrett-ruth** [comment]
For anyone looking, the above solution didn't work or wasn't satisfactory, so I added the following luasnip to my python files:
```lua
    s('f', fmt('print(f{}{}{})', { c(1, { t("'"), t('"') }), i(2), rep(1) })),
```
