### ISSUE TITLE
Flickering `(mini.starter) Query:` at startup

### ISSUE THREAD

**Issue by rgnkn** [echasnovski/mini.nvim#64]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

Maybe there's an option that already handles this which I couldn't find yet. If so, please, direct me to the answer / solution.

I use `mini.starter` and when I start vim the command line displays for a fraction of a second `(mini.starter) Query:`. It would be nice if there would be an option to disable this behavior altogether. 

This is obviously just a glitch and nothing with very high priority.

**Comment by echasnovski** [comment]
Thanks for report. Didn't need to ask for reproducible example, because it turned out I experience this in my setup too. Just didn't notice :)

However, the reason seems to be the lazy loading of some other plugin which cleans command line. If you try `nvim --clean -u minimal-starter.lua' which only loads 'mini.starter', the query does not disappear.

Do you suggest an option to completely remove all "current query" messages at the bottom because they are not useful to you?

I'll see what I can do.

**Comment by rgnkn** [comment]
Oups. Yes my suggestion would be to disable the query line by default and opt it in if someone needs it. At least for me there seems to be no need for this visual feedback at all.

**Comment by rgnkn** [comment]
... and yes: My config is heavily applying lazy loading ;-)
