### ISSUE TITLE
mini.ai: around selection occasionally misses left side

### ISSUE THREAD

**Issue by atusy** [echasnovski/mini.nvim#641]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

If I perform `va*` on `*foo*`, I expect `*foo*` is selected.
However, the selection is `foo*`, which is missing `*` on the left.

The similar thing happens on `/` or some other symbols.

### Neovim version

0.8 to 0.10 (unreleased)

### Steps to reproduce

- setup

```
vim.opt.runtimepath:prepend("/path/to/mini.nvim")
require("mini.ai").setup({})
```

- do `va*` on a line: `*foo*`

### Expected behavior

selection is `*foo*`

### Actual behavior

selection is `foo*` (missing left `*`)

**Comment by echasnovski** [comment]
This is [by design](https://github.com/echasnovski/mini.nvim/blob/a118a964c94543c06d8b1f2f7542535dd2e19d36/doc/mini-ai.txt#L175-L179) and is more oriented towards the following type of use cases: remove `bbb_` from `aaa_bbb_ccc` while preserving snake case.

To avoid this, define custom textobjects for surrounding characters you use, like `*`, `/`, etc.
