### ISSUE TITLE
Mini.notify gets stuck

### ISSUE THREAD

**Issue by eXvimmer** [echasnovski/mini.nvim#647]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.notify

### Description

Hi.
When I open a file (e.g., a Lua file) and try `:LspStop lua_ls` while the LSP is trying to index the files, the mini.notify gets stuck in the corner and I cannot close it.

[Screencast from 08-01-24 02:05:21.webm](https://github.com/echasnovski/mini.nvim/assets/30720669/8b860d10-264f-426d-b3de-9f1bce1e00d5)

### Neovim version

v0.9.4

### Steps to reproduce

Try LspStop while mini.notify is showing and the LSP is indexing.

### Expected behavior

Mini.notify should be gone after a specific time (1500ms in my case).

### Actual behavior

It remains there.

**Comment by echasnovski** [comment]
Thanks for the issue!

LSP progress notifications are handled according to [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress), which states that work is done after there is a [certain response from a server](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressEnd). Doing `LspStop` prevents processing that response thus 'mini.notify' thinks that progress is still in place. I think this is an expected behavior here.

To remove notifications, use `:lua MiniNotify.clear()`.

Closing as not planned.

**Comment by eXvimmer** [comment]
Thanks for your response.
I used to use fidget, and it was able to handle these cases. I think there might be some way to prevent this behavior.

**Comment by echasnovski** [comment]
> Thanks for your response. I used to use fidget, and it was able to handle these cases. I think there might be some way to prevent this behavior.

Of course, there is a way. I am saying that the behavior itself of hiding LSP progress notifications not only after its successful end is a bit misleading and should be quite rare. If this occurs, there is something wrong and should be investigated further. If done on purpose, there is `MiniNotify.clear()`.

**Comment by eXvimmer** [comment]
Thank you!
