### ISSUE TITLE
mini.files: file deletion upon undoing rename operation

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#656]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

files

### Description

After renaming a file and confirming the change, attempting to undo and then reconfirming will result in the file being deleted. This has led to many issues in large-scale codebase refactoring, among others.

### Neovim version

NVIM v0.10.0-dev+1974-g714b07519

### Steps to reproduce

1. Create two files, hello.c and hello.h.
2. Rename hello.c to main.c and confirm the change.
3. Undo the previous rename operation and confirm.
4. Observe that our file is now deleted.

### Expected behavior

Undoing a file rename should not result in file deletion; rather, main.c should revert to being hello.c.

### Actual behavior

[Screencast from 2024-01-15 11-54-09.webm](https://github.com/echasnovski/mini.nvim/assets/91024200/24707603-89aa-491b-835f-a4fd59d64ab2)

**Comment by echasnovski** [comment]
Thanks for the issue!

I can indeed confirm. The reason this happens is because of [how 'mini.files' tracks which operation need to be done](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-files.txt#L234-L245). Here is what is going on:
- Initially explorer contains lines of something like `/1/hello.c` and `/2/hello.h`. Here 1 and 2 are unique path identifiers which are stored for each session.
- First renaming is deduced when synchronizing the following lines: `/1/main.c` and `/2/hello.h`. 'mini.files' sees that the file `1` doesn't match what it has stored and deduces that file should be renamed. And successfully renames. Lines after that are `/2/hello.h` and `/3/main.c` as 'main.c' is a different path on disk.
- *Now*, after undo lines are the same as they were initially. During synchronization 'mini.files' sees that file `3` was present and now is missing thus deciding it needs to be deleted. I *think* it should also suggest creating file `2` in this situation, but it does not.

I'll see what is the best approach in this situation.

**Comment by echasnovski** [comment]
Thanks again for opening the issue! This should be fixed on latest `main`.

**Comment by wroyca** [comment]
> Thanks again for opening the issue! This should be fixed on latest `main`.

I confirm, thank for the quick fix!
