### ISSUE TITLE
[mini.surround] Separate remaps for normal and visual mode?

### ISSUE THREAD

**Issue by lupont** [echasnovski/mini.nvim#66]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Hi!
I'm a long time vim-surround user, so I wanted to change the mappings of mini.surround to reflect those present in vim-surround. In that plugin, you use `ys` to add a surrounding. This remapping fine in normal mode, but when highlighting something in visual mode and pressing `y` to yank it, it puts you in operator pending mode - presumably because it's waiting to see if you want to execute `ys` from mini.surround.

I'd really like a way to map only for normal mode. For inspiration, vim-surround maps `S` to add a surrounding when in visual mode.

I've also remapped changing a surrounding to `cs`. Curiously, pressing `c` when in visual mode does not put you in operator pending.

Please let me know if anything is unclear, or if you'd like a minimal config to try it out and compare with vim-surround.

Thanks for this great plugin!

**Comment by echasnovski** [comment]
Thanks for suggestion and kind words!

You've got a valid point here. I was a 'vim-sandwich' user myself, so an overall design is more adapted towards it. I am leaning towards adding this, but I tend to spend at least a night before making such decision. Tomorrow I hope to get back here.

Two nitpicks:
- In your case after pressing `y` in Visual mode Neovim doesn't "go into Operator pending mode". It waits `timeoutlen` time for a possible mapping to complete. So basically, everything you said, but without "Operator pending mode" name.
- There is no such behavior for `cs` and `c` in Visual mode because there is no mapping for "change surrounding" in Visual mode.

**Comment by lupont** [comment]
Great to hear! And so quickly, too.

You know, I had a feeling it wasn't the correct term. I opted to believe that it'd at least get the point across :) thanks for the explanation! And that makes sense regarding `c` in visual mode, I can't really imagine it being very useful.

**Comment by echasnovski** [comment]
So after thinking for a while, I came to conclusion that main problem here seems to be not "separate mappings for Normal and Visual modes", but "How to configure similarly to 'tpope/vim-surround'"? So I added the "recommended" way of doing so in documentation and tried to make it reasonably visible. It doesn't change current configuration options, but rather makes a remapping afterwards (few of them, actually).

Hope this answers your question. If not, feel free to elaborate here.

**Comment by lupont** [comment]
Great, always nice to be able to use existing functionality. Your suggestion works well, bonus points for the separate `(` and `)` bindings! I unmapped `ys` in visual mode, since with your suggestion `S` works.

```lua
vim.keymap.del("v", "ys")
```

Thanks again!
