### ISSUE TITLE
Inaccurate tag match in the presence of an arrow function operator

### ISSUE THREAD

**Issue by thenbe** [echasnovski/mini.nvim#671]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

ai

### Description

Incorrect `it` match in the presence of an arrow function operator.

Given the following svelte snippet:

```svelte
<x on:click={() => 1}>aaa</x>
```

`it` will match: ` 1}>aaa`, whereas the match should be `aaa`. The error is caused by the early `>` sign which is part of the arrow function operator `=>`.

### Neovim version

NVIM v0.10.0-dev-4e59422

**Comment by echasnovski** [comment]
Thanks for the issue!

Tag textobject has obvious limitations in 'mini.ai' due to it using Lua pattern matching by default. The current implementation indeed recognizes tag only up to the first instance of `>`.  As you did in #672, this can be customized, but I am hesitant to increase complexity of this textobject even further.

Specifically for tags a more sustainable and robust approach would be to use tree-sitter parsing and textobjects based on queries from 'nvim-treesitter-textobject': create filetype config file in 'after/ftplugin/xxxxxx.lua' (replace `xxxxxx` with the name of 'filetype' option inside which you need this specific behavior; not sure which one is set when working with Svelte) and define `vim.b.miniai_config` buffer local variable there:

```lua
local spec_treesitter = require('mini.ai').gen_spec.treesitter
vim.b.miniai_config = {
  custom_textobjects = {
    -- Replace tags for captures which cover tags in the target filetype
    -- See 'nvim-treesitter-textobject' queries to know more
    t = spec_treesitter({ a = '@function.outer', i = '@function.inner' }),
  },
}
```

It will be more accurate but won't work inside comments and strings, though.

Closing as not planned.

**Comment by thenbe** [comment]
> hesitant to increase complexity of this textobject even further

Fair enough. Thanks for pointing me in the right direction. For those that come later, here is how I fixed it:

1. Create file `nvim/queries/svelte/textobjects.scm` with the following contents:

   ```query
   ; These are mostly taken from upstream html/textobjects.scm, but with
   ; `s/function/tag`. This is because upstream captures tags as @function, whereas
   ; in svelte tags and functions may co-exist at the same time. Therefore, we now
   ; explicitly capture tags as @tag instead of @function.
   ;
   ; Also see:
   ; https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/queries/html/textobjects.scm
   ; https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/189468b62133d44fb6220530c8aa96718d0e93d1

   (element) @tag.outer

   (element (start_tag) . (_) @tag.inner . (end_tag))

   ((element (start_tag) . (_) @_start (_) @_end . (end_tag))
   (#make-range! "tag.inner" @_start @_end))

   (script_element) @tag.outer
   (script_element (start_tag) . (_) @tag.inner . (end_tag))

   (style_element) @tag.outer
   (style_element (start_tag) . (_) @tag.inner . (end_tag))
   ```

1. Create file `nvim/ftplugin/svelte.lua` with the following contents:

   ```lua
   local spec_treesitter = require('mini.ai').gen_spec.treesitter
   vim.b.miniai_config = {
     custom_textobjects = {
       t = spec_treesitter({ a = '@tag.outer', i = '@tag.inner' }), -- @tag.outer and @tag.inner are defined in svelte/textobjects.scm
     },
   }
   ```
