### ISSUE TITLE
mini.surround: proper vim grammar semantics for specifying count for deletion and replacement operations

### ISSUE THREAD

**Issue by TheSast** [echasnovski/mini.nvim#676]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

This is an extension of #376.
> When it comes to doing surround operations count1 should apply to the operator and count2 should apply to the object.

This should apply to deletion and replacement operations too, making `2sd(` convert `(foo (b*r)) baz` to `foo bar baz` in place of `foo (bar) baz` which would instead be achieved via `sd2(`.
Similarly, `2sr)]` would turn `(foo (b*r)) baz` into `[foo [bar]] baz`, and `sr2)]` would result in `[foo (bar)] baz`.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Right now all "input" surrounding (which find surrounding; as in "delete" and first step of "replace") is implemented via getting a single character surrounding identifier. Implementing cases like `sd2(` and `sr2)]` would require much complicated logic (taking into account that proper support needs to account not only single digit counts, but also more), which is not welcome.

Other than that, most of use cases you describe can be done with dot-repeat:
- `(foo (b*r)) baz` -> type `sd).` -> `*oo bar baz`.
- `(foo (b*r)) baz` -> type `2sd)` ->`*oo (bar) baz`
- `(foo (b*r)) baz` -> type `sr)].` -> `[*oo [bar]] baz`
- `(foo (b*r)) baz` -> type `2sr)]` -> `[*oo (bar)] baz`

So `[count]` for this type of operations will remain to be the number *before* action mapping and will have [this meaning](https://github.com/echasnovski/mini.nvim/blob/79b1b3350f1cac7cef9e46a637f9adf2a14b4923/doc/mini-surround.txt#L390-L393).

Closing as not planned due to being.
