### ISSUE TITLE
Question: permanent_delete MacOS Trash

### ISSUE THREAD

**Issue by daniel-samson** [echasnovski/mini.nvim#685]
Hi,

I am currently using mini.files plugin. When i delete files, i want it move it to my trash can. I have tried to pass in the correct options for this, but it doesn't seem to be working.

```lua
require "mini.files".setup({
  options = {
	  permanent_delete = false,
  }
})
```

Am i missing something here?

**Comment by echasnovski** [comment]
The [`config.options.permanent_delete` indicates whether to perform permanent delete or move into **special** trash directory](https://github.com/echasnovski/mini.nvim/blob/16600082b7b3e3ee3aa3d59f2bc589fc60ffcada/doc/mini-files.txt#L602-L606). That trash directory is not the same as system trash because moving files into system trash is not entirely trivial.

If you have deleted files after permanent delete was disabled, the files should be present in 'mini.files/trash' subdirectory of "data" standard path.
