### ISSUE TITLE
[mini.files] Deleting file/folder moves files to system trash / recycle bin

### ISSUE THREAD

**Issue by daniel-samson** [echasnovski/mini.nvim#686]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

As a user, I want to be able to specify which command, the "mini.files" module uses to delete a file/folder, so that when i delete a file it moves the file to the system trash can or recycle bin.

* Given that i am on a MacOS computer, i want to be able to use the [trash](https://hasseg.org/trash/) command.
* Given that i am on Windows computer, i want to be able to use the [recycle.exe](https://github.com/kizzx2/cmd-recycle) command.
* Given that i am on Linux computer, i want to be able to use the [trash-put](https://github.com/andreafrancia/trash-cli.git) from the trash cli.

### Proposal

In the `mini.files` module:
* Add a `config.options.delete_command` to the default config as an empty string. 
* Update `H.fs_delete` function in the `mini.files` arguments to `function(path, permanent_delete, delete_command)`
* Pass `config.options.delete_command` into `delete_command` argument
* Update `H.fs_delete` function in the `mini.files` module to check if `delete_command` is empty
* When `delete_command` is not empty call `os.execute(delete_command .. ' ' .. path)`

### Additional Notes

I have tested this locally and it seems to work fine. I intend to make a pull request, after i have check my changes against to CONTRIBUTING.md guidelines. 

I welcome any feedback, questions, or comments.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was previously discussed in #431. I still concur the reasoning from that issue and would like this to not be a part of 'mini.files'. With one extra reason: 'mini.nvim' tries to avoid any dependencies when possible and having to rely on three different CLI tools for three platforms does not quite align with this design goal.

I *really* appreciate the enthusiasm, but this type of PR will not be merged.

**Comment by enoryw** [comment]
@daniel-samson can you share the code for Linux system trash? Within a minute of testing out this plugin I knew system trash needs to be supported. The trash directory of any good file manager has only ever meant system trash and I would rather not have to remember and manage files from trash differently in some weird editor plugin-specific directory. From the user standpoint, nothing is simpler than using a file manager that support systems trash like any decent ones or plugins for that matter. I often wish Mini's philosophy of keeping things simple to also mean it is simple for the users because--as in this example (and with mini.pick), artificial limitations impose a layer of complexity for no good reason.

Trash files from mini.files are no different than any other trash files on the system. I don't see how optional dependencies are an issue and nothing would change for users who don't use the feature as the default is all they need. At the end of the day a good plugin is one that does its job well and works as expected without weird quirks, not because it has fewer lines of code for personal amusement.

**Comment by echasnovski** [comment]
> I often wish Mini's philosophy of keeping things simple to also mean it is simple for the users because--as in this example (and with mini.pick), artificial limitations impose a layer of complexity for no good reason.

Making plugin easy to use *is* the goal of any 'mini.nvim' module. But unfortunately, it is the opposite of achieving an easy future-proof maintenance. And the number one design of this plugin is to balance both of them.

> I don't see how optional dependencies are an issue and nothing would change for users who don't use the feature as the default is all they need. At the end of the day a good plugin is one that does its job well and works as expected without weird quirks, not because it has fewer lines of code for personal amusement.

It doesn't look like any more justification beyond what is presented here or in the documentation will be useful here. If you personally are not happy with how the plugin is designed or implemented, there is no need to add this extra information to the issue tracker. It doesn't really help 'mini.nvim' development.

**Comment by max397574** [comment]
I also just started using this plugin and was looking for an answer to this.

Collecting the reasons from you to not add it from the different threads linked here and then recursively:
> Basically: too complex to do it right and cross-platform.

nothing to say about this since it doesn't really say anything specific

> Also having a way to customize deleting but not other actions seems a bit off, which only adds to the complexity/maintenance.

there is an extra option now either way so this is no longer relevant.

> My main reason for not going with delete_cmd is mostly because it is virtually Unix-only; Windows users probably won't install any CLI apps.

that doesn't make sense, like just because it's more unlikely that windows users will use this is no reason to not add it



So either I missed something or there weren't really any good reasons for not adding this. It should be as simple as `vim.system(user_cmd:format(file))` (or however you pass the file to the user cmd added at this line https://github.com/nvim-mini/mini.files/blob/02874bc653fbecf2bee2c65441d0ebd09110f011/lua/mini/files.lua#L2955

**Comment by max397574** [comment]
A really easy way to get this working for at least some users would be to just allow to configure the trash directory I guess.

**Comment by echasnovski** [comment]
> So either I missed something or there weren't really any good reasons for not adding this. 

What makes a reason "good" is in the eye of the beholder. Adding a feature that depends on three different OS specific CLI tools is not something I'd like to maintain. Even adding a placeholder config for this would require documenting how to make it useful for users, which is also maintaining (since it'll require documenting and recommending specific tools).

> there is an extra option now either way so this is no longer relevant.
> ...
> It should be as simple as `vim.system(user_cmd:format(file))` (or however you pass the file to the user cmd added at this line https://github.com/nvim-mini/mini.files/blob/02874bc653fbecf2bee2c65441d0ebd09110f011/lua/mini/files.lua#L2955

The `user_cmd` is another extra option, though.

> A really easy way to get this working for at least some users would be to just allow to configure the trash directory I guess.

This is not as easy as that, since deleting to trash directory is special. There has to be some metadata stored about files for them to be able to be restored. That's the reasons there are OS specific tools that take care of this.

**Comment by max397574** [comment]
for anyone interested in this, here is how I got it working on macos, use at your own risk:
```diff
diff --git a/lua/mini/files.lua b/lua/mini/files.lua
index 43bcaf8..89d7aaa 100644
--- a/lua/mini/files.lua
+++ b/lua/mini/files.lua
@@ -2955,11 +2955,7 @@ end
 H.fs_do.delete = function(from, to)
   -- Act based on whether delete is permanent or not
   if to == nil then return vim.fn.delete(from, 'rf') == 0 end
-  pcall(vim.fn.delete, to, 'rf')
-  -- Move to trash but skip renaming loaded buffer (same as with permanent
-  -- delete). This also skips triggering extra autocommands that can have
-  -- unwanted side effects (like loading LSP in the new "trash" project).
-  return H.fs_do.move(from, to, true)
+  return vim.system({ 'trash', from }):wait().code
 end
 
 H.fs_do.move = function(from, to, skip_buf_rename)
```
