### ISSUE TITLE
Question: How do I disable the navigation by "letter" on starter so I can use j, k and <CR>?

### ISSUE THREAD

**Issue by dathinaios** [echasnovski/mini.nvim#70]
As the title states, I don't need to navigate using letter selection as I usually just go to my last saved session and when I need to change I just want to select different one with j, k as I used to do on startify. Muscle memory is kicking in pretty strongly with this one...

**Comment by echasnovski** [comment]
At the moment, I don't think there is a way. And ,probably, won't be a builtin way to do so because of the main idea of using "query" before arrows.

There are at least two options for you:
- Use `require('mini.starter').setup({ query_updaters = '' })` with custom buffer mappings for `j` and `k` using `MiniStarter.update_current_item()`. So something like:
```lua
require('mini.starter').setup({ query_updaters = '' })
vim.cmd([[
  augroup MiniStarterJK
    au!
    au User MiniStarterOpened nmap <buffer> j <Cmd>lua MiniStarter.update_current_item('next')<CR>
    au User MiniStarterOpened nmap <buffer> k <Cmd>lua MiniStarter.update_current_item('prev')<CR>
  augroup END
]])
```
- Try to get used to `<M-j>/<M-k>`. I personally use these and it was not that hard transition.

**Comment by dathinaios** [comment]
Works a treat 😀 Thank you!
