### ISSUE TITLE
Wrong comment on markdown files

### ISSUE THREAD

**Issue by drzhivago420** [echasnovski/mini.nvim#705]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

Hello, I know markdown doesn't really have "comments", but it is kind of a consensus to respect HTML style comments ( `<!-- comment -->` ) on markdown files. That's the way tpope's plugin does it for example.

Currently mini.comment uses `# comment` for md files, and in markdown that means a header, so kinda the opposite of a comment.

### Neovim version

NVIM v0.10.0-dev

### Steps to reproduce

1. `nvim a.md`
2. Write line
3. gcc that line

### Expected behavior

Comment format is `<!-- comment -->`

### Actual behavior

Comment format is `# comment`

**Comment by echasnovski** [comment]
'mini.comment' [infers comment structure from 'commentstring' option](https://github.com/echasnovski/mini.nvim/blob/1d49300d50a2c8ee7faecceb151084f207ff65ba/doc/mini-comment.txt#L11-L14). For me (and [by default](https://github.com/neovim/neovim/blob/ea0737c838b029fc96b1321c4ac15e0dc7e29b84/runtime/ftplugin/markdown.vim#L15)) it is equal to `<!--%s-->` which is the same as the expected behavior.

My guess is that something overrides this to be `# %s`. It might be something trivial, like `FileType` autocommand or 'ftplugin/markdown.lua', either in the config or from plugin. Or it might be something less trivial: you use tree-sitter highlighting and have global 'commentstring' option set to `'# %s'` (which should be the default empty string `''` as [per documentation](https://github.com/echasnovski/mini.nvim/blob/1d49300d50a2c8ee7faecceb151084f207ff65ba/doc/mini-comment.txt#L28-L30)).

**Comment by drzhivago420** [comment]
Seems like you are right and the problem is related to treesitter, I'll just completely disable it with markdown files.

**Comment by echasnovski** [comment]
> Seems like you are right and the problem is related to treesitter, I'll just completely disable it with markdown files.

It seems to be too drastic, as allows massive quality of life improvement specifically in markdown (at least by highlighting code blocks with the language inside it, if it has tree-sitter highlighting enabled).

I would suggest figuring out why 'commentstring' changes here. You can see the value of global option with `=vim.inspect(vim.go.commentstring)`. The aim is for it to output `""`.

**Comment by drzhivago420** [comment]
![Peek 2024-02-17 23-09](https://github.com/echasnovski/mini.nvim/assets/110633694/ead7b542-2e39-4e02-b1dc-f84eeb4cb118)
Commentstring is still empty. I don't really have much configuration either, if any at all, with the treesitter plugin. The only other thing that I can recall on my config  related to treesitter is Neorgl with the sync parsers thing.

Anyway not trying to make you troubleshoot my config problems, just commenting in case anyone else gets the same issue.

**Comment by echasnovski** [comment]
> Commentstring is still empty. I don't really have much configuration either, if any at all, with the treesitter plugin. The only other thing that I can recall on my config related to treesitter is Neorg with the sync parsers thing.

Strange.

> Anyway not trying to make you troubleshoot my config problems, just commenting in case anyone else gets the same issue.

But yeah, sorry, I can not reproduce this even with Neorg installed and set up. I thought maybe there was some issue with 'comment' tree-sitter parser, but even with it enabled I still could not reproduce.
