### ISSUE TITLE
Cursor horizontal position lost after scrolling

### ISSUE THREAD

**Issue by bassamsdata** [echasnovski/mini.nvim#715]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

I encountered an issue where the cursor's horizontal position is lost after scrolling using C-d / C-u / C-f commands.

I faced a similar problem with another plugin, which was related to the 'winhl' option in Neovim. A fix for this issue can be found here: [#27470](https://github.com/neovim/neovim/issues/27470). Consequently, I believe this issue might be related.

I haven't opened an issue on Neovim because I'm unsure about which option is set by this plugin and how exactly the plugin operates or even if the issues are related.

### Neovim version

NVIM v0.10.0-dev-2445+g2e1f5055a

### Steps to reproduce

1. this code:

```sh
mkdir repro
cd repro
git clone https://github.com/echasnovski/mini.nvim
cat >repro.lua <<EOF
vim.o.runtimepath = os.getenv('PWD') .. '/mini.nvim,' .. vim.o.runtimepath
require('mini.animate').setup()
EOF
nvim --clean -u repro.lua
```

2. edit a long file that has multiple short and long lines. 
3. scroll down by C-d and C-u and the issue will occur.

### Expected behavior

keep cursor column position

### Actual behavior

lose cursor column position

**Comment by echasnovski** [comment]
Thanks for the issue!

Would you mind elaborating a bit about what do you mean by "cursor column position is lost"?

My current understanding is that if before scroll cursor was on come column (say 20) and after scroll it happens to land on the last column of short line (say 10), then next scroll tries to set cursor on line 10 instead of 20 (even if line is long enough)? If this is the case, then I don't think this is a big issue. I'll take a look at if this can be solved relatively pain free, but I'd not have hopes up (as the only way to use the information about where cursor "wants" to go is with Vimscript `getcurpos()` and `cursor()` with which I did not have much success in 'mini.animate').

**Comment by bassamsdata** [comment]
Thank you for the response.

> My current understanding is that if before scroll cursor was on come column (say 20) and after scroll it happens to land on the last column of short line (say 10), then next scroll tries to set cursor on line 10 instead of 20 (even if line is long enough)

Yes, this is the issue. I've noticed this especially when it reaches an empty line, column 0, and remains there during scrolling.

Given my experience with a similar issue caused by Neovim `options` in another plugin, I raised this concern.

> If this is the case, then I don't think this is a big issue. I'll take a look at if this can be solved relatively pain free, but I'd not have hopes up

Since I'm not fully familiar with how the plugin operates, and probably the scrolling is not fully controlled, then there is no issue here.

Thank you

**Comment by echasnovski** [comment]
So after considering it for a while now, I don't think this is a huge issue for how much trouble it would require to implement, test, and maintain. Sorry.

Closing as not planned.
