### ISSUE TITLE
Syntax highlighting in mini.doc codeblocks

### ISSUE THREAD

**Issue by S1M0N38** [echasnovski/mini.nvim#716]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.doc

### Description

Hi, is there any plan to add syntax highlighting to codeblocks generated by `MiniDoc.afterlines_to_code`?
I think that this can be added without much overhead as a optional parameter, that is
```lua
MiniDoc.afterlines_to_code = function(struct, lang)
  ...
  return '>' .. (lang or '') .. '\n' .. src .. '\n<'
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

'mini.nvim' itself does not yet use `>lang` notation in help files since it currently supports Neovim>=0.7.0 and this notation became non-breaking in 0.8.2 (and actually useful in 0.9.0).

I plan to give 'mini.doc' an update resolving some other issues (#666, #668) and will see if adding this change will be worth it at that point.

**Comment by echasnovski** [comment]
As 'mini.nvim' now (finally) does not support Neovim<0.8, this is resolved on latest `main`. I opted to always use `>lua` (even though it is a breaking change) because 'mini.doc' is meant to be always used for Lua files.
