### ISSUE TITLE
FR: trim when replacing linewise register into charwise text object

### ISSUE THREAD

**Issue by chrisgrieser** [echasnovski/mini.nvim#743]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.operators / replace operator

### Description

Given this example:

```lua
local foo = {
	"apple",
	"orange",
	"banana"
}
buySome(fruits)
```

I yank "banana" with `yy`, go two lines down, and want to substitute `fruits` via `grib`.

```lua
-- result includes the leading whitespace
buySome(	"banana")

-- expected/desired result
buySome("banana")
```

I cannot really think of a scenario where the current behavior would be desirable, so I would like to propose to change the replace-operation to trim text when replacing a charwise object with linewise content.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> I cannot really think of a scenario where the current behavior would be desirable, so I would like to propose to change the replace-operation to trim text when replacing a charwise object with linewise content.

The main reason for trying to preserve the text from register as much as possible is to reduce the amount of surprise. That is, if user put a text with whitespace in the register then this text should be used during replace.

Having this behavior changed to allow more general `yy` instead of more target `yi"` in this case looks a bit far fetched to me. Besides, that would mean *if* user actually wants to include whitespace from linewise selection in charwise replace, they'd have to not do the obvious `yy` but resort to forcing charwise selection.

All in all, replacing text with target and register having different selection types (charwise/linewise/blockwise) is supported more for completeness sake. I'd strongly suggest in day-to-day editing to replace text with register of the same type.

Closing as not planned.
