### ISSUE TITLE
Replacing wrong HTML tag

### ISSUE THREAD

**Issue by OysterD3** [echasnovski/mini.nvim#755]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

I am using LazyVim with `mini.surround` and playing with it

### Neovim version

0.9.5

### Steps to reproduce

1. `nvim test.html`
2. 
```html
<div>
  <h1>Test</h1>
  <div>
    <p>Test</p>
  </div>
</div>
```
3. Place the cursor at first `<`
4. `gzrtt`
5. test
6. Enter

### Expected behavior

It should be replace the last `div` closing tag instead of the closest one. Which became
```html
<test>
  <h1>Test</h1>
  <div>
    <p>Test</p>
  </div>
</test>
```

### Actual behavior

```html
<test>
  <h1>Test</h1>
  <div>
    <p>Test</p>
  </test>
</div>
```

**Comment by echasnovski** [comment]
Thanks for the issue!

In 'mini.surround' the built-in input surroundings are searched with Lua patterns (similar to regular expressions). [Tag surrounding is no exception](https://github.com/echasnovski/mini.nvim/blob/e025ee74705b04dd25a132a521c9c535dc78a8d8/doc/mini-surround.txt#L51-L53).

This particular case is because `<div>` tags are nested and similar to the 'mini.ai' tag textobject (for example, see #735).

My suggested solution is to use [tree-sitter based surrounding](https://github.com/echasnovski/mini.nvim/blob/e025ee74705b04dd25a132a521c9c535dc78a8d8/doc/mini-surround.txt#L732). This is the best option if you work in tag-related filetypes often and have tree-sitter enabled there. This requires investigation about which 'nvim-treesitter-textobjects' query corresponds to tags in the target filetype.

Closing as not planned.
