### ISSUE TITLE
Some examples that would be great for the readme/docs for hiPatterns

### ISSUE THREAD

**Issue by snoblenet** [echasnovski/mini.nvim#759]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-hiPatterns

### Description

I'm really enjoying `mini-hiPatterns`. Thanks! 💯 

Here are some examples that would be great for the readme and/or the docs:

- highlight entire line, but only when line starts with a particular string
- highlight entire line, but only when line ends with a particular string
- highlight entire line when line, but only when:
  - line starts with a particular string, or
  - line end with a particular string, or
  - line contains a particular string, with whitespace on either side (like the existing example in the docs)

Also, this is not on `mini.nvim` at all, but if it was possible, it would be amazing if there were also links to:
- a definitive guide to using Lua's frontier patterns
- a snippet that shows how to read all existing styles on a highlight group so they can be incorporated into the call to `vim.api.nvim_set_hl()`

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This all feels a bit too narrow to be included in the docs. Here is one way to do three scenarios from this issue:

```lua
require('mini.hipatterns').setup({
  highlighters = {
    -- Highlight whole line including all space to the right
    line_starts = { pattern = '^hello', group = 'DiffAdd', extmark_opts = { line_hl_group = 'DiffAdd' } },

    -- Highlight whole line but only text
    line_ends = { pattern = '^.*world$', group = 'DiffChange' },

    -- I don't think there is a way to include a complex "... or ..." logic to
    -- `pattern`. See `:h MiniHipatterns.config` for what is possible.
  },
})
```

> a definitive guide to using Lua's frontier patterns

I don't know about a single definitive guide to frontier patterns. Here is [the description from Lua 5.4](https://www.lua.org/manual/5.4/manual.html#6.4.1) reference guide. This works incidentally in Neovim because it uses LuaJIT 5.1, which does have frontier patterns.

> a snippet that shows how to read all existing styles on a highlight group so they can be incorporated into the call to `vim.api.nvim_set_hl()`

Not entirely sure what should be done here and why this might be needed. There is a [`get_matches()`](https://github.com/echasnovski/mini.nvim/blob/a683bfe8e03293e3bb079e24c94e51977756a3ec/doc/mini-hipatterns.txt#L392) which returns data about matches and should be enough.

------

Closing as not planned.
