### ISSUE TITLE
Add option to start nvim without session when autoread is true

### ISSUE THREAD

**Issue by edshamis** [echasnovski/mini.nvim#76]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.sessions

### Description

I'd like to start with session by default but to have an option to skip it without loading a file. 
For example
`nvim "+let g:mini_sessions_enabled = v:false"`
It can also serve if one decides to condition session loading in init
Or maybe I missed the existing option?))

**Comment by echasnovski** [comment]
This can already be done two ways (well, one and a half):
- All "runtime" options in every 'mini.nvim' module can be [modified manually after setup to take effect](https://github.com/echasnovski/mini.nvim/blob/b0ba2b98ee63b4814fcfa7657dab9f72bc4cc7da/README.md?plain=1#L79). So in this case the most suitable way of doing this is to use `nvim -c 'lua MiniSessions.config.autoread = false'`.
- Any 'mini.nvim' module have the same [disabling functionality](https://github.com/echasnovski/mini.nvim/blob/b0ba2b98ee63b4814fcfa7657dab9f72bc4cc7da/README.md?plain=1#L80). In this case you can do `nvim -c 'let b:minisessions_disable=v:true'`. That is only a half-solution because it will disable `mini.sessions` in the first loaded buffer, requiring resetting this variable or creating new buffer in order to use 'mini.sessions'.

**Comment by echasnovski** [comment]
I think this is exactly the type of information suitable for 'wiki'. So I created [new page](https://github.com/echasnovski/mini.nvim/wiki/mini.sessions#how-to-start-nvim-without-session-when-autoread-is-true) there. Thanks for the question!

**Comment by edshamis** [comment]
Cool, thanks. I'll try it
