### ISSUE TITLE
Possible to open file under cursor in a split with mini.files

### ISSUE THREAD

**Issue by siddhantac** [echasnovski/mini.nvim#760]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

This may already be possible but I haven't found a way to do it yet. 

I want to open a file in a vertical or horizontal split. The example config provided in the docs opens the _currently open_ file in a new vert/horiz split, but I want to open the file that is under my cursor.

**Comment by echasnovski** [comment]
The #646 issue has the same question. Here is [the answer](https://github.com/echasnovski/mini.nvim/issues/646#issuecomment-1880700124).

Basically, follow the the [example in the help page to modify target window via split](https://github.com/echasnovski/mini.nvim/blob/a683bfe8e03293e3bb079e24c94e51977756a3ec/doc/mini-files.txt#L429-L458) and follow it up by opening file as usual (it will be opened in the newly created split).

Closing as duplicate.

**Comment by siddhantac** [comment]
Thank you for the response. However, that solution requires me to open mini.files again after splitting. Is there no way to directly open the file under cursor in the mini.files popup to open in the split?

**Comment by echasnovski** [comment]
> I wanted to do the equivalent of `:vsplit <filename>` where the filename is taken from the currently selected file in the mini.files popup. Is there no way to directly open the file under cursor in the mini.files popup to open in the split?

Yes, there is. It requires modifying the example code a little bit. There is a line there which sets target window and you'd want to immediately follow up with opening file. There is an exported function in 'mini.files' for that: [`go_in()`](https://github.com/echasnovski/mini.nvim/blob/a683bfe8e03293e3bb079e24c94e51977756a3ec/doc/mini-files.txt#L693). This will be an addition of a single line.
(I'd like to make it clear that this answer is an attempt at "instead of giving a fish, teach a person to fish, and they'll never be hungry")

Note: if you are using 'mini.operators', beware that typing `gs` for a horizontal will be followed with a delay because there is a `gss` mapping coming from it (so Neovim wait for `'timeoutlen'` milliseconds for extra keys).

**Comment by siddhantac** [comment]
> go_in()

That's the thing I was looking for! Thanks! I have been trying to hack my way around to this for a while, just somehow managed to overlook that function entirely. 🙂
