### ISSUE TITLE
Add mini.files example on how to show git status as an extmark

### ISSUE THREAD

**Issue by RaafatTurki** [echasnovski/mini.nvim#765]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Hi!
This is less of a feature request and more of an inquiry.

The help page is very clear on git integration being out of scope, however it does hint that it's achievable by setting extmarks on the `MiniFilesBufferUpdate` event.

I hope some code snippet of this gets added to the wiki or the examples section in the help file.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The problem here is actually computing status of each path, adding extmarks would be somewhat straightforward (needs only the proper combination of options). In turn, getting information about Git status for every path and in a way that is at least somewhat efficient (at least non-blocking and not loading 100% CPU) is not something that can be expressed in a concise and usable manner. So I don't think it will be added.

Closing as not planned.

------

(There is planned 'mini.git' module for which I already have approximate scope and I also don't really see a concise way of utilizing it for this kind of task).
