### ISSUE TITLE
Add support for user defined diagnostic signs

### ISSUE THREAD

**Issue by suliatis** [echasnovski/mini.nvim#769]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

If the user defined diagnostic signs are available via `vim.fn.sign.setdefined` or `vim.diagnostic.config`, then use it show diagnostic count in the diagnostic statusline provider.

I think this would fit into mini.statusline nicely without adding too much extra complexity.

I'm planning to create a pr with this change if you agree.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yes, I think this is a reasonable thing to add.

> I'm planning to create a pr with this change if you agree.

Please don't. There is a planned update coming to 'mini.statusline' in the foreseeable future, in which I'll also resolve this suggestion.

**Comment by echasnovski** [comment]
This is now finally possible on latest `main`.

Although, unfortunately, not as straightforward for users as only configure `vim.diagnostic.config({ signs = { text { ... } } })`. For actual reasons see comment message at 4b397915a4cacba1c9fe8033f0ff048d8f377a29.

**Comment by pkazmier** [comment]
Nice! Although after trying a couple of variants:

### Icons instead of E, W, H, I
Too many icons for my taste. I prefer the less-is-more approach used by mini's default settings where an icon is used to introduce a section of the statusbar.
<img width="1050" alt="Screenshot 2024-05-31 at 8 41 54 AM" src="https://github.com/echasnovski/mini.nvim/assets/747855/e5f6b7b0-9674-4b0f-a86d-a7f6fae9a68c">

### Color versions of E, W, H, I
I would define new hlgroups to color match the background if I liked this, but I prefer monochromatic approach used by mini's default settings. The only place I like color in my statusbar is to highlight the filename if the buffer has been modified (in my screenshot it's green).
<img width="1050" alt="Screenshot 2024-05-31 at 8 57 07 AM" src="https://github.com/echasnovski/mini.nvim/assets/747855/2bcf3f3c-a196-4cf7-b07c-12134ca9a3f2">

### Original
It's nice to have the option to customize of course, but I find myself resorting back to the defaults as I find the minimal aesthetics more pleasing to my eye (although oddly I still use icons in the statuscolum, but maybe I'll revisit that right now 😄 ).
<img width="1050" alt="Screenshot 2024-05-31 at 8 58 23 AM" src="https://github.com/echasnovski/mini.nvim/assets/747855/7126a5e1-2c2f-4a25-aa23-74bf84772bea">

**Comment by abeldekat** [comment]
Very nice!

Now I don't have to override the whole diagnostic function anymore in order to have [colored](https://github.com/abeldekat/nvim_pde/blob/98e4f2ca31aa5c9f04d3982bddac797c9afdfe97/lua/ak/config/ui/mini_statusline.lua#L112) diagnostic signs.
Thanks!

![1717183012](https://github.com/echasnovski/mini.nvim/assets/58370433/93525d55-f50e-42ce-b6be-48ebe5739109)
