### ISSUE TITLE
[mini.basics] Toggling highlight search does not update mini.map

### ISSUE THREAD

**Issue by pkazmier** [echasnovski/mini.nvim#800]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.basics

### Description

The mini map is not refreshed when toggling highlight search via the `mini.basics` toggle `\h`. If I manually, type `:set nohls` or `:set hls`, the refresh works as expected. Based on the comment in this thread (https://github.com/echasnovski/mini.nvim/discussions/356#discussioncomment-6098993) I was under the impression `mini.basics` would refresh the map.

### Neovim version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

### Steps to reproduce

<details><summary>minimal.lua contents</summary>
<p>

```lua
-- Clone 'mini.nvim' manually in a way that it gets managed by 'mini.deps'
local path_package = vim.fn.stdpath("data") .. "/site/"
local mini_path = path_package .. "pack/deps/start/mini.nvim"
if not vim.loop.fs_stat(mini_path) then
  vim.cmd('echo "Installing `mini.nvim`" | redraw')
  local clone_cmd = {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/echasnovski/mini.nvim",
    mini_path,
  }
  vim.fn.system(clone_cmd)
  vim.cmd("packadd mini.nvim | helptags ALL")
  vim.cmd('echo "Installed `mini.nvim`" | redraw')
end

-- Set up 'mini.deps' (customize to your liking)
require("mini.deps").setup({ path = { package = path_package } })

MiniDeps.now(function()
  require("mini.basics").setup()
end)

MiniDeps.now(function()
  local map = require("mini.map")
  map.setup({
    integrations = { map.gen_integration.builtin_search() },
  })
end)
```

</p>
</details> 

1. `nvim -nu ./minimal.lua minimal.lua`
2. Type `:lua MiniMap.toggle()`
3. Press `/` and search for `vim` (map shows matches).
4. Press `\h` to toggle highlight search (map still shows matches, unexpected).
5. Type `:set nohls` (map no longer shows matches as expected).

### Expected behavior

I expect the mini map to refresh when I use `\h` from `mini.basics`.

### Actual behavior

The mini map does not refresh when I use `\h` from `mini.basics`.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is seems reasonable. However, I personally [have it overridden](https://github.com/echasnovski/nvim/blob/535ed97e480b89cb7e7e33c95f9559ba5091a0e3/src/mappings.lua#L35-L38) to force mode change. And it was like this since introduction of 'mini.basics'. I am not entirely sure why it is like it is, but I am sure there was a reason (probably to have all toggle mappings in 'mini.basics' consistently not trigger mode change).

I'll take a look into the best ways to resolve this: either update `\h` mapping in 'mini.basics' or document how it can be updated to work better with 'mini.map'.

**Comment by echasnovski** [comment]
In the end, I've decided to document how to do the custom mapping. Mostly because I do want 'mini.basics' mappings to be as consistent as possible (and not trigger mode change) while there is already a section for custom remaps in `:h MiniMap.gen_integration.builtin_search()`.

This should now be documented on latest `main`.
