### ISSUE TITLE
Highlight on Yank broken when using Mini.jump2d

### ISSUE THREAD

**Issue by BenjaminKern** [echasnovski/mini.nvim#83]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.jump2d

### Description

Mini.jump2d is interfering with custom yank on highlight autocommand

### Neovim version

v0.8.0-dev+198-g030417d80

### Steps to reproduce

Take the following minimial neovim config 

```
vim.call('plug#begin', plugged_path)
Plug('echasnovski/mini.nvim')
vim.call('plug#end')

vim.api.nvim_create_autocmd('TextYankPost', {
  pattern = '*',
  callback = function(args)
    vim.highlight.on_yank()
  end,
})

vim.keymap.set('n', 'Y', 'y$', { desc = 'Yank till the end of the line' })

local enable_jump2d = 0

if enable_jump2d == 1 then
require('mini.jump2d').setup({
  labels = 'etovxqpdygfblzhckisuran',
})
end
```
Open a file and press `y1<cr>` and observe, that the yanked lines are highlighted. Now set `enable_jump2d=1` and do the same again and observe, that the mini.jump2d labels are popping up.

### Expected behavior

Yank is properly highlighted with enabled mini.jump2d

### Actual behavior

Instead of highlighting the yanked lines, mini.jump2d labels are popping up

**Comment by echasnovski** [comment]
Thanks for making an issue!

The reason this is happening is that with `y1<CR>` you are using `<CR>` in Operator-Pending mode. By default it is mapped to `MiniJump2d.start()` in that mode also, but you seem to expect its default motion ("[count] lines downward, on the first non-blank character |linewise|").

There are several options here:
- Use `y2_` instead of `y1<CR>`.
- Use different mapping to start jumping. For example, `  require('mini.jump2d').setup({ mappings = { start_jumping = '<M-m>' } })`.

**Comment by BenjaminKern** [comment]
Yes, thanks for the explanation.
