### ISSUE TITLE
mini.files: error when `-` called on unsaved file

### ISSUE THREAD

**Issue by nat-418** [echasnovski/mini.nvim#840]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

If I open a new file and then try to navigate its parent directory using `-`,  I get an `E5108: Error executing lua: (mini.files) `path` is not a valid path` error. I don't think the file not being written should matter, since the parent directory exists.

### Neovim version

v0.10.0-dev-c81b784

### Steps to reproduce

1. `mkdir -p foo`
2. `echo "a" > foo/a.txt`
3. `nvim foo/b.txt`
4. press `-`

### Expected behavior

show me my directory explorer

### Actual behavior

error

**Comment by echasnovski** [comment]
This is intended and [documented](https://github.com/echasnovski/mini.nvim/blob/04f8d6e0acd5a52d01ec1c392e3947135dbfd8ef/doc/mini-files.txt#L647) behavior. Ensuring that path actually exists on disk simplifies code logic down the line by removing the need to do later checks.

Plus I assume that `-` calls `MiniFiles.open()` with the path of the current file, which should result with cursor placed on that file in the explorer. This is impossible because there is no file on disk (yet).

The cost of not being able to open explorer with focus on non-existing path seems OK for me.

Closing as not planned.
