### ISSUE TITLE
mini.clue: add option to hide keymaps

### ISSUE THREAD

**Issue by rafamadriz** [echasnovski/mini.nvim#864]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

clue

### Description

Hello, I would like to know if the option to hide keymaps is something you would be open to add. Similar to #863, this is a another feature from `which-key.nvim`  that can be useful for certain keys you really don't want to show up in the popup window for whatever reason. I know this is very specific and most people won't need it so it kinda goes against the *`mini`* part.

Here's an example, I know they don't have a description so it looks empty, but I simply don't want those to show up even if I added a description to them.

![edit](https://github.com/echasnovski/mini.nvim/assets/67771985/e2a3fd19-1ffc-4355-a622-98ab20cc2ecb)

If you're open to this let me know, I would be happy to implemented it. 

ref: https://github.com/folke/which-key.nvim/pull/391

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This has already come up in #490 with resolution that I don't think it is a good long term idea both for 'mini.clue' and users who manage their own config.

My suggestion would be to add description to those mappings: either by using `desc` option if those are created manually or with [`set_mapping_desc()`](https://github.com/echasnovski/mini.nvim/blob/5df3155218807fb6049779bb488f48f77fdd9dcb/doc/mini-clue.txt#L623) function otherwise (exported specifically for this purpose).

Closing as not planned.
