### ISSUE TITLE
mini.notify: transparency support

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#873]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.notify

### Description

Hello echasnovski. I have come across a problem where I want to enable transparency for mini.notify but am not able to. Even though I set the background to NONE for MiniNotifyNormal, MiniNotifyTitle and MiniNotifyBorder, transparency is not enabled for mini.notify. I am unable to figure out what to do and taught I could get some assistance by raising a bug request.

### Neovim version

v0.10.0-dev-3117+g4e5c633ed

### Steps to reproduce

Just use mini.notify and try enabling transparency.

### Expected behavior

Wanted transparency.

### Actual behavior

Transparency is not coming.

**Comment by echasnovski** [comment]
This is a bit broad question at the moment. Mostly because "transparency" can mean several things:
- If your primary concern is to see the text "below" the notification window, set [`config.window.winblend`](https://github.com/echasnovski/mini.nvim/blob/2d0f10540efdbb1f5c480ebe19ce4de451936a5d/doc/mini-notify.txt#L125-L126) option to 100 (for fully transparent window).
- If you primary concern is about inheriting color of window "below" the notification window, then setting `guibg=NONE` to relevant highlight groups is the way to go. Be mindful about the following potential issues:
    - Make sure that your color scheme is loaded *before* you make changes to highlight groups. Otherwise color scheme may override them.
    - Make sure to have `vim.notify()` also uses highlight groups without background (if that is where you want to have transparency). By default it uses the [following highlight groups](https://github.com/echasnovski/mini.nvim/blob/2d0f10540efdbb1f5c480ebe19ce4de451936a5d/doc/mini-notify.txt#L240-L247).

Without more detailed reproduction steps, I am afraid I can not help any further.

**Comment by 231tr0n** [comment]
![image](https://github.com/echasnovski/mini.nvim/assets/56352048/ae8df3f2-6c5a-43bf-b54f-310270f62a9a)
@echasnovski sorry for not being specific. What i wanted to achieve was something of this sort which I am not able to. As you can see in the image above the notifications background is totally transparent. Do you have any idea how can I achieve that. I use tokyonight.nvim theme and currently mini.notify looks something like this while I want something like the above.
![image](https://github.com/echasnovski/mini.nvim/assets/56352048/662563f4-044a-48b3-b353-dc278c118377)

**Comment by echasnovski** [comment]
> ```lua
> vim.cmd.colorscheme("tokyonight")
> vim.cmd("au ColorScheme * highlight MiniNotifyNormal guibg=NONE")
> vim.cmd("au ColorScheme * highlight MiniNotifyTitle guibg=NONE")
> vim.cmd("au ColorScheme * highlight MiniNotifyBorder guibg=NONE")
> ```

This is the main issue: you first enable color scheme and *after* that create autocommands that should react to color scheme change. Putting `vim.cmd.colorscheme("tokyonight")` after autocommands creation *should* solve the issue.

In reality, there needs to be one extra adjustment: use `config.window.winblend = 0` in 'mini.notify'. This is because with `winblend > 0` doesn't work nicely with "transparent" floating windows (see neovim/neovim#10685).

**Comment by 231tr0n** [comment]
> > ```lua
> > vim.cmd.colorscheme("tokyonight")
> > vim.cmd("au ColorScheme * highlight MiniNotifyNormal guibg=NONE")
> > vim.cmd("au ColorScheme * highlight MiniNotifyTitle guibg=NONE")
> > vim.cmd("au ColorScheme * highlight MiniNotifyBorder guibg=NONE")
> > ```
> 
> This is the main issue: you first enable color scheme and _after_ that create autocommands that should react to color scheme change. Putting `vim.cmd.colorscheme("tokyonight")` after autocommands creation _should_ solve the issue.
> 
> In reality, there needs to be one extra adjustment: use `config.window.winblend = 0` in 'mini.notify'. This is because with `winblend > 0` doesn't work nicely with "transparent" floating windows (see [neovim/neovim#10685](https://github.com/neovim/neovim/issues/10685)).

It works thank you for helping me out.

**Comment by andradei** [comment]
https://github.com/neovim/neovim/issues/10685 was the issue for me... confusing behavior.
