### ISSUE TITLE
Don't set terminal colors in base16

### ISSUE THREAD

**Issue by arcxio** [echasnovski/mini.nvim#899]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.base16

### Description

mini.base16 overrides terminal colors with a supplied palette, which results in different colors in a neovim terminal than the ones configured in a terminal emulator:
![image](https://github.com/echasnovski/mini.nvim/assets/94578451/040626eb-10ce-4c0f-ba92-547e052377c8)
What is the reason for this? I believe there should at least be an option to turn this behavior off, as I found it jarring: neovim terminal isn't expected to have its own colors

**Comment by echasnovski** [comment]
> What is the reason for this? I believe there should at least be an option to turn this behavior off, as I found it jarring: neovim terminal isn't expected to have its own colors

The reason for this is because I believe every buffer inside Neovim is expected to use colors from color scheme. If you don't want them, I'd suggest unsetting [`vim.g.terminal_color_x`](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/lua/mini/base16.lua#L1190-L1205) variables. Like `vim.g.terminal_color_0 = nil`, and make sure to do that *after* `require('mini.base16').setup()`.

Closing as both "works as expected" and "not planned".
