### ISSUE TITLE
endwise

### ISSUE THREAD

**Issue by xigoi** [echasnovski/mini.nvim#9]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

pairs

### Description

It would be nice to have [endwise](https://github.com/tpope/vim-endwise/blob/master/plugin/endwise.vim)-like functionality, either as a new module or as a part of `pairs`. It gets annoying to type `end` when editing Lua and tpope's plugin doesn't cooperate well with other plugins that map `<cr>` in insert mode.

I could try to implement it. Looking at tpope's code, it's not that complex.

**Comment by echasnovski** [comment]
At the moment I strongly think that this type of functionality is better suited for snippets (I personally use one for this). Definitely not in 'mini.pairs'.

**Comment by xigoi** [comment]
That's a good point. In that case, should we have a snippet engine `mini.snippets`?

**Comment by echasnovski** [comment]
I definitely thought about this. I plan to wait and see what Neovim core will do with snippet support for 0.7.

**Comment by megalithic** [comment]
@echasnovski; mind sharing how you use snippets for this? i'm assuming a snippet that fills out the `if thing then..end` block; if so, then yes this is great, but there are still cases where, for instance, in lua at least, `do<CR>` is faster (also am making assumptions about how one might have their completion plugin of choice setup).

**Comment by echasnovski** [comment]
> @echasnovski; mind sharing how you use snippets for this? i'm assuming a snippet that fills out the `if thing then..end` block; if so, then yes this is great, but there are still cases where, for instance, in lua at least, `do<CR>` is faster (also am making assumptions about how one might have their completion plugin of choice setup).

Basically, these steps:
- Install snippet plugin. At the moment I use [L3MON4D3/LuaSnip](https://github.com/L3MON4D3/LuaSnip) (until possible future 'mini.snippets' :) ).
- Define/install snippets you want to use. [rafamadriz/friendly-snippets](https://github.com/rafamadriz/friendly-snippets) is a great start. I prefer having all my snippets [manually defined](https://github.com/echasnovski/nvim/tree/master/misc/snippets).
- Use snippet engine. Either with completion plugin like [hrsh7th/nvim-cmp](https://github.com/hrsh7th/nvim-cmp) ('mini.completion' doesn't handle snippets by design; at least at the moment) or by manually triggering when you know the snippet should expand. I use a [somewhat hacky approach](https://github.com/echasnovski/nvim/blob/master/lua/ec/configs/luasnip.lua) to get notification if snippet can be expanded, which is more than enough for me.

**Comment by baggiponte** [comment]
There's also this [treesitter plugin](https://github.com/RRethy/nvim-treesitter-endwise) if you want to skip defining the snippets yourself.

**Comment by echasnovski** [comment]
Just as a form of closure, I'd mention that ['mini.snippets'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-snippets.md) is now part of 'mini.nvim'.
