### ISSUE TITLE
Add git conflict resolution

### ISSUE THREAD

**Issue by RaafatTurki** [echasnovski/mini.nvim#985]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.git, mini.diff

### Description

This is a very deep rabbit hole but some users (myself included) resolve their conflicts without multi-pane diffing using the bare git markers only.

My proposition here is giving mini.diff the ability to use git merge as a diffing reference for its extmarks (it would be nice to have a couple new markers such as `ours`, `theirs` if not then the same `add`, `change`, `delete` markers could be reused)

Furthermore mini.git could get a a keymap that accepts the hunk the curser is currently within (either the `ours` hunk or the `theirs` hunk)

> similar plugins:
[1](https://github.com/tjdevries/diff-therapy.nvim)
[2](https://github.com/akinsho/git-conflict.nvim)
[3](https://github.com/rhysd/conflict-marker.vim)
[4](https://github.com/christoomey/vim-conflicted)
[5](https://github.com/whiteinge/diffconflicts)
[6](https://github.com/mkotha/conflict3)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't see a usable/helpful way of integrating conflict resolution/visualization into 'mini.diff'. Conflict markers are searchable and quite visible text, so that working with them is as straightforward as possible.

Generally speaking, this feels like a job either for a general purpose text editing mapping or a full featured Git client (if there are some tricky edge cases I am not aware of). There is a suggested approach for the first one [in 'mini.bracketed'](https://github.com/echasnovski/mini.nvim/blob/a3f274633a57c713160baf51724ecfc051117877/doc/mini-bracketed.txt#L250-L255).

Closing as not planned.
