### ISSUE TITLE
Option to change what keys are mapped to fix macros

### ISSUE THREAD

**Issue by lostl1ght** [echasnovski/mini.nvim#998]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Hello!
I have remapped `q` and `Q` so that I don't accidentally start recording a macro when mashing `q` to close some windows.
```lua
vim.keymap.set('n', 'Q', 'q')
vim.keymap.set('n', 'q', '', { remap = true })
```

However, now I cannot record macros at all because pressing `Q` now throws an error:
```
E354: Invalid register name: '^@'
```
I'm guessing this is because mini.clue remaps `Q`.

Is it possible to add options to change what keys mini.clue maps in order to solve issues with macros?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The 'mini.clue' module indeed [does some things](https://github.com/echasnovski/mini.nvim/blob/7cd21b780e9891cb84e47198aa2ee20e184b8354/doc/mini-clue.txt#L90-L94) with macro recording. This is done so that it is possible to use keys with triggers inside macros.

It indeed remaps `@` (default key for replaying macro from *some* register) and `Q` (default key for repeating the last recorded register). Those keys are not arbitrary and are there to make replaying possible (mostly because there is no automated way to do that; see neovim/neovim#24565).

If you want your own mapping for `Q` instead of what 'mini.clue' does, the suggestion is to make own mapping *after* `require('mini.clue').setup()`.

Closing as not planned.

**Comment by echasnovski** [comment]
@lostl1ght, just FYI: as Neovim PR was not merged as fast as I hoped, I decided to alter the behavior of how 'mini.clue' creates `@` and `Q`. It now won't create them if the key is already mapped. All other points from previous comment still stand, though.
